### ISSUE TITLE
Remove STATE_NAME environment variable

### ISSUE THREAD

**Issue by cmroberts** [usdigitalresponse/usdr-gost#10]
This doesn't make senes in the context of a multi-tenant hosted app. Let's remove it from render and this repo altogether and update the e-mail format to include the tenant name after #6 is complete.

**Comment by mhuang-usdr** [comment]
Given that #6 is closed, is this bug ready to take on @cmroberts ?

**Comment by TylerHendrickson** [comment]
Note to self: Either close this out if no existing references or update this issue with findings if the env var is still in-use.
