### ISSUE TITLE
[ID] Add negative keywords using existing Keywords functionality

### ISSUE THREAD

**Issue by cajinajr** [usdigitalresponse/usdr-gost#1003]
In order to be roll out the negative keyword feature sooner than later, I designed a way for users to add negative keywords using existing keyword functionality. 

![Image](https://user-images.githubusercontent.com/16214088/220468441-3b33a26e-3965-4bb3-8fcf-a1640e3afd59.png)
_Screenshot of the user flow across multiple screens._

Some small changes to what currently exists: instead of a "Notes" column, there is now a column that identifies the "type" of the keyword. The "Search Term" and "Type" keyword can be used to sort the keywords alphabetically and by type. (I don't think there's a need to include a column header for "Action" since the only action you can take is delete.)
![Image](https://user-images.githubusercontent.com/16214088/220468898-6519dbc5-6ece-4e25-a461-a59c3fe98bc3.jpg)

The modal that pops up when the Add button is clicked just consists of an input field for the term and a drop down menu to set the inclusion or exclusion of the keyword from searches. The dropdown menu should be initialized with an option already set (i.e. set to be included, as seen below) so users understand the purpose of the dropdown.

![Image](https://user-images.githubusercontent.com/16214088/220469941-592f8504-3c7e-4a23-9eee-13920748a0cf.jpg)

![Image](https://user-images.githubusercontent.com/16214088/220470278-1a977fda-ac1a-432e-9df3-6adafe81d2b1.jpg)

**Comment by mhuang-usdr** [comment]
Add'l product context - this UI update is gating the full feature launch.
