### ISSUE TITLE
[ID] Clean up database so that there are no Users or Agencies with Null tenant IDs, and the agencies have the correct parents.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#102]

**Comment by mhuang-usdr** [comment]
Check

- [ ] Create Agency
- [ ] Create User

**Comment by chrisxkeith** [comment]
Both staging and prod have been:
- updated with the code fix
- NULLs manually replaced with real data
- migrations run
