### ISSUE TITLE
Non-numeric values are being accepted for numeric-type fields

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#1044]
This bug was reported in an email titled `[USDR Grants Eng Vols] [Grants HD] USDR ARPA Reporter bug - Non-numerical entries` sent to the grants-helpdesk email on Feb 13th. 

In the linked workbooks, Alysha points out that some users have out in non-numeric values (specifically the string 'N/A' in place of numbers. Here is an example:
![Screenshot 2023-03-03 at 9 35 26 AM](https://user-images.githubusercontent.com/3675290/222789315-b420322e-861c-4e85-b1ff-c7a80e02a709.png)

These values are eventually written to the generated ARPA report, and when that report is uploaded to treasury, that fails with an error because of the unexpected value.

We should add a validation that will throw an error whenever a numeric field has a non-numeric value.

**Comment by jcomeau1** [comment]
Why is this Done? It doesn't look like anything has been addressed.

**Comment by jcomeau1** [comment]
It looks like this was implemented some time ago (March, 2023). This can be closed.
