### ISSUE TITLE
Feature request: Add historical data to audit report

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#1059]
Partners have mentioned this as a request in several meetings now, and on at least one occasion a user described it as their number 1 priority: 

The audit report only includes the _current_ information for the various data types (projects, subrecipients, awards, expenditures). But for some of those fields, the historical data is still relevant and important to help with auditing and validation.

This was flagged primarily about monetary amount fields. In particular, in our workbooks we collect `` and `` for each project. But when we output that data to the bulk upload csvs those fields are actually given a new label in each quarter (e.g. `Q4_2022_Obligations__c` or `Q4_2022_Expenditures__c`). This historical data is important because the treasury keeps a record of the historical quarterly Obligations/Expenditures for each project, and will use those values to validate future values (a cumulative number can't be reduced in the future).

Adding the old quarterly values to the audit report would help partners detect errors sooner in their process.

Note: We should check with partner's if there are other field names that they would like to see historical data for, or if the quarterly Obligations and Expenditure numbers are enough.

**Comment by ClaireValdivia** [comment]
Re: 2/5 convo with Joe - this has been completed
