### ISSUE TITLE
In ARPA Reporter tool - server-side automated test timeout needs to be updated from 2 secs

### ISSUE THREAD

**Issue by swatisqa1** [usdigitalresponse/usdr-gost#1071]
When setting up Docker containers & running server-side tests - Chris noticed this issue. Pls update time out from 2 seconds to 10 seconds to match Grant Id timeouts.

  1) /api/exports
       "before all" hook for "returns a response for default period id":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/packages/server/__tests__/arpa_reporter/server/routes/exports.spec.js)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

![Image](https://user-images.githubusercontent.com/123099222/223489223-a5c89817-dde7-4a7b-a347-8cf5b6135587.png)

**Comment by jcomeau1** [comment]
This issue was implemented in March, 2023. Closing.
