### ISSUE TITLE
Critical Bug: Remove Expenditure Code from NewUpload field

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1083]
It appears that the feedback of removing the Expenditure Code from the new upload screen was never reflected. We must remove this from the screen as it's an unnecessary burden on the users. The EC comes from the Input Template itself. This should be treated as a high priority. This is related to #786 

![Upload Screen](https://user-images.githubusercontent.com/78866741/224113296-dd8dfb38-a6d0-4c38-9627-c369017241c0.png)

**Comment by NatHillardUSDR** [comment]
👍 - I mentioned this over at https://github.com/usdigitalresponse/usdr-gost/pull/1048/files#r1131345956 but I had been consulting the original screenshots which did have this field. It's not actually currently used on the backend so we can safely remove it. I can have a patch shortly
