### ISSUE TITLE
Derive Agency Code and Reporting Period Details exclusively from Form

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#1110]
# Background
This is followup to https://github.com/usdigitalresponse/usdr-gost/issues/895 , which made it so that we can specify the agency code and reporting period from our newly-provided form. 

As followup to this change, Joe made a version of the sheet that removes the need to store agency code and reporting period on the cover sheet, because we can now get this from the form instead. 

Now we need to update our app to both support this new template and update our validation logic.

From Joe:
As mentioned earlier, I have made a new version of the Input Template, v20230312, that removes the Agency Code, Reporting Period Start Date and Reporting Period End Date from the Cover sheet. I have also addressed all associated functionality including the ShowSheet, Reset Workbook, and Import Data functions. I have created two new test cases that, data-wise, are identical to their v20230305 counterparts, sans the above fields (see Materials below)

I have created two new test cases that, data-wise, are identical to their v20230305 counterparts, sans the above fields. I attempted to upload these, but I am getting errors;
![image](https://user-images.githubusercontent.com/120750336/225529953-339cda14-a577-475d-9956-4ae666c83536.jpg)

# Necessary changes
Input sheet:
- [ ] We will need to update the input template sheet itself - see [here](https://github.com/usdigitalresponse/usdr-gost/blob/_staging/docs/common-tasks/updating-input-templates.md) for instructions on how to do this
- [ ] (Address errors from the screenshot) We will need to update validation logic to pull agency code, reporting period start and reporting period end exclusively from our form, rather than from the spreadsheet. 

# Materials
[Files.zip](https://github.com/usdigitalresponse/usdr-gost/files/10987315/Files.zip)

**Comment by jcomeau1** [comment]
This is fully implemented by another issue. This can be closed.
