### ISSUE TITLE
[ID] Research data for dashboard

### ISSUE THREAD

**Issue by hadashirt** [usdigitalresponse/usdr-gost#112]
[] find where all the data is that we want to access for this feed 
[] if something cannot be found - note that so we can create a new issue 

Link to design doc: https://docs.google.com/document/d/1U1tL4y-5ivGDgFyukgIkkQQiCkr27sNSlQBk-oc0K_Q/edit?usp=sharing

**Comment by mhuang-usdr** [comment]
No real QA needed, but moving to the column for completion's sake
