### ISSUE TITLE
Audit Report not functioning in Production

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1132]
The partners have reported that they are getting the following error when trying to run the audit report:

![unnamed](https://user-images.githubusercontent.com/78866741/227272812-27deef27-efda-4e77-9f5b-954d5b2b1693.png)

It appears to be working fine on Staging.

**Comment by jcomeau1** [comment]
@as1729 As long as we don't mess with their data, there shouldn't be any issues.

**Comment by as1729** [comment]
Confirming that the reason this is happening is that it takes upwards of 30 seconds to generate an audit report but API gateway has a 30-second timeout. This is why the request is being served as 503 but the report is being successfully generated within ECS correctly after a while.

**Comment by as1729** [comment]
Aligning on the following solution:

1. User goes to dashboard and clicks on a button that says "Email the Audit report"
A background tasks kicks off to generate the audit report and then upload the audit report to S3. User just sees a confirmation in the webpage that say. Take a look in your inbox after 5 mins.

2. After a few minutes user receives an email that says "Link to download your audit report"


3. User clicks on the link and are able to download the link directly from S3
How long will this link stay active? It can expire within 7 days.

**Comment by jcomeau1** [comment]
I like the approach. To clarify, each time they click the audit report button, they will ultimately get a unique link?

**Comment by as1729** [comment]
> I like the approach. To clarify, each time they click the audit report button, they will ultimately get a unique link?

Correct, for now they will get a unique link each time they click the audit-report button. In future maybe we can look into caching that if there are no changes to the uploads. But I would say the scope of this work is to focus on unblocking the immediate issue. @TylerHendrickson can chime in as well.

**Comment by mhuang-usdr** [comment]
@jcomeau1 clarified that this is required by next week. @jcomeau1 can we say 3/31 to be specific?

**Comment by jcomeau1** [comment]
Yes, that's perfect.

**Comment by as1729** [comment]
@caitlinwinner 

This is the page where the "email me the audit report" button will show up. It is going to replace the "Download Audit Report" button.
![image](https://user-images.githubusercontent.com/6497366/228248710-cd1dc40b-db19-46f9-a79a-bdb446f94cfd.png)

**Comment by caitlinwinner** [comment]
Designs : https://www.figma.com/file/fER1DR0wvai9vkT4lgUS4a/Send-Audit-Report-By-Email?node-id=0%3A1&t=EByHBp7A0UcfVBik-1
