### ISSUE TITLE
Add URL masking to grants.usdigitalresponse.org

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#12]
examples: 

https://gost-grants-tools.onrender.com/ --> grants.usdigitalresponse.org
https://gost-grants-tools.onrender.com/login --> grants.usdigitalresponse.org/login

**Comment by mhuang-usdr** [comment]
The marketing content is already moved. Raph will be putting it up as a
part of his website redesign.

We'll likely bring some content back to this URL in the future, but I'm not
worried about having it up immediately as the current content is already
very outdated and we are not actively linking it to partners.

**Comment by mhuang-usdr** [comment]
As discussed with @cmroberts , as soon as this is done we'll do an internal announcement!

**Comment by cmroberts** [comment]
@mhuang-usdr You should go visit grants.usdigitalresponse.org :)

**Comment by cmroberts** [comment]
Archived https://github.com/usdigitalresponse/cares-website and added a CNAME record pointing grants.usdigitalresponse.org -> gost-grants-tools.onrender.com , which also redirects to the login page.
