### ISSUE TITLE
[SPIKE] Use Storybook to Visualize Component States

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#1205]
# Description
In a recent sync about frontend tech modernization, we discussed potentially using Storybook to visualize component states as we work on new screens. We should research how to bring this about in our project.

# Acceptance Criteria
* We have copied [this](https://www.notion.so/usdr/Duplicate-me-Architecture-Decision-Record-Template-79ad657a737f47838741017c743a4b4f) Notion template to a subpage of the [Tech Modernization page](https://www.notion.so/usdr/Tech-Modernization-b0f8e3736ebc4e9a898dad2b4ca2f858) named the same as this issue and have filled out the various sections appropriately
* We have added it as a link in the top-level [Tech Modernization page](https://www.notion.so/usdr/Tech-Modernization-b0f8e3736ebc4e9a898dad2b4ca2f858)

**Comment by thelmaboamah** [comment]
hey @NatHillardUSDR, worked on this [here](https://www.notion.so/WIP-Use-Storybook-to-visualize-component-states-59e9d92f0acd464b837097b328ddbea4). Was unsure about dates in the Phases section. Otherwise, anything important missing or can I make this as done?

**Comment by NatHillardUSDR** [comment]
Awesome - Great writeup! Let's plan to talk about this next week as part of our meeting on Tues - maybe for now you can move to "Review"?

**Comment by NatHillardUSDR** [comment]
I converted the Notion doc to an ADR [here](https://github.com/usdigitalresponse/usdr-gost/pull/1311) -- we an use this PR for further discussion
