### ISSUE TITLE
[SPIKE] Use Typescript

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#1217]
# Description
We have determined we need to migrate toward using Typescript in our project. Currently none of our code uses it. There are bigger questions about what our eventual stack should look like, but we do know we will need Typescript. We should write out a plan for how to incrementally adopt it. 

# Acceptance Criteria
* A decision record has been written within [./docs/decisions](https://github.com/usdigitalresponse/usdr-gost/tree/_staging/docs/decisions) documenting the decision

**Comment by Samcbehrens** [comment]
https://github.com/usdigitalresponse/usdr-gost/pull/1333

**Comment by ClaireValdivia** [comment]
Stopped this effort due to capacity
Want to assess typescript with broader discussion of re-platforming
