### ISSUE TITLE
[SPIKE] State Management

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#1218]
# Description
As we move toward a new React-based stack, we should look into the various state management libraries that are available and make a decision about which to go forward with.

- We currently use [Vuex](https://vuex.vuejs.org/) - we would need to move toward a different library in the React world.
- Tentative Example options:
    - Just [useReducer](https://react.dev/reference/react/useReducer) 
    - [Redux](https://react-redux.js.org/) + [Redux Toolkit](https://redux-toolkit.js.org/)
    - [Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction)

# Acceptance Criteria
* We have copied [this](https://www.notion.so/usdr/Duplicate-me-Architecture-Decision-Record-Template-79ad657a737f47838741017c743a4b4f) Notion template to a subpage of the [Tech Modernization page](https://www.notion.so/usdr/Tech-Modernization-b0f8e3736ebc4e9a898dad2b4ca2f858) named the same as this issue and have filled out the various sections appropriately
* We have added it as a link in the top-level [Tech Modernization page](https://www.notion.so/usdr/Tech-Modernization-b0f8e3736ebc4e9a898dad2b4ca2f858)

**Comment by Samcbehrens** [comment]
[Associated Notion doc](https://www.notion.so/usdr/WIP-Migrating-State-management-1ccff6b630894709bdc394aac560e81d)

**Comment by NatHillardUSDR** [comment]
PR [here](https://github.com/usdigitalresponse/usdr-gost/pull/1314) for GitHub version
