### ISSUE TITLE
Error in Aggregate Awards < 50000 sheet (column C)

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1256]
Similar to #1244 

To resolve this issue we need to:
- [x] Create new version of the Input Template (v20230419)
- [x] Create test case
- [x] Upload it to backend so the validation will be correct
- [x] Validate

**Comment by as1729** [comment]
@NatHillardUSDR is this something you have bandwidth to handle today? If not, I can make the PR and give it to you for review. Lmk what you prefer.

**Comment by jcomeau1** [comment]
I corrected the metadata and did a search through the entire workbook to ensure I didn't miss it anywhere else. Refer to Slack for the file. Once promoted to Staging, I will test.
