### ISSUE TITLE
**Urgent** Delete/Archive Unwanted uploads for CT

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1289]
Connecticut has several uploads that they need deleted so that they are not included in the upload to Treasury. If deleting these files isn't an option, then as long as they can be excluded from the Output (priority #1) and Audit report (priority #2) this will suffice.

The following files need to be addressed:
- 4ef0b69e (Test – 2.27)
- 9585a165 (Test – 1.7)
- Ec39a3c4 (Test – 1.11)
- De90c64b (Test – 1.11)
- 3ee59215 (Test – 2.18)
- E45b1efe (Test – 3.5)
- 4212f2eb (Test – 1.12)
- 13b08d17 (Test – 2.1)
- 4134c264 (OPM-2.18)

No data associated with these upload needs to be retained for any reason.

**Comment by as1729** [comment]
```js

const ids_to_delete = ['13b08d17-1535-44d1-bf35-eb88c41d9707', '3ee59215-bc29-4388-86f5-eb9b0f062911', '4134c264-8423-4381-898b-552d286dda6c', '4212f2eb-4b65-4dd7-ad4e-a531cbf4b170', '4ef0b69e-2e64-461d-b571-9141c8f891e2, '9585a165-11eb-472f-bb38-708d5911ae1a', 'de90c64b-8b0f-46a1-bcf7-8097e68e6bac', 'e45b1efe-6ea8-453c-8d26-647422808207', 'ec39a3c4-2df5-44c0-b097-741c502d07d3']

const filesToDelete = await knex('uploads').whereIn('uploads.id', ids_to_delete);

filesToDelete.length === 9

const result = await knex('uploads').whereIn('uploads.id', ids_to_delete).del()

```
