### ISSUE TITLE
[ID] Interested and Rejected Grants views should be Agency-scoped, not Agency+child-scoped

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#129]
Video explaining the issue here: https://www.loom.com/share/b98a1d6cd01e46b7a862c264ff07e9d2

**Comment by mhuang-usdr** [comment]
Initial eng context - the Interested Grants table only tracks the user_id

**Comment by bspates** [comment]
@mhuang-usdr Mind if I try this one out?

**Comment by mhuang-usdr** [comment]
It's yours! Once I get you added to this repo you can assign the issue to yourself.

**Comment by mhuang-usdr** [comment]
@bspates I can still see Interested, Rejected, and Assigned grants that are not for the agency I'm currently viewing as. I recorded a video to explain it a bit better. This is on `_staging`

https://www.loom.com/share/7370f6804fc14c59b590da603250e93e

**Comment by bspates** [comment]
@mhuang-usdr I just tried this on staging. Looks like it is scoped to your current agency and any subagencies. This becomes more obvious when switching to an agency with no subs.

**Comment by mhuang-usdr** [comment]
@bspates ah, it should be scoped to only your current agency, not any subagencies.

**Comment by mhuang-usdr** [comment]
This issue is fixed for Interested grants but not for Rejected grants. For Rejected grants, I am able to see all grants that anyone has rejected.

**Comment by as1729** [comment]
@mhuang-usdr I added an MR here that should resolve the issue you may be seeing. Let me know if the[ loom demo](https://www.loom.com/share/21ea1fd0f1be491aaf7cd8be8bfacbb9) looks right.
