### ISSUE TITLE
Enrich the existing ARPA Audit report with additional fields similar to CARES (CRF) Audit Report

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#1303]
## Context
The CARES act reporting was primarily project-based, however, the ARPA reporting is primarily based on expenditure codes. Partners have indicated that internally they find it easier to audit the data on a project-basis so we would like to update the audit report to have a richer set of project summary data.

## Columns to Add by Sheet
- @jcomeau1 will be filling this out based on partner feedback

### Format
<sheet_name_1>
- <column_name_to_add_1>
- <column_name_to_add_2>

<sheet_name_2>
- <column_name_to_add>

## Initial Thoughts
There are some columns in the CARES (CRF) audit report that we can mimic for a more in depth comparison of data (by Project and by Subaward ID):

Adopted Budget
Project Expenditure Category Group
Total Aggregate Expenditures
Total Expenditures for Awards Greater or Equal to $50k
Total Aggregate Obligations
Total Obligations for Awards Greater or Equal to $50k
Project Expenditure Category
Total Cumulative Obligations
Total Cumulative Expenditures
Project Description
Number of Subawards
Number of Expenditures
Completion Status
Evidence Based Total Spend
Structure and objectives of assistance program
Recipients approach
Industry Experienced 8 Percent Loss
Number of Workers K 12
Small Businesses Served

## Engineering Resources
- Cares reporter audit report code can be found here: https://github.com/usdigitalresponse/cares-reporter/blob/master/src/server/lib/audit-report.js
- ARPA reporter audit report generation code is found here: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/lib/audit-report.js
- Vide of a walkthrough with @jcomeau1 on the requirements : https://drive.google.com/drive/folders/1agoYSLgoahykZwwnZnm07bWRSyfqWQyv?usp=sharing
-

**Comment by as1729** [comment]
@ajhyndman has the most experience here.

Timeline
- We should have this ready by next reporting cycle.

Raw Notes
```
Enhancing the US Treasury audit report that UDSR is generating
IDs are more important
Audit reports are more important than online validations. The partners always prefer the audit report.
Go through what we have for the audit report
Talk about what additional fields we want added to this
In some instances its adding a new tab to add additional information.
ARPA
EC view


Project view
Partners prefer this
CRF
This is over and done with. That was the quarterly reporter.
The Cares act created the CRF.
American recovery created ARPA.
The CRF had an audit report that was better than the existing ARPA report.
Find out if the total obligations have changed/exceeded
The data in a usable format.
Firm up with fields and the tabs, we need to write it out. Closer to a data dump.
Next steps
Improve the ticket to add certain fields
Andrew has the most experience here.
```

**Comment by as1729** [comment]
Additional datapoint that underscores the importance of this work is captured in this ticket created by a partner #1349 
> Include all expenditure data reported by project ID, and by subaward #, and by quarter - to assist State's in finding calculation issues as reports are loaded into the Reporter (instead of waiting on Treasury validations) and to assist in reconciling projects to our accounting system. This is Ohio's https://github.com/usdigitalresponse/usdr-gost/pull/1 priority!

**Comment by as1729** [comment]
@jcomeau1 to attach an example cares audit report

**Comment by jcomeau1** [comment]
Attached, you will see what the CRF Audit Report looked like. There will definitely be differences with ARPA as CRF didn't have expenditure categories, but the basic intent of the fields they are looking for, especially on the Project tab, of the ARPA audit report are there.

While the Project Identifier is key on the following sheets in the CRF example, we would combine the 2nd and 3rd below into a single sheet on the ARPA audit report:
- Project Summaries
- Aggregates Awards < 50000
- Aggregates Payments to Individuals

[audit report 23-05-04.xlsx](https://github.com/usdigitalresponse/usdr-gost/files/11482231/audit.report.23-05-04.xlsx)

**Comment by as1729** [comment]
@mhuang-usdr where did you get these initial column list from? Was that from discussion with partners by any chance?

**Comment by as1729** [comment]
Next steps:

- @jcomeau1 to work with partners to identify what they would need in the audit report and the format they would need it in.
- Attach a template with columns and sheet names of what the final product should look like. The row numbers may be empty.

**Comment by mhuang-usdr** [comment]
@as1729  - it looks like @jcomeau1 edited the initial description with the column list. So I fully defer to @jcomeau1 for that answer!

**Comment by as1729** [comment]
Adding this raw notes file that @jcomeau1 and I worked on. Will be cleaning it up to present it to our partners tomorrow.
[sample_report.xlsx](https://github.com/usdigitalresponse/usdr-gost/files/11680302/sample_report.xlsx)

**Comment by jcomeau1** [comment]
Addresed by #1894
