### ISSUE TITLE
Create backend functionality / API calls to obtain data for recent activity column

### ISSUE THREAD

**Issue by hadashirt** [usdigitalresponse/usdr-gost#132]

**Comment by mhuang-usdr** [comment]
QA: Recent Activity Column shows up as blank.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/91221265/181130998-3961c97a-16d5-4932-9139-6743fd676ebd.png">

**Comment by cavukovic** [comment]
Issue was fixed so closed again

**Comment by mhuang-usdr** [comment]
QA: LGTM
