### ISSUE TITLE
[ARPA P&E Reporting] ability to run spell check in the upload workbook

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1345]
**Submitted Description:**

**(Optional) Uploaded file - click to download:**

**Comment by as1729** [comment]
As per the reporting call on 5/11 @jcomeau1 is going to look into seeing how we can enable spell checker on the excel workbook. Currently it looks like the workbook is locked down for the users and spellcheck is disabled.

**Comment by jcomeau1** [comment]
I have added a Spell Check button to each of the EC sheets. I'll validate with the partners whether this should be added to any other sheets. Upon clicking the button, the protection will be disabled and only the user-enterable fields will be checked, allowing the user to make changes as needed. Upon closing the spell checker, the protection will be re-applied.

This has been added to v20230523.

**Comment by jcomeau1** [comment]
Based on partner feedback, I added the Spell Check button to the Subrecipient and Awards > 50000 sheets as well.

This has been added v20230604.
