### ISSUE TITLE
[ARPA P&E Reporting] Subaward City Name

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1347]
**Submitted Description:**
can the tool remove any periods in the Subaward city name when it goes to the Report export (treasury import)? The portal kicks back an error in this field if a period is included. 

## Context
Users fill out submit an excel workbook for upload through the "Submit Workbook" flow in the the arpa reporter tool.

## Current State
When the upload is submitted we are not throwing an error when there is a `.` character in the "Subaward City name" field.

## Ideal State
When the upload is submitted we should throw a validation error when a `.` character is found in the "Subaward City Name" field.
Ex: `St. Louis` results in an error

## Eng Resources
- Where the upload happens on the front-end: https://staging.grants.usdr.dev/arpa_reporter/new_upload
- Upload validation begins here: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/validate-upload.js#L570

**Comment by as1729** [comment]
@jcomeau1 do you have any context here by any chance?

**Comment by as1729** [comment]
Ideally if there is a `.` character in the sub-award city-name this should throw an error during an upload validation

**Comment by jcomeau1** [comment]
This item is referring to Place_of_Performance_City__c (column U on the Awards > 50000 sheet). While I wonder if there are other special characters that aren't allowed as well, we can always add a new issue to address that.

**Comment by jcomeau1** [comment]
In the partner meeting today, the following clarifications/desires were made:

1. Currently unknown if only alpha characters can be used, so limit just to the "." for now
2. Ideally, issue a WARNING upon upload if a "." is present
3. Ideally, strip the "." from the name and store/send to US Treasury

Numbers 2 & 3 should be done together. If we can't do it in time, then it would be best to issue an ERROR if a "." is present.
