### ISSUE TITLE
[ID] A staff user should not be able to add a new agency

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#135]
The "Add" button should not appear for a staff user. It should only appear for Admin users.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/91221265/179624203-64a1db17-7549-48bd-b8b7-6c04667181c7.png">

**Comment by slants3** [comment]
I can take a look at this

**Comment by slants3** [comment]
This should be done no?

**Comment by mhuang-usdr** [comment]
feel free to close issues @slants3 ! 

Also, if you say "Fixes #xx" in the pull request, I believe Github will automatically link and close the issue once the PR is in.
