### ISSUE TITLE
[ARPA P&E Reporting] Some subaward fields not required for all EC's

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1350]
**Submitted Description:**
Subaward tab - Purpose of Funds and Primary Sector (Columns M-O) should only apple to EC 1.10, EC2.25-2.36, and EC4.1-4.2). 

**(Optional) Uploaded file - click to download:**

**Comment by as1729** [comment]
@jcomeau1 if you're able to help provide some context here-

- Is this a workbook-only change or do we need to update our backend in anyway?
- Is this work important to be completed by June 30th or the second quarter deadline?

**Comment by as1729** [comment]
This is more about the input template. @jcomeau1 has to do some investigation. The guidance says one thing but the portal works another way and Treasury has aligned the portal with the guidance so we need to re-align this.

**Comment by as1729** [comment]
It would be very helpful to be done by the July 31st prior to the deadline to submit in the IRS portal for the partners.

For any template related changes we should do it 2 weeks before the deadline so the feature should be available by July 15th.

**Comment by jcomeau1** [comment]
On the sheet Awards > 50000, columns M, N and O (Primary Sector, Other, Purpose of Funds) are now all Conditional and will only appear for the following ECs: 1.10, 2.35, 2.36, 4.1 and 4.2. Note that the original comment above states 2.25-2.36, but I believe that is a typo. I'll confirm.

This has been added to v20230523.

**Comment by jcomeau1** [comment]
Confirmed that the affected ECs are 1.10, 2.35, 2.36, 4.1 and 4.2.
