### ISSUE TITLE
BUG: FK constraint violation when deleting agencies

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#1395]
**Description:** An agency that has assigned users assigned cannot currently be deleted. Instead these requests to the `DELETE /api/organizations/:organizationId/agencies/del/:agency` endpoint fail with a 500 status code because of the following error being thrown on the backend: 
> `error: delete from "agencies" where "id" = $1 and "parent" = $2 and "name" = $3 and "abbreviation" = $4 and "warning_threshold" = $5 and "danger_threshold" = $6 - update or delete on table "agencies" violates foreign key constraint "email_subscriptions_agency_id_foreign" on table "email_subscriptions"`

**Steps to reproduce:**
1. Login as a user with permission to create agencies (e.g. tenant admin).
2. Create a new agency for the tenant.
3. Create a new user assigned to the newly-created agency.
4. Ensure that the browser's developer console is recording requests, and attempt to delete the newly-created agency. Observe that although the modal closes, the request fails with a 500 response code and the error message documented above is logged.
5. Delete the newly-created user.
6. Once again, attempt to delete the newly-created agency. Observe that the deletion is successful.

**Impacts:**
- User experience: there is no message communicating that the agency failed to delete.
- User experience: it is unclear that an agency with associated users cannot be deleted (or whether that an intentional constraint).

**Desired behavior:**
Currently unclear what the best UX would be – when deleting an agency, should all associated users be automatically deleted as well (and the request succeeds), or should we inform the admin user performing the deletion that agencies with users cannot be deleted (and that they need to manually delete those users first)?

**Implementation details**
Depending on desired behavior:
1. Users should be automatically deleted when their associated agency is deleted:
    -  Update the handler's execution path to check for and batch-delete users associated with the agency being deleted prior to issuing the `DELETE from "agencies" ...` query. 
    - Alternatively (and more atomically), adjust the `DELETE from "agencies" ...` query to appropriately cascade to records associated with the agency (including users and their associated records).
2. The UI should convey an error message that an agency cannot be deleted because it has assigned users.
    - Update the handler's execution path to check for associated users before attempting to delete the agency. If associated users are found, issue a 400 response that conveys the nature of the problem.
    - Update the UI to react appropriately when (400 status) responses containing errors are received by the client upon form submission.

**Comment by TylerHendrickson** [comment]
cc @caitlinwinner for input on desired behavior.

**Comment by mhuang-usdr** [comment]
Related: https://github.com/usdigitalresponse/usdr-gost/issues/1197

**Comment by agn-dsgn** [comment]
Design recommendations here!
I have suggestions for a **short-term** and a **long-term** solution based on constraints discussed with @mhuang-usdr and @caitlinwinner 

# Solutions
### SHORT TERM
- Every confirmation dialog appears the same
- No change in system behavior
- IF delete action fails for whatever reason, throw a toast in the UI for the user to see

Text:
`Are you sure you want to delete this agency? This action cannot be undone.`

### LONG TERM
- Error messages appear in dialog as needed
- Show counts of each so user can make informed decision
- Team members and sub-teams automatically deleted if user continues

Text:
`Are you sure you want to delete this team? This action cannot be undone.`
`This team has [X] team member[s]. If you continue, each user will be deleted from [Tool name].`
`This team has [Y] sub-team[s]. If you continue, each sub-team and its members will be deleted from [Tool name].`

![Screenshot 2023-05-24 at 2 16 56 PM](https://github.com/usdigitalresponse/usdr-gost/assets/127222088/705cdab1-989f-4606-a3e9-44859cf6cdf9)


Designs saved here: [Figma: Admin settings and user management](https://www.figma.com/file/UocTxQwwFb58ze7kvIO6on/Grants---Admin-settings-and-management?type=design&node-id=278-23282
)
