### ISSUE TITLE
BUG: Sorting grants by "Viewed by" or "Interested Agencies" fails

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#1396]
**Description:** Users browsing grants on either the "Browse Grants" or "My Grants" tabs in the ID tool have the option of sorting the results table by certain columns. However, when attempting to sort by "Viewed by" or "Interested agencies", requests to `GET /api/organizations/:organizationId/grants` fail with a 500 status code because of an error thrown on the backend due to a malformed Postgres query:
> `select distinct "grants".* from "grants" left join "grants_interested" on "grants"."grant_id" = "grants_interested"."grant_id" where ("eligibility_codes" ~ $1 and "description" ~* $2) order by "grants_interested"."grant_id" asc, "grants"."grant_id" asc limit $3 - for SELECT DISTINCT, ORDER BY expressions must appear in select list`

**Steps to reproduce:**
1. Login to the ID Tool (role doesn't matter)
2. Navigate to the "Browse Grants" tab.
3. Ensure that the browser's developer console is recording requests, and attempt to sort the results based on the "Viewed by" column. Observe that the request fails with a 500 response code and that the order of results in the UI does not change.
4. Attempt to sort the results based on the "Interested Agencies" column. Observe that the request fails with a 500 response code and that the order of results in the UI does not change.
5. Optionally, navigate to the "My Grants" tab and assuming there is a non-empty list of results, repeat steps 4 and 5 on that tab. The observed results should be the same.

**Impacts:**
- The sort feature for both columns is broken for users, although no error is presented.

**Desired behavior:**
- ~~Users are able to sort grants based on the "Viewed by" column.~~
- ~~Users are able to sort grants based on the "Interested agencies" column.~~
- Users don't have the option of sorting by the "Viewed by" and "Interested agencies" fields (i.e. remove this feature).

**Implementation details:**
- UI: Remove `sortable: true` option for the columns keyed by `viewed_by` and `interested_agencies` from the [`packages/client/src/components/GrantsTable.vue` component](https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/client/src/components/GrantsTable.vue#LL101C1-L108C11).
- API: 
  - Remove the conditional sort functionality for `viewed_by` and `interested_agencies` fields in the `getGrants()` function ([defined here](https://github.com/usdigitalresponse/usdr-gost/blob/f6531c40b4e7dd329cb2cf59d86f9756a8d97477/packages/server/src/db/index.js#L420-L437)).
  - Ensure that user-selected sorting behavior is only available for known input. Specifically, the only values that should be honored in the `?orderBy` query string argument are those that match one of the following literal strings: `award_ceiling`, `open_date`, `close_date`. In all other cases, this argument should be ignored completely to help protect against unsanitized input.
- **Leaving for the sake of completeness, but the following information is no longer relevant to achieving the desired behavior.**
  - As the error message indicates, `SELECT DISTINCT ...` queries in Postgres that contain an `ORDER BY` expression must include all `ORDER BY` columns in the `SELECT` expression as well. Generally, the simplest solution is to update the `SELECT` expression accordingly. However, under certain use-cases, it may not be desirable for the database to fetch all of these columns. In these cases, it may be necessary to wrap the existing query as a subquery that can select a subset of the columns selected in the subquery. For example:
      ```sql
      -- This query, which is invalid:
      SELECT DISTINCT a, b
      FROM my_table
      ORDER BY c
      
      -- Becomes this query, which is valid:
      SELECT DISTINCT a, b, c
      FROM my_table
      ORDER BY c
      
      -- Or this query, which is also valid:
      SELECT inner.a, inner.b
      FROM (
        SELECT DISTINCT a, b, c
        FROM my_table
        ORDER BY c
      ) inner
      ```

**Comment by ClaireValdivia** [comment]
proposal is to close this ticket and create a new one that is just to remove the sort, as we expect recommendations from Collab to rework interested feature

**Comment by ClaireValdivia** [comment]
disregard previous comment
