### ISSUE TITLE
Add USDR branding

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#14]
Add USDR logo to:

- [ ] Login page
- [ ] in-app header
- [ ] favicon

**Comment by mhuang-usdr** [comment]
Assets are here: https://drive.google.com/drive/u/1/folders/1TX60SQFpUj3GuocheB38ZXSG_yzuZZwu

**Comment by davidbkay** [comment]
slight issue with the USDR branded favicon...IMO the text ends up too small to be useful. @mhuang-usdr or @Raphomet LMK how you'd like to adjust it.

![image](https://user-images.githubusercontent.com/16613132/163700704-83dbe906-ac3c-456e-bd0c-02850b7a2edf.png)

**Comment by mhuang-usdr** [comment]
The favicon size seems okay. We should aim to match the one of the main site: https://www.usdigitalresponse.org/ 

Left aligned for the login page banner!

Thanks David :)

**Comment by Raphomet** [comment]
Try this favicon instead, hopefully it's less blurry. ![image](https://user-images.githubusercontent.com/58006/163879936-4eaf8da8-d12c-40b8-bd4b-748a439c3dcc.png)

And yes, left aligned please!

**Comment by davidbkay** [comment]
@mhuang-usdr merged to staging

**Comment by mhuang-usdr** [comment]
The login banner and favicon look good! I can't seem to actually log into staging though

**Comment by mattbroussard** [comment]
fyi #64 (merged recently) added some copy to this login page; I'm guessing it will not require additional changes here unless you've significantly changed the structure of the page (in which case you might get a merge conflict).

**Comment by mhuang-usdr** [comment]
I logged into the new staging environment https://gost-grants-tools-staging.onrender.com/#/login and checked it out. 

all LGTM
