### ISSUE TITLE
Spike - filter logic 

### ISSUE THREAD

**Issue by Samcbehrens** [usdigitalresponse/usdr-gost#1410]
# Summary 
The filter logic is central to this feature, and we must figure out the best way to apply the filter. 

# Acceptance Criteria 
* Write a doc on filter logic 
* The logic needs to handle individual filters or multiple filters. 
* It must also have to handle individual term changes to a set of filter terms. 
* Doc should include API design to handle new endpoint.

**Comment by ClaireValdivia** [comment]
@joshgarza  fyi that we have shifted our approach to search and landed on the following functionality for the current milestone - just want to make sure you're aware as you're working on this ticket. CC @TylerHendrickson 

Searching is like writing an old, MS Word file that doesn’t have autosave. Just as you can:
- Create a document
- Open an existing document
- test what you want to write in that document
- save the document with the changes you like
- Delete the document

so too you can
- create a new search
- Open an existing search
- test out the search
- Save the search with the changes you like
- Delete a search

**Comment by kevin-kasunic** [comment]
Blocking front end advanced search - primarily #1404
