### ISSUE TITLE
Create saved search name component

### ISSUE THREAD

**Issue by misspran** [usdigitalresponse/usdr-gost#1417]
- create save new search UI component
  - save new search name input
  - save button: does not need to be functional yet will be hooked up on next ticket, [1418](https://github.com/usdigitalresponse/usdr-gost/issues/1418)
  - cancel button: does not need to be functional yet will be hooked up on next ticket, [1418](https://github.com/usdigitalresponse/usdr-gost/issues/1418)
  - close button: functionl

<img width="317" alt="Screenshot 2023-05-22 at 3 57 55 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/3173822/bcd53c9a-2821-435f-91ba-0e5fd50884e9">

Figma: https://www.figma.com/file/TRONzuKDV3K9gzWZAwJ7ma/Search-Experience?type=design&node-id=409-24288&t=eI1VCE0HMam5HXsr-0

**Comment by ClaireValdivia** [comment]
This ticket is no longer applicable; archiving ticket.

**Comment by misspran** [comment]
This branch exists in case it ever reopens: https://github.com/usdigitalresponse/usdr-gost/tree/1417-saved-search-name
