### ISSUE TITLE
Create saved search detail popover menu

### ISSUE THREAD

**Issue by jakekreider** [usdigitalresponse/usdr-gost#1453]
### Description
Create a popover menu to display on click of the kebab menu within a Saved Search Details

### Acceptance criteria ([design](https://www.figma.com/file/TRONzuKDV3K9gzWZAwJ7ma/Search-Experience?type=design&node-id=1381-49345&mode=design&t=csk7QBLaMYuLwRV3-4))
* Popover displays when kebab menu is clicked, showing Edit and Delete options
* Clicking or focusing outside of the menu closes it

### Parent ticket
* https://github.com/usdigitalresponse/usdr-gost/issues/1370

**Comment by ClaireValdivia** [comment]
*This needs to be updated - confirming with Caitlin but pretty sure three options will be:
View Results
Edit
Delete
