### ISSUE TITLE
fix failing tests & add GH actions

### ISSUE THREAD

**Issue by User1m** [usdigitalresponse/usdr-gost#149]
Server tests on main are not passing. Needs to be fixed.

Also add automated CI to run tests on each push

<img width="611" alt="Screen Shot 2022-07-20 at 11 20 36 PM" src="https://user-images.githubusercontent.com/4316022/180143364-6715e0b1-2bc4-442c-8705-bb19b98d4234.png">

**Comment by mhuang-usdr** [comment]
QA: Not needed.

Thank you for your code health contributions Claudius!
