### ISSUE TITLE
[ID] Remove Covid-related default keywords from Keywords 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#15]
Under https://gost-grants-tools.onrender.com/#/keywords, currently we have a bunch of pre-seeded keywords. Partners have given feedback that this is no longer as helpful since CARES is wrapping up, and they tend to delete it and replace it with other keywords instead.

**Comment by mattbroussard** [comment]
Started looking at this as a starter task (don't seem to have permission to claim/assign it on github?). Some observations and questions:

- The keywords are seeded into the database for each agency listed when `npx knex seed:run` is run. Are we good with just removing them from the [hardcoded list](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/seeds/dev/ref/keywords.js#L3) for future runs of this (i.e. newly added agencies) or do we want to also run a migration(?) to remove these rows for existing agencies?
- There are unit tests for permissions logic related to the `keywords` table and associated routes and [some of them](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/__tests__/api/keywords.test.js#L51) expect these pre-seeded rows to exist for every agency. What sort of environment(s) do the tests run in and is it safe for a test to insert rows for the purpose of the test?
- We also seed a [single global `keywords` row](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/seeds/dev/ref/keywords.js#L30) with empty string query and NULL agency_id. What is this for?
- What is the `mode` field on the `keywords` table used for? It seems to be set to `autoinsert ALL keywords matches` for the pre-seeded keywords and empty string for keywords created by users.

**Comment by mhuang-usdr** [comment]
> The keywords are seeded into the database for each agency listed when npx knex seed:run is run. Are we good with just removing them from the [hardcoded list](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/seeds/dev/ref/keywords.js#L3) for future runs of this (i.e. newly added agencies) or do we want to also run a migration(?) to remove these rows for existing agencies?

Since we'll need to set up new tenants and new agencies from scratch anyways, removing for future runs only is fine.

I do not have answers to the other questions, but I'll get you access to the tool for you to poke around in case it helps to answer!
