### ISSUE TITLE
Revised Guidance for Broadband Projects

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1525]
From US Treasury:
=================
Dear SLFRF Recipient:  

You are receiving this email to notify you about an update to the Compliance and Reporting Guidance for the State and Local Fiscal Recovery Funds (SLFRF) program, specifically around data collection for following three broadband expenditure categories:
 
- EC 5.19: Broadband: “Last Mile” projects
- EC 5.20: Broadband: IIJA Match
- EC 5.21: Broadband: Other projects

If you do not have or intend to have projects categorized under the above broadband expenditure categories, you do not need to take any action.

**If you DO have or intend to have broadband projects under the above categories, please review the guidance to make sure you make any applicable changes for your Quarter 2 2023 reporting.**

As reflected in the updated guidance and beginning with your July 2023 Project and Expenditure (P&E) Report, Treasury will have the following updates to your broadband project reporting requirements. These are:

1. **Fabric ID# and FCC Provider ID#** – All broadband location files will now be required to include standardized FCC Identifiers.  This includes the Fabric ID # (Broadband Serviceable Fabric Locations) and FCC Issued Provider ID #s.
2. **Location Template Requirement** – All broadband projects will now be required to provide location data files, not just completed projects. The existing options to answer “No” to the question of “Do you have a broadband location file to upload?” and providing an explanation will continue to be available for recipients who need it.
3. **Location Template Bulk Upload** – All broadband location data files will now be uploaded using the bulk upload process within the P&E report. Recipients will use the broadband location data template as in previous quarters but will be expected to load it through the new process. Instructions will be provided within the report screen itself. This template can be found on the [Recipient Compliance and Reporting Responsibilities](https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/state-and-local-fiscal-recovery-funds/recipient-compliance-and-reporting-responsibilities) page and is available for [download](https://home.treasury.gov/system/files/136/Broadband-Infrastructure-Location-Data-Template.xlsx).

Treasury looks forward to working with you to ensure the continued success of the program.   

Thank you,

**Office of Recovery Programs
U.S. Department of the Treasury**

**Comment by jcomeau1** [comment]
#1 above definitely affects the Input Template and output templates. If we add the location data to the input template (with associated output template), only then will #2 and #3 affect us.

**We will need to put this in place for Q2 reporting.** We'll have to see if we can get the details (Treasury Field IDs and output template formatting/impact.

**Comment by jcomeau1** [comment]
I have added fields Fabric_ID__c and FCC_Provider_ID__c (columns BR and BS) to sheet **EC 5 - Infrastructure**. They are Required, and will only show, for EC 5.19 - 5.21.

This has been added to v20230615.

**Comment by as1729** [comment]
This was QA'd and confirmed by @jcomeau1 in the staging environment as part of PR #1535 . Since we can't push these changes directly to production we have cherrypicked these commits into #1546 to push directly to production.

**Comment by jcomeau1** [comment]
Re-closing this. Issue #1547 has been created to update the output template associated with this change.
