### ISSUE TITLE
(1)Integrate frontend template and backend API for the Upcoming Closing Dates

### ISSUE THREAD

**Issue by anigonzales** [usdigitalresponse/usdr-gost#153]

**Comment by mhuang-usdr** [comment]
QA: It looks like the changes from #225 (feedback from the UXD) got reverted.

- The colors need to be changed
- The dates should be bolded
- Looks like the agency list under the grant isn't showing up

Currently:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/91221265/183788866-56305931-f284-4b09-b70a-d7b69c5d1ff9.png">


Used to be:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/91221265/183788505-57b84680-aaf5-4f71-bd22-c1e3fa4bb946.png">


@anigonzales

**Comment by anigonzales** [comment]
@mhuang-usdr QA changes addressed in #247

**Comment by mhuang-usdr** [comment]
@anigonzales should this issue be closed?
