### ISSUE TITLE
Archive RI templates from prior reporting period

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1545]
The following uploads should be removed from RI. If you need more information, just let me know.

- File Name: 10003 - HHS3 - EC1.12 - EI Provider Relief and Recovery - 033123 SFRF Reporting Workbook - v1 (1).xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/7b0717ca-a730-4d68-9624-fe7f4a564a19

- File Name: 10005 - DCYF - EC2.36 - DCYF Workforce Stabilization - 033123 SFRF Reporting Workbook - v1.xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/d7a0bd85-b28f-4e36-b8d5-3b863e62abc0

- File Name: 10008 - EOC - EC2.29 - Small Business Direct Grants - 033123 SFRF Reporting Workbook - v1.xlsm 
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/9c1ca3a8-c571-4068-afb4-a86297397857

- File Name: 10015 - EOC - EC2.12 - HTE Marketing ARPA - 033123 SFRF Reporting Workbook - v1.xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/4ee7f82d-6cc2-4d50-b8e6-0eef0021847b

- File Name: 10035 - DLT - EC2.10 - Enhanced Real Jobs - 033123 SFRF Reporting Workbook - v1.xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/d65ec728-100e-4f14-aaf2-d1b38efd8d45

- File Name: 10042 - DOA5 - EC2.36 - Health Care Facilities For-Profit Hospital Assistance - 033123 SFRF Reporting Workbook - v1 (1).xlsm 
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/c39a6c12-47d1-4bff-bd30-5585d7b6bb3e

- File Name: 10042 - DOA5 - EC2.36 - Health Care Facilities For-Profit Hospital Assistance - 033123 SFRF Reporting Workbook - v1 (1).xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/c39a6c12-47d1-4bff-bd30-5585d7b6bb3e

- File Name: 10044 - DOA (HSRI) - EC2.6 - Auto-Enrollment Program - 033123 SFRF Reporting Workbook v1 (3).xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/7926f26a-4d73-4b66-974d-30172a35c958

- File Name: 10047 - DOA 3- EC2.34 - Health Care Facilities Health Center Assistance - 033123 SFRF Reporting Workbook - v1 (1).xlsm
Link: https://grants.usdigitalresponse.org/arpa_reporter/uploads/a8eae349-06cc-4f74-85c0-9eb08bd6db15

**Comment by as1729** [comment]
This is resolved thanks to @tzinckgraf 's PR!! 

@jcomeau1 I confirmed by generating an Audit report and made sure that these uploads are not reflected in there.

**Comment by as1729** [comment]
The process to resolve was:
1. Login to the tool as the tenant
2. Open the Chrome dev console
3. Update the `ids` with the upload ids
4. Run the script
```
const ids = ['id1', 'id2'];
const urls = [];
ids.forEach((id) => urls.push(`https://api.grants.usdigitalresponse.org/api/uploads/${id}/invalidate`))

urls.forEach((u) => fetch(u, { method: 'POST' }).then(console.log));
```
