### ISSUE TITLE
Frontend - Ribbon App Titles & Branding

### ISSUE THREAD

**Issue by kevin-kasunic** [usdigitalresponse/usdr-gost#1588]
### Context
Desire to rebrand/redesign the Grant Identification Tool 
Users of the Grant Finder also want a way to easily access their "My Profile" user account and manage their team(s) no matter what screen they are currently on
This is a ticket for Grant Finder only and assumption is that no changes will impact ARPA users

### Open Questions
- None

### Current State
![Image](https://github.com/usdigitalresponse/usdr-gost/assets/135758360/5731f453-7f1d-4626-9195-711dc6c475ca)
In the Grant Finder Tool, a Quick Menu current exists in the top ribbon, with limited fields available (see below).
Image

### Future State ([design](https://www.figma.com/file/gi975Am6lHBFbjCZeVBzb5/Settings?type=design&node-id=697-18353&mode=design&t=b1u9OLalI1W1AUwl-4))
The Grant Finder will have an improved Quick Menu that can be easily accessed from the top ribbon of the tool. improvements include:
- updating "Grant Identification Tool" name to "Federal Grant Finder"
- updating colors/fonts/styles to match figma file
- updating display of profile on the header to display Profile circle with initials, user's full name, and name of Organization

Future State Mock Figma:
https://www.figma.com/file/gi975Am6lHBFbjCZeVBzb5/Settings?type=design&node-id=697-18353&mode=design&t=b1u9OLalI1W1AUwl-4

**_Federal Grant Finder_**
![Image](https://github.com/usdigitalresponse/usdr-gost/assets/135758360/1159fcc6-314d-4f31-bed8-5aa0e5dcd11b)

**Comment by adele-usdr** [comment]
@ClaireValdivia we have other tickets tracking the profile changes, right? I have a branch now with the toolbar color change and tool name change, but not sure if I should wait on doing anything with the profile.
