### ISSUE TITLE
Add 'Read All' front end functionality for recent activity table

### ISSUE THREAD

**Issue by hadashirt** [usdigitalresponse/usdr-gost#159]

**Comment by mhuang-usdr** [comment]
QA: 

1. The header should be aligned with the icons to match #164.
2. Widen the rightmost date column, so all the "X days ago" fit on a single line. 
3. Any activity that occurred more than 7 days ago should be a date.

Here's the original mock:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/91221265/182222320-711f618d-41b0-4963-8841-cc0a2e1b80b4.png">
