### ISSUE TITLE
[ID] Export information from the ID tool into an excel spreadsheet for maximum compatibility with govt workflows

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#16]
From Ohio

as a stopgap until new features are in, can we export the info to an Excel Sheet and we can track/modify on our own after?

**Comment by mhuang-usdr** [comment]
From OH's latest email: 

> There is not an ability to export to excel, so even if we were using this tool to find the opportunities we will then have to enter them again in excel to do the other tracking this tool does not do for us on how agencies plan to respond to the opportunity.

**Comment by mhuang-usdr** [comment]
A local partner indicated that the ability to export the tables to CSV would be their top priority.

**Comment by Raphomet** [comment]
Put the button here:

![CleanShot 2022-04-11 at 14 02 53@2x](https://user-images.githubusercontent.com/58006/162831728-0934467e-b5c3-4f41-98f7-5fb8a77ca9f6.png)

[The download icon is from Bootstrap Icons.](https://icons.getbootstrap.com/icons/download/)

CC @mhuang-usdr
