### ISSUE TITLE
[ARPA P&E Reporting] A user suggested including the Project ID column throughout the template

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1625]
**Submitted Description:**
Most sheets in the USDR template include the assigned Project ID for individual projects. The only sheet that does not have the Project ID is the Expenditures>50,000. A user suggested that the Project ID column should also be included on the Expenditures>50,000 sheet. 

**(Optional) Uploaded file - click to download:**

**Comment by as1729** [comment]
Input tempalte
> Its not so much that they could re-type the project ID but they would like it to auto-populate
- Either way is fine, it just helps them do their own validation.

Going forward we can make that available but it won't be ready by this quarter.

> Would it be like an existing helper columns?
- Joe to take a peek and figure out what makes sense here.

Just don't want a scenario where project ID gets added and forgotten to be added in the Expenditures < 50000.
