### ISSUE TITLE
[ID] Update the Dashboard page with the feedback from our designer

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#164]
Here are the mocks with feedback she suggested 

https://www.figma.com/file/xI45uK21kK3tASL11GNSoG/USDR-Grants-Tools%3A-GOST-(Rachel's-Copy)?node-id=725%3A9257

**Comment by cavukovic** [comment]
The see all upcoming and see all activity alignment issues are fixed in issue #159 and #157
