### ISSUE TITLE
[Infra] An email address created with capitalized letters cannot log in again

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#166]
This is the same issue as in the ARPA reporter tool:
https://github.com/usdigitalresponse/arpa-reporter/issues/335

We normalise casing during login, but not on account creation
Discussed fix - also normalise case during account creation

We should fix it here so that the ARPA reporter repo doesn't need to fix it.

@ajhyndman fyi

**Comment by as1729** [comment]
@mhuang-usdr and @ajhyndman afaict this issue should be resolved. Please let me know if that is not the case.

You can see my investigation here in this 2 min video:
https://www.loom.com/share/52e8d431110d4d0dbb36970540c9776c

**Comment by mhuang-usdr** [comment]
I just checked in prod and it seems fixed as well. Thanks for investigatin!
