### ISSUE TITLE
Migrate one saved search per user

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#1662]
### Why is this issue important?

Because all saved searches are being changed to be individual, the current agency criteria and keywords will no longer be accessible to users and may disrupt their work.

### Current State

Each agency has one shared search, which will not be the case when we deploy search changes

### Expected State

At time of milestone launch, all existing users should have one saved search - the one that is active on their current account (i.e. with relevant keyword and eligibility criteria). 

Need to take a snapshot of current saved keyword and eligibility criteria for each agency - TBD when we should do this snapshot. This should be used to create a saved search for each user.

This will include non-grantfinder users, but this will be okay because notification settings will apply to individuals

### Implementation Plan

The following functions need to be added...

**Comment by as1729** [comment]
[staging_saved_search_migration.log](https://github.com/usdigitalresponse/usdr-gost/files/12755055/staging_saved_search_migration.log)

ran this in staging confirmed that the saved search matched the previous keywords setup for 50 users

<img width="900" alt="image" src="https://github.com/usdigitalresponse/usdr-gost/assets/6497366/42613a5b-0cfc-48ca-b00b-3c044d87a141">

**Comment by as1729** [comment]
[saved_search_migration_prod.log](https://github.com/usdigitalresponse/usdr-gost/files/12773047/saved_search_migration_prod.log)
<img width="795" alt="image" src="https://github.com/usdigitalresponse/usdr-gost/assets/6497366/1f0b3e21-2db5-416c-8029-106a6a0faae7">
