### ISSUE TITLE
Unification of UX design

### ISSUE THREAD

**Issue by kevin-kasunic** [usdigitalresponse/usdr-gost#1670]
(Scope provided by Joey Yang via Slack)

**Current state:**
- The [USDR design system](https://www.figma.com/file/HWu4iIjcoX2txuN543qzIB/USDR-Design-System?type=design&node-id=101%3A167&t=1Mnjagb3YN6D33iO-1) is in early stages of development. Liz and Caitlin originally created the design system, defined in Figma, based on Bootstrap Figma assets since we’re using Bootstrap 4 / Vue on the GOST frontend.
- The primary areas where the USDR design system differs from Bootstrap is in color and text style definitions.
- The frontend team is planning on migrating the frontend to React in the mid-term (starting no earlier than end of June). We are currently using Bootstrap Vue, which uses Bootstrap 4. There are some components that pull in Bootstrap 5 components.

**Proposed plan to unify USDR DS & GOST frontend:**
- I’d like to start by auditing the frontend codebase, focusing on identifying one-off styles that are defined at a component level and do not come from the Bootstrap library. This would focus on color & text, since those are the primary areas where the USDR system differs from Bootstrap, but I’d also look out for other css styles that are defined in individual components. I’d be using searches [like this](https://github.com/search?q=repo%3Ausdigitalresponse%2Fusdr-gost%20color%3A&type=code) to identify one-off styles that exist in individual components (ex. colors defined by hex code). This will allow us to identify gaps between the USDR library and what engineering has to implement and potentially result in design system improvements that can be merged upstream into the USDR library.
- After that, I’d like to implement the USDR brand color & text styles in the current Vue frontend - this would likely be a frontend .scss stylesheet that defines the USDR colors and styles, including base token definition (e.g. $raw-gray-700: #1E1F20,  etc.) and then semantic token definition, which we define based on our base tokens (ex. .primary-text { color: $raw-gray-700; } ). This stylesheet would be either reusable or easily transferrable to a new React codebase.
- Next, working with the engineering team, I’d like to go through the frontend codebase and replace the styles with USDR system styles. This will allow for a smoother migration path to React and Storybook.

**Comment by ClaireValdivia** [comment]
@caitlinwinner was this issue completed with the work Joey did this summer?

**Comment by caitlinwinner** [comment]
yes completed
