### ISSUE TITLE
Fix activity feed not showing, currency filter errors, remove duplicate styles

### ISSUE THREAD

**Issue by CGowan44** [usdigitalresponse/usdr-gost#169]

**Comment by mhuang-usdr** [comment]
QA: The activity feed should not be scrollable, it should only show max 4 rows. Otherwise looking good!

**Comment by CGowan44** [comment]
@mhuang-usdr Could I open a separate issue for showing only four items and work off of that? I just edited the title of this issue to be more specific as to what the original bug we were trying to fix was (the feed wasn't showing at all) since it was a little vague originally.

**Comment by mhuang-usdr** [comment]
@CGowan44 sure thing!
