### ISSUE TITLE
[ID Tool] Add concept of a closed grant.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#17]
Request from Ohio:

> Don't show a grant if it's been X days and ____ after the close date.

We need more info about the parameters of what grants should get archived - ex. X days and untouched?

**Comment by mhuang-usdr** [comment]
From Alaska - if I finished using reviewing a grant, I need a way to close it out and mark it as "done"

**Comment by mhuang-usdr** [comment]
Alaska - On the main dashboard - I shouldn't be seeing a bunch of grants I that are expired.

**Comment by Raphomet** [comment]
I suspect different users will have different needs — probably better to give them filtering controls instead of applying blanket rules they can't set.

**Comment by mhuang-usdr** [comment]
Next step: ask partner:

Can we define anything as past the closed date as "closed"?

Or is there a difference b/t closed and archived on grants.gov?

**Comment by Raphomet** [comment]
Related to #53 , which should solve this issue for now.

**Comment by mhuang-usdr** [comment]
I'll close this issue as the needs are covered in #53 and #50.
