### ISSUE TITLE
[ARPA P&E Reporting] EC 1.4 needs updated in Treasury upload file

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#1728]
**Submitted Description:**
Project Baseline upload EC 1.4 wording should be updated to:

1.4-Prevention in Congregate Settings (Nursing Homes Prisons/Jails Dense Work Sites Schools Child care facilities etc.)

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212007960331041/5668791581716387345/projectBaselineBulkUploadTemplate.xlsx

**Comment by jcomeau1** [comment]
The dropdown has been updated with the exact wording above (no commas). This has been added to v20230912.
