### ISSUE TITLE
Investigate whether there is an issue with USDR Treasury Export files

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1778]
### Why is this issue important?

In our partner call we heard issues with uploading the treasury export file generated from the ARPA tool.

WI - Ran into treasury issues during upload which necessitated some manual work.
OH - had to copy paste from the USDR export into the treasury's version. It was accepting some of the data, not accepting **current-period expenditures and obligations**.
This is for all project templates
All project templates had an update timestamp of May 17th.
Something on Treasury’s backend seems to have jeopardized the current period information.

### Current State

We are unaware of any issues with our treasury export formatting.

### Expected State

We have reviewed the treasury export files for:
- Current period expenditures
- Current period obligations

Ensure they are of the expected data-type in the actual treasury export requirements.

If they are mal-formatted, please create a ticket to fix the bug.

### Implementation Plan

N/A

**Comment by jcomeau1** [comment]
Although it's not clear if this is in Production, changes have been applied. Closing this issue as it is listed as Done.
