### ISSUE TITLE
/validate endpoint throwing a datadog tracer error

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1781]
### Why is this issue important?

Awaiting a deployment to production and the functionality is not passing QA

### Current State

When a user uploads or validates a workbook, they are receiving a 503 error

`{"error":"tracer.tracer is not a function"}`

### Expected State

When a user uploads or validates a workbook, they will not receive an error

**Comment by as1729** [comment]
https://github.com/usdigitalresponse/usdr-gost/pull/1732/files#r1291753788

**Comment by TylerHendrickson** [comment]
Error trace in Datadog, [here](https://app.datadoghq.com/apm/trace/2180922403606892195?colorBy=service&env=staging&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=1270351095061563992&spanViewType=errors&timeHint=1691785603596.0022) (screenshot below).

The actual issue appears to be a teeny tiny typo – there's a call to `tracer.tracer()` that should be `tracer.trace()`:
https://github.com/usdigitalresponse/usdr-gost/blob/e1710100b1d4b1bb82845fdfd8208f01b0164135/packages/server/src/arpa_reporter/services/persist-upload.js#L233

---

![image](https://github.com/usdigitalresponse/usdr-gost/assets/1851017/3a9a5947-3dbf-476a-b1cc-20b5032a6e05)
