### ISSUE TITLE
[ID] Users would like to add notes/give context about a grant

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#18]
Request from Ohio for:

- ability to put in and see the total award amount if granted
- ability to put in a reason for rejection if not granted
- ability to see this information after the fact

**Comment by mhuang-usdr** [comment]
Request from BB to be able to have different people "comment" on a grant, so everyone can see the context and history on it

**Comment by mhuang-usdr** [comment]
Also from the partner:

- AS AN Agency User I want to communicate the date I applied for a grant to the Grants Office and other stakeholders

**Comment by mhuang-usdr** [comment]
From #21:

Currently the Grants tab show a Status field, which represents the Grants.gov status. This is fine. However, it would be helpful if a partner could indicate where a grant is within their own process; we can call this a grant's State. Potential State values could be things like: Assigned, Answered, Awarded, Rejected.

Acceptance Criteria

- See the State field of a grant that indicates where the agency is within their own process
- Filter on State field values (Assigned, Answered, Awarded, Rejected)

From Jessica Martin (OH)

**Comment by mhuang-usdr** [comment]
An initial draft wireframe, I think it needs to be expanded from a notes field to a comment thread system.

https://www.figma.com/file/jHvmE56bZIQWozGreXDOit/Grants-ID-Tool?node-id=458%3A2651

**Comment by mhuang-usdr** [comment]
Upon conversation with Design team - let's just roll with this for MVP - basic text boxes, no need to track any type of edit history. We can observe what users do with the text box and design further in the future.


![Image](https://user-images.githubusercontent.com/91221265/219126203-09f636d2-d597-4232-bc39-380861d9aba9.png)

**Comment by ClaireValdivia** [comment]
out of date, collab cohort has new recommendations for this
