### ISSUE TITLE
Add ability to view treasury-export-file and audit-report for closed reporting periods

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1801]
## Current State
When a reporting period is closed partners do not have access to the audit report or the treasury export file.

## Ideal State
A partner is able to navigate to any prior quarter and retrieve the last audit-report and treasury-export that was generated prior to the reporting period being closed.

## Open questions
- Is it OK to show just the last audit-report that was generated? Or do we want to generate a new audit report when the button is pressed for a closed reporting period? This may cause inconsistencies.
  - @jcomeau1  - whatever was last generated/produced is more than acceptable. This is literally what went to treasury so from an audit perspective there's no difference. Ensures that subsequent changes do not impact the actual data.

**Comment by as1729** [comment]
Same as #1133 please review the comments in the other ticket as well and incorporate them.

**Comment by tzinckgraf** [comment]
@as1729 went through this code over the weekend. Still working through some test cases, but should have this done this week.

**Comment by tzinckgraf** [comment]
@jcomeau1 / @as1729 please confirm the below is what is expected:

![image](https://github.com/usdigitalresponse/usdr-gost/assets/842982/f6c189fb-26fc-42cd-b532-6ec4fa0505b1)

A few questions before completing this ticket.
1. The original ticket mentions saving a copy of the report once the reporting period is closed. Do we still want to do that? We could add columns to the `reporting_periods` table for reach report, or we can store it as a separate table, or use some sort of naming scheme.
2. Do we want to change the filename to indicate this is a report for an older reporting period? Currently, the name format is audit-report-<date>-<uuid>.xlsx. As a few options, we can keep this as the default for current reporting period, and add something like quarterly-x to historic reports. Thoughts?

**Comment by tzinckgraf** [comment]
Changed this a bit so that only the download buttons show on the closed reporting periods. This also means that for the non-admins, the closed reporting period page looks identical.

Non-Admin
![image](https://github.com/usdigitalresponse/usdr-gost/assets/842982/97d56ba1-ad12-4402-ad1e-dec97a9a6f16)

Admin
![image](https://github.com/usdigitalresponse/usdr-gost/assets/842982/b766879b-1e3f-429b-81c4-f0c39196f1f7)

**Comment by as1729** [comment]
@as1729 to get a review on the PR.

**Comment by as1729** [comment]
Next steps:

From partners answer the following question:
- What should happen for periods prior to the current 2024-Q2 reporting period?
  - Is it sufficient to re-generate the report with old upload files? Or should we remove this functionality entirely?
- What should happen moving forward beginning the 2024-Q3 reporting period?  
  - Is it OK to save these audit report and treasury reports moving forward? Is it sufficient to save the last-generated file or is there a specific file we need to save?

For Engineering:
- Implications of storing these reports long-term
- What should happen to the current feature as it is?
  - Should we feature flag it ahead of the next release?
    - If its simple enough then sure.
  - Should we rollback just the front-end parts?
    - Since the backend now has added flexibility the functionality is hidden for the user.
