### ISSUE TITLE
[Issue]: Audit Report Enhancements

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#1894]
### Why is this issue important?

The partners have provided feedback on the Audit Report to make it more useful.

### Current State

There are two basic types of changes:

1. The order of the fields (columns) - currently oriented by Period then fields, but need Field then Periods
2. Certain fields on the Audit Report are pulling from the wrong source - pulling from the project sheet instead of the Awards sheets

### Expected State

<html>
<body>
<ul type="disc" style="margin-bottom: 0in; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpFirst" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Project Summaries tab looks correct.<u></u><u></u></span></li><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Project Summaries V2 updates:</span><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;"><u></u><u></u></span><ul type="circle" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Project Data<u></u><u></u></span><ul type="square" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Add Project Name<u></u><u></u></span></li><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Always pull from most recent, validated file: Project ID, Name, Description, Expenditure Categories<u></u><u></u></span></li></ul></li><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Chronological order (L to R, starting w/ the oldest period)<span> </span><i>this looks to be the case except for States w/ 12/31/2021 reporting</i><u></u><u></u></span></li><li class="m_922795016269247802MsoListParagraphCxSpLast" style="margin: 0in 0in 8pt; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Re-organization to be by “type”, then by date. Example of the beginning below, order of amount type is indicated by next bullet!<u></u><u></u></span></li></ul></li></ul>

12-31-2021Total CumulativeObligations | 03-31-2022Total CumulativeObligations | 06-30-2022Total CumulativeObligations | 09-30-2022Total CumulativeObligations | 12-31-2022Total CumulativeObligations | 01-31-2023Total CumulativeObligations | 03-31-2023Total CumulativeObligations | 06-30-2023Total CumulativeObligations | 12-31-2021Total CumulativeExpenditures | 03-31-2022Total CumulativeExpenditures | 06-30-2022Total CumulativeExpenditures | 09-30-2022Total CumulativeExpenditures
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

<p class="m_922795016269247802MsoListParagraphCxSpFirst" style="margin: 0in 0in 0in 1in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;"><u></u> <u></u></span></p><ul type="disc" style="margin-bottom: 0in; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0in;"><ul type="circle" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpLast" style="margin: 0in 0in 8pt; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Here is where the specific cells should be pulling from for each Project ID:</span></li></ul></ul>
</body>
</html>

<html>
<body>
<br class="Apple-interchange-newline">

Total CumulativeObligations | Total CumulativeExpenditures | Current Period Obligations | Current Period Expenditures | Awards > 50000 SubAward Amount (Obligation) | Awards > 50000 Current Expenditure Amount | Aggregate Current Quarter Obligation | Aggregate Current Quarter Expenditure/Payments
-- | -- | -- | -- | -- | -- | -- | --
EC TabColumn G | EC TabColumn H | EC TabColumn I | EC TabColumn J | Awards > 50000 tabColumn K (total all related to the Project ID) | Expenditures > 50000Column G (total all related to the Project ID) | Aggregate Awards < 50000Column E (total all related to the Project ID) | Aggregate Awards < 50000Column F (total all related to the Project ID)

<p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: Arial, sans-serif;"><u></u> </span></p>
</body>
</html>

### Implementation Plan

The following functions need to be added...

**Comment by tzinckgraf** [comment]
Hey @jcomeau1 , I'm seeing the following columns for Project Summary V2 with a date attached to the header:
Total Aggregate Expenditures
Total Aggregate Obligations
Total Expenditures for Awards Greater or Equal to $50k
Total Obligations for Awards Greater or Equal to $50k

The non-dated columns are the following:
Project ID
Project Description
Project Expenditure Category Group
Project Expenditure Category
Capital Expenditure Amount

I'm also seeing dates in the format 2023-01-21.

Can you confirm that it seems correct? If so, which ordering do you want?

**Comment by jcomeau1** [comment]
The order should be:
Project ID
Project Description
Project Expenditure Category Group
Project Expenditure Category
Capital Expenditure Amount
Total Aggregate Obligations (for each period)
Total Aggregate Expenditures (for each period)
Total Obligations for Awards Greater or Equal to $50k (for each period)
Total Expenditures for Awards Greater or Equal to $50k (for each period)

**Comment by ClaireValdivia** [comment]
@jcomeau1 going through ticket clean-up, wondering - can this one be closed?

**Comment by jcomeau1** [comment]
@ClaireValdivia, no, Tom is still working on it. Additionally, I'll split out part of this request into a separate one.

**Comment by jcomeau1** [comment]
Update the description to only include what we are currently implementing. @tzinckgraf any update on when this can be tested in Staging?
