### ISSUE TITLE
My Profile Page - Avatar Color

### ISSUE THREAD

**Issue by kevin-kasunic** [usdigitalresponse/usdr-gost#1912]
Handle random assignment of avatar color. Text should be either black or white for optimal contrast. Color values (background and text colors) should be stored to the database as part of users table. Do a database migration to add the field for current users.

**Comment by ClaireValdivia** [comment]
Tested in staging and the color picker on profile looks great. However, confirming that right now it seems like all users are defaulted to the brown color. @caitlinwinner does a new issue need to be created for random color generation?

**Comment by ClaireValdivia** [comment]
disregard earlier comment - confirmed in staging that colors are randomly assigning to new and existing users!
