### ISSUE TITLE
[Performance Reporter] Add the URL redirect into the login email 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#195]
Right now, the login email will take you to the Grants ID tool by default. But if they came to the authentication page via the Performance Reporter, they should get redirected back to [grants.usdigitalresponse.org/#/](https://grants.usdigitalresponse.org/#/arpa-annual-performance-reporter)

**Comment by ThienBNguyen** [comment]
Hi, I would like to work in this issue.

**Comment by mhuang-usdr** [comment]
Hi @ThienBNguyen! Thanks for reaching out with your interest. This repository is part of [U.S. Digital Response](https://www.usdigitalresponse.org/), a nonprofit that organizes pro-bono technologists to help with critical government needs.

If you'd like to volunteer, please fill out our [volunteer handraiser form](https://www.usdigitalresponse.org/volunteer), so we can put you through the onboarding process. Thank you!

**Comment by ThienBNguyen** [comment]
Thank you for the opportunity with US Digital Response as a volunteer. I can not join the organization.

**Comment by mattbroussard** [comment]
As noted in my comment on #288, I'm taking this over since haven't heard from @romangurovich and I need this functionality for ARPA integration project.
