### ISSUE TITLE
[ID Tool] Adding a user that already exists should show an error.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#199]
Current behavior:
- Add a user that already exists
- Click Ok
- Nothing happens - the modal doesn't close, there's no reaction.

Expected behavior:
- Add a user that already exists
- Click Ok
- There's a pop-up, or some sort of error message that says "email@email.com already exists."

**Comment by slants3** [comment]
I can take this one

**Comment by slants3** [comment]
@mhuang-usdr this has been added

**Comment by mhuang-usdr** [comment]
Looks great! Thanks!
