### ISSUE TITLE
[ID Tool] When creating a user after switching views, the dropdown menu for adding the user to an agency doesn't update until manually refreshing

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#200]

**Comment by chrisxkeith** [comment]
@mhuang-usdr : Do you have two browser tabs open, one showing the Users tab and the other showing the Agencies tab?

**Comment by mhuang-usdr** [comment]
@chrisxkeith I just reinvestigated this and can't repro it. I'll close it for now, thanks for taking a look!
