### ISSUE TITLE
Results Table Horizontal Responsiveness Updates

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2065]
### Why is this issue important?
on smaller screens, grants table text overlaps and is difficult to read

### Current State
Horizontal Fit - when the screen size is small, the text in the table overlaps

![Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/dcfcddad-65e0-40ae-a18b-32c1e9464c5a)

### Expected State
Fix horizontal resizing so that the text does not overflow in to the next cell.

### Implementation Plan
tbd

**Comment by ClaireValdivia** [comment]
@caitlinwinner is this ticket ready for an eng volunteer to look into and propose an approach?

**Comment by caitlinwinner** [comment]
@ClaireValdivia I think we should scope to two tickets. 1/fix horizontal resizing so that the text is clipped rather than overflowing in to the next cell. 2/ (less urgent) look into automatically fitting the vertical height to the screen height rather than using a fixed width.

**Comment by adele-usdr** [comment]
Instead of clipping the text in the cells, should we have a minimum width of the table, and then allow the page to scroll horizontally, if the table is too big for the viewport?

**Comment by adele-usdr** [comment]
Maybe a better question is - how is the design supposed to work in a narrow mobile layout?

**Comment by caitlinwinner** [comment]
the new https://grants.gov/search-grants does a pretty good job with this, take a look @adele-usdr

**Comment by caitlinwinner** [comment]
yes! that makes sense to me

**Comment by adele-usdr** [comment]
Looks like the stacked layout properties don't work well combined with the sticky header.  The sticky header seems more important, so I'll leave the stacked change for another time.

**Comment by ClaireValdivia** [comment]
seeing this in staging but not in prod so moving back to staging status for now!
