### ISSUE TITLE
Audit Report Enhancements

### ISSUE THREAD

**Issue by jcomeau1** [usdigitalresponse/usdr-gost#2105]
### Why is this issue important?

Additional enhancement requests by the partners.

### Current State

To reduce the amount of copy & pasting and calculations each partner needs to do.

### Expected State

<html>
<body>
<ul type="disc" style="margin-bottom: 0in; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0in;"><ul type="circle" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Re-sizing columns may be difficult (keep testing)<u></u><u></u></span></li><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Future audit report tabs:</span><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;"><u></u><u></u></span><ul type="square" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpMiddle" style="margin: 0in; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">KPI’s by project ID (still working on compiling columns)<u></u><u></u></span></li><li class="m_922795016269247802MsoListParagraphCxSpLast" style="margin: 0in 0in 8pt; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Data specific<span> </span><i>by Subaward ID</i>, example this would be listed where Subaward ID is the key. Example:<u></u><u></u></span></li></ul></li></ul></ul>

  | 12-31-2021 Awards > 50000 SubAward Amount (Obligation) | 01-31-2022 Awards > 50000 SubAward Amount (Obligation) | 03-31-2022 Awards > 50000 SubAward Amount (Obligation) | 06-30-2022 Awards > 50000 SubAward Amount (Obligation) | 12-31-2021 Awards > 50000 Current Expenditure Amount | 01-31-2022 Awards > 50000 Current Expenditure Amount | 03-31-2022 Awards > 50000 Current Expenditure Amount | 06-30-2022 Awards > 50000 Current Expenditure Amount
-- | -- | -- | -- | -- | -- | -- | -- | --
Subaward ID | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID)

<br class="Apple-interchange-newline">
</body>
</html>
<html>
<body>
<ul type="disc" style="margin-bottom: 0in; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0in;"><ul type="circle" style="margin-bottom: 0in; margin-top: 0in;"><ul type="square" style="margin-bottom: 0in; margin-top: 0in;"><li class="m_922795016269247802MsoListParagraphCxSpLast" style="margin: 0in 0in 8pt; line-height: 14px; font-size: 10pt; font-family: Calibri, sans-serif;"><span style="font-size: 11pt; line-height: 15.4px; font-family: Arial, sans-serif;">Aggregate data specific by Project ID<i><span> </span>and Subaward Type</i>, example this would be listed where Subaward ID is the key, Example:<u></u><u></u></span></li></ul></ul></ul>

Project ID | Aggregate Subaward Type | 12-31-2021 Aggregate Current Quarter Obligation | 01-31-2022 Aggregate Current Quarter Obligation | 03-31-2022 Aggregate Current Quarter Obligation | 12-31-2021 Aggregate Current Quarter Expenditure/Payments | 01-31-2022 Aggregate Current Quarter Expenditure/Payments | 03-31-2022 Aggregate Current Quarter Expenditure/Payments
-- | -- | -- | -- | -- | -- | -- | --
Aggregate Awards < 50000Column C (Project ID could be listed multiple times if there are more than one type reported) | Aggregate Awards < 50000Column D (one line per Type – see drop down) | Aggregate Awards < 50000Column E (total related to Type in Column D) | Aggregate Awards < 50000Column E (total related to Type in Column D) | Aggregate Awards < 50000Column E (total related to Type in Column D) | Aggregate Awards < 50000Column F (total related to Type in Column D) | Aggregate Awards < 50000Column F (total related to Type in Column D) | Aggregate Awards < 50000Column F (total related to Type in Column D)

<p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: Arial, sans-serif;"><u></u> <u></u></span></p><p class="MsoNormal" style="margin: 0px; color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="font-family: Arial, sans-serif;"><u></u> </span></p>
</body>
</html>

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
relevant slack thread which includes mock-ups of audit report template and audit report file itself https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1705348545305769

**Comment by ClaireValdivia** [comment]
@jcomeau1 is it correct that after PR #2399 is pushed to prod, that the following items on this issue are still outstanding: 
Re-sizing columns 
Future audit report tabs:
- KPI’s by project ID (still working on compiling columns)
- Data specific by Subaward ID, example this would be listed where Subaward ID is the key.

**Comment by jcomeau1** [comment]
@ClaireValdivia, yes, that's correct.
