### ISSUE TITLE
Results table vertical height

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2129]
### Why is this issue important?

Fixed height of grants results table makes it unclear how many grant are on the page

### Current State

On My Grants and Browse Grants, the table seems to be a set height, with scrolling happening within the table and not when the page is scrolling up and down. 

### Expected State

look into automatically fitting the vertical height to the screen height rather than using a fixed width.

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@caitlinwinner per request in other ticket, created this one - can you review and add if additional details are needed before this goes to Ready?

**Comment by adele-usdr** [comment]
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/c9d3744e-78be-4859-ab1d-b5dca73d93d6

@caitlinwinner is this what you were going for? This makes the table height no longer fixed and scrollable, so the contents scroll with the page. The downside is that you can end up in a state where you can't see the headers. I'm still thinking about whether there's some other solution that keeps the sticky table header, but I think that will require that you scroll the table itself.

**Comment by adele-usdr** [comment]
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/9ee51a50-1918-4c5e-aac7-cd4684601dd7

@caitlinwinner how does this look to you? I played with a few different layouts, but I think this is a good short term option. Maybe eventually, if we move away from pagination, we would do something a little different - like no scrolling on the main page at all.

**Comment by caitlinwinner** [comment]
I agree, this is an improvement! Thank you!

**Comment by ClaireValdivia** [comment]
saw this marked as completed but not seeing this one in staging or prod. @adele-usdr was the related PR pushed to staging?

**Comment by adele-usdr** [comment]
It should be there:

https://github.com/usdigitalresponse/usdr-gost/commit/5ed5879a040f0938c3ef443281186635c0d20320

**Comment by ClaireValdivia** [comment]
@caitlinwinner are you seeing this in staging or prod? I'm not sure if I'm looking for the wrong thing...

**Comment by caitlinwinner** [comment]
No I can't see it either @ClaireValdivia @adele-usdr. Logged out and logged back in, cleared cache etc

**Comment by as1729** [comment]
@caitlinwinner and @ClaireValdivia  this ticket is only merged to Staging not yet in Production. Not sure if that changes things here.

**Comment by caitlinwinner** [comment]
i was looking at staging

**Comment by adele-usdr** [comment]
I still see what I posted above on _staging, but perhaps with different data sets there is different behavior.  Will try to sync up w/ @caitlinwinner or @ClaireValdivia to better understand what they're seeing.

**Comment by ClaireValdivia** [comment]
staging now is looking different from prod for me now, but I'm not 100% clear on the acceptance criteria for this one - @caitlinwinner can you please take a look and confirm if staging is behaving as we expect?

**Comment by ClaireValdivia** [comment]
confirming that this works in staging as it does in the video demo above, but just a ping for @caitlinwinner in case you want to create a new ticket to remove the double scrolling from pages with the table (as depending on screen size, this solution has the same challenges as the current display on prod)

**Comment by adele-usdr** [comment]
Here's an alternate version that may help in the discussion. No scrollable table. The main downside is no sticky header, but maybe that's ok.


https://github.com/usdigitalresponse/usdr-gost/assets/146878468/abada2cc-e147-4afe-bcea-6545f5f05803

**Comment by caitlinwinner** [comment]
this is wayyy better. what do you think @ClaireValdivia ?
