### ISSUE TITLE
add top and bottom borders to table

### ISSUE THREAD

**Issue by caitlinwinner** [usdigitalresponse/usdr-gost#2213]
### Why is this issue important?

This issue stems from a conversation in Slack, I noticed the table borders disappear on scroll sometimes. 

### Current State

<img width="992" alt="Screenshot 2023-11-13 at 3 14 44 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/1101194/211c083f-350c-4d38-ae8c-cff91b3c4182">

### Expected State

All 4 sides of table have a light gray 1px border

**Comment by adele-usdr** [comment]
Uploading Screen Recording 2023-11-14 at 6.13.05 PM.mov…

@caitlinwinner how does this look to you? There is some bugginess around the sticky header, so this seemed like the cleanest solution, but does mean that sometimes you get a thicker border when two borders overlap.

**Comment by adele-usdr** [comment]
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/4e75500d-aeff-4c25-a163-d4da863670d9

had some trouble uploading...here's the screen recording!

**Comment by caitlinwinner** [comment]
Did all the borders get thicker?

**Comment by adele-usdr** [comment]
the top and bottom borders are doubling up making them all look thicker.  I'm going to try another technique....

**Comment by adele-usdr** [comment]
@caitlinwinner how is this option?  The bottom border of the header row still gets collapsed/hidden, and there's still something a little weird going on behind the sticky header.


https://github.com/usdigitalresponse/usdr-gost/assets/146878468/df57274c-7639-4833-831b-295bbdc0278b

**Comment by adele-usdr** [comment]
This should get addressed with #2269

**Comment by adele-usdr** [comment]
This can be closed now.
