### ISSUE TITLE
[Data] Google Analytics update: extend to all pages

### ISSUE THREAD

**Issue by jsandlund** [usdigitalresponse/usdr-gost#2223]
**User Story**
As a USDR team member, I’d like to view basic page view analytics in Google Analytics so that I can better understand user engagement and behavior. 

**Background**
* The Google Analytics 4 ("GA4") script currently only fires on the login page. We'd like to extend GA4 to all pages so that we can better understand user engagement and behavior. 
* This ticket is part of the Product Analytics Platform v1 initiative: https://www.notion.so/usdr/Grant-Finder-Product-Analytics-Platform-v1-69fe295f1f7442e586aef55fbb1d824b?pvs=4

**Requirements**
1. GA4 page_view events fire on state changes that generate a unique URL. 
~~2. the following [custom event parameters](https://developers.google.com/analytics/devguides/collection/ga4/event-parameters?client_type=gtag#set-up-every-event) are added to every event
  2.1 team_name (e.g. "USDR") -- this is a.k.a "agency_name"~~

**Examples** 
Viewing each of the following pages triggers a page_view event :  
- https://grants.usdigitalresponse.org/#/my-grants https://grants.usdigitalresponse.org/#/grants  
- https://grants.usdigitalresponse.org/#/dashboard  

**Out of Scope**
On-page actions such as clicking “New Search” does not trigger a page_view event because a new URL is not generated.

**Comment by jsandlund** [comment]
@TylerHendrickson JFYI. Can you have a look at this when you get a chance and lmk if it LGTY?

**Comment by sanason** [comment]
Could I get access to whatever Google Analytics account we have been using?

**Comment by sanason** [comment]
@TylerHendrickson I take it that you are the one to tag about this request ^^.

**Comment by sanason** [comment]
I split the custom event parameter part of the requirements into a separate ticket. #2380

**Comment by ClaireValdivia** [comment]
PR #2323 is in prod, but pr #2342 is not; my understanding is that both PRs need to be deployed for this to be completed, but lmk if that's incorrect @sanason @jsandlund

**Comment by jsandlund** [comment]
Sprint planning notes: Scheduled to be released ~ Thurs 1/4
