### ISSUE TITLE
Avatar creation for header

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2232]
### Why is this issue important?

similar to the profile avatar created for the profile page in #1910  using BootstrapVue [Avatar](https://bootstrap-vue.org/docs/components/avatar) component, this issue is to create the avatar that will display on the grant finder header.

### Current State

User's email and team display on right side of grant finder header

### Expected State

Figma file: https://www.figma.com/file/gi975Am6lHBFbjCZeVBzb5/Settings?type=design&node-id=697-18353&mode=design&t=vb6D9DFSWAUORYDq-4

Profile avatar should display on right side of header
Avatar circle should include Initials, and to the right, the user's name and Team name should display 

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@thelmaboamah we realized that the avatar creation for the header was not explicitly named in any of the other profile issues so have created this one. was just curious if you had any notes for implementation details of this issue based on your work on #1910

**Comment by thelmaboamah** [comment]
@ClaireValdivia it was among the items in the ribbon ticket #1588 but looks like it was missed. An additional ticket sounds good.
