### ISSUE TITLE
All notification should be default to "on" for new users

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2242]
### Why is this issue important?

expected behavior is that new users have notifications on 

### Current State

none of the notifications are default to on

### Expected State

- The first time I log in as a new user, when I go to "Settings" (or My Profile after implemented), all Notifications should be toggled to the "on" position (Grant Assignment, New Grant Digest, and after profile is implemented - Occasional Updates)

### Implementation Plan

The following functions need to be added...

**Comment by thelmaboamah** [comment]
Changing the constant from unsubscribed to subscribed [here](https://github.com/usdigitalresponse/usdr-gost/blob/d03283c04e788d69c77169971ae8044cb1b5d49a/packages/server/src/db/index.js#L77) should resolve this.
