### ISSUE TITLE
Notification email link updates

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2268]
### Why is this issue important?
Need to update digests and assignment notifications so managing notification preferences will direct to the new profile page.

### Current State
Footer on both digest and assignment emails has a link for "change notification preferences" that directs to grant finder Profile Settings Modal

### Expected State

- [ ] On Grant Digest email, the footer link that says "Change notification preferences" should link to the /my-profile page
- [ ] On the Assignment notifications email, the footer link that says "Change notification preferences" should link to the /my-profile page

TBD - can email notification updates be feature flagged?

### Implementation Plan

The following functions need to be added...

**Comment by sanason** [comment]
@ClaireValdivia This change _is_ behind a feature flag, which is on for staging and off for production. I had to add a new server-side flag, which is called `api_enable_my_profile` in Terraform.
