### ISSUE TITLE
Deal with dependabot alerts

### ISSUE THREAD

**Issue by cmroberts** [usdigitalresponse/usdr-gost#23]
Maintenance makes the world go 'round

**Comment by starscouter1973** [comment]
hey guy,, allow me some question please im a newbie in every case . just scripting a bit depends on passion.   Deal with dependabot alert  is the thing that mekes me nervous. 
just looking for a point i can go to . 
im a little afraid that this warning means more then i hope..

can you give me an advice to which point i have to send my issues--

greets from cologne

**Comment by cmroberts** [comment]
Relevant pieces captured in #45
