### ISSUE TITLE
Update header logo size to match size of Profile icon

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2306]
### Why is this issue important?

@caitlinwinner noticed the header logo looks too small now that we have a new profile icon

### Current State

Logo is too small

### Expected State

Logo height should match profile icon

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@adele-usdr can you confirm this was merged to staging? right now the sizing of the logo in staging looks the same as production

**Comment by adele-usdr** [comment]
@ClaireValdivia it's there now! I think it was stuck in the deploy-to-staging workflow.
