### ISSUE TITLE
[Spike]: Off the shelf search tools

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2308]
### Why is this issue important?

Improvements to search fields is currently time intensive for requirements specifications and execution, so we are interested in researching off the shelf tools like Algolia that we can leverage to better implement search features that are well validated to provide a strong experience, and to make execution more straightforward.

### Current State

Our current implementation of search does not make use of any off the shelf tools. We want to research offerings like Algolia to see if they will make an impact on ability to ship high quality improvements to our search from a user experience and engineering perspective. Example of high priority search improvements on the horizon include:
#2201 
#2063 
#2110 
#2283

### Expected State

Assessment of Algolia and other search tools and summary for each, including:
- Cost
- Expected impact on ease of improving search from engineering perspective
- out of the box functionality for full text search
- recommended path forward 

Expectation is that we want to first implement a new search tool with functional parity (i.e. no changes to how search works currently), then address outstanding issues to improve search (i.e. bill field, department field, full text search of documents, etc)

### Solutions worth exploring

- [Algolia](https://www.algolia.com/)
- [Typsense](https://typesense.org/) (note: OSS; can also be self-hosted)

**Comment by coderintherye** [comment]
@TylerHendrickson I added you to the index I created a little while back using one of the grants.gov data dumps https://dashboard.algolia.com/apps/X4V5YU1HL4/dashboard

Pricing-wise https://www.algolia.com/pricing/
"Build" is free and might fit current needs, "Grow" is also relatively low-cost. 
The more full-featured "Premium" and above plans though tend to be more enterprise pricing. If helpful I could reach out to a prior contact from there for any insights.

**Comment by ClaireValdivia** [comment]
1/9 discussion - after current work, Shelley will take a look

**Comment by sanason** [comment]
> @TylerHendrickson I added you to the index I created a little while back using one of the grants.gov data dumps https://dashboard.algolia.com/apps/X4V5YU1HL4/dashboard

Hi, @coderintherye . Could you add me to your index too?

**Comment by sanason** [comment]
Here is my write-up - https://www.notion.so/usdr/Off-the-shelf-Search-Tools-be02cb5306734ddabcaad03bb9816422?pvs=4
