### ISSUE TITLE
[ID] Enforce data rules

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#231]
- [x] There should never be Users or Agencies with Null tenant IDs
- [x] `main_agency_id` for an Agency should always equal the `main_agency_id` of the tenant that the Agency belongs to. The decision was made to store `main_agency_id` in both places for sake speed of accessing the information for future features that require knowledge of the agency.

**Comment by mhuang-usdr** [comment]
@bspates fyi

**Comment by bspates** [comment]
@mhuang-usdr Gonne pick this one up, as it makes the next multi-tenancy stuff easier.

**Comment by bspates** [comment]
Since @chrisxkeith ran the backfill on the prod this is complete.
