### ISSUE TITLE
[GDP] Create new feature flag for moving Grant Details from a modal to an independent page

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2337]
### Why is this issue important?

First step in the new Grant Details work

### Current State

No intended behavior changes

### Expected State

No intended behavior changes

**Comment by ClaireValdivia** [comment]
@adele-usdr could you please add the name of the feature flag for grant details here: https://www.notion.so/usdr/Feature-flags-63d7131522d0446288e081b4b0493b6a

CC @jsandlund

**Comment by adele-usdr** [comment]
> @adele-usdr could you please add the name of the feature flag for grant details here: https://www.notion.so/usdr/Feature-flags-63d7131522d0446288e081b4b0493b6a
> 
> CC @jsandlund

done!

**Comment by ClaireValdivia** [comment]
confirmed that feature flag is working in staging and prod, closing issue
