### ISSUE TITLE
Add "Result" Status codes - "Applied," "Awarded", "Rejected"

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#235]

**Comment by mhuang-usdr** [comment]
Also requested by a partner today

**Comment by slants3** [comment]
Hey @mhuang-usdr, to clarify - 

We have existing `Interested` and `Rejections` categories - 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/38918961/195207221-1e990cfb-feb0-454f-9952-36004abda9f5.png">

Am I understanding correctly that we want a third new category called `Result` with "Applied," "Awarded", "Rejected"?

FYI it looks like the codebase expects a binary status code - either a positive (interested) or a negative (not interested)

**Comment by mhuang-usdr** [comment]
Yes, we'll want a third category. Seems like we'll have to move from a binary status code to an enum of some sort.

`Result` is not the same as `Assigned`, it should be a whole separate thing. 

`Assigned` is an action that someone else took to send you the grant. `Interested,` `Rejected`, and `Result` are all status codes that the user took action on for their own agency.

**Comment by mhuang-usdr** [comment]
Hm, I think we should also rename `Rejected` to `Not Interested` for clarity's sake.

**Comment by slants3** [comment]
@mhuang-usdr re: renaming - I have a hunch `Rejected` might be better than not interested despite the potentially confusing naming aspect purely because the term `Interested` is fairly overloaded in the codebase and beyond

**Comment by mhuang-usdr** [comment]
There will likely need to be a renaming effort both in the UI as well as the codebase as we elevate "Interested" codes to "status" codes, a la https://github.com/usdigitalresponse/usdr-gost/issues/438

I'll close this issue for now and create a separate one on that effort
