### ISSUE TITLE
These status codes should show up in the grants modal alongside the list of "Interested" and "Rejected" Statuses

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#236]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/91221265/194666596-a56bbf47-4e8b-42e5-8f04-e4950ef0141d.png">

**Comment by slants3** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/38918961/197246316-7ff270e3-a104-4680-a27d-578818a3d763.png">

Hey @mhuang-usdr , here's what the new dropdown looks like with the `Result` options added

**Comment by mhuang-usdr** [comment]
@slants3 thanks! I dropped my comments in the PR

**Comment by mhuang-usdr** [comment]
@slants3 can this be closed?

**Comment by slants3** [comment]
Yup! Closing
