### ISSUE TITLE
[GDP] Load current GrantDetail modal as a new page, with back button support

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2368]
### Why is this issue important?

Sub-task of Grant Detail Page sprint.

### Current State

GrantDetail currently loads as a Modal through GrantDetailLegacy.vue

### Expected State

When the newGrantsDetailPageEnabled feature flag is in use, all the actions that currently load GrantDetalLegacy.vue should instead load GrantDetail.vue as a new page. The back button should preserve history and take you back to the previous page.

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
closing this out as the modal itself with a back button was created. will create a new issue to address remaining acceptance criteria for "back to results" functionality
