### ISSUE TITLE
[GDP] Move existing Grant Details content to match new placement

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2370]
### Why is this issue important?

Sub-task of Grant Detail Page sprint.

### Current State

Content placement matches what is in the old modal in GrantDetailsLegacy.vue 

### Expected State

Change layout of existing content in GrantDetails.vue to match the new placement in the [design](https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?node-id=1480%3A3099&mode=dev)

**Comment by mounalawrence** [comment]
Design file for Grant Details, to be reviewed on Mon 1/15:

https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=1110-2419&mode=design

**Comment by adele-usdr** [comment]
I think this is now covered by other issues
