### ISSUE TITLE
[GDP] Add any new content not in the existing Grant Details modal to the new page

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2371]
### Why is this issue important?

Sub-task of Grant Detail Page sprint.

### Current State

New content defined in the design is not yet present in GrantDetails.vue

### Expected State

Add any new content defined in the [design](https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=722-6816&mode=design&t=c4MOzrnOBIbw9uve-0), not in the existing GrantDetailsLegacy modal to the new GrantDetails.vue

**Comment by mounalawrence** [comment]
Design file for Grant Details, to be reviewed on Mon 1/15:

https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=1110-2419&mode=design
