### ISSUE TITLE
[GDP] Turn newGrantsDetailPageEnabled feature flag on in Development 

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2372]
### Why is this issue important?

Sub-task of Grant Detail Page sprint.

### Current State

Feature flag is not on anywhere

### Expected State

Feature flag should be on for development

### Implementation Plan

Make sure to look at any changes to GrantDetailsLegacy.vue made since we created GrantDetails.vue, and sync any needed changes as part of this PR.

**Comment by ClaireValdivia** [comment]
@adele-usdr @TylerHendrickson closing this one as I believe this is configured on local environments. let me know if there's something outstanding though and we can reopen!
