### ISSUE TITLE
[GDP] Add instrumentation to GrantDetails.vue on page load and to GrantDetailsLegacy.vue when the Modal is loaded

### ISSUE THREAD

**Issue by adele-usdr** [usdigitalresponse/usdr-gost#2375]
### Why is this issue important?

Sub-task of Grant Detail Page sprint.

### Current State

No instrumentation exists yet to log when the new Grant Details page is loaded

### Expected State

When a Grant Details page is loaded, we should have instrumentation to log the page load.  We should be able to compare this data with data on when the old Modal is loaded.

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@adele-usdr wanted to check in if this one was completed or if it is still needed? thanks!

**Comment by adele-usdr** [comment]
I think we still need to do this, unless page load events are captured outside of these files.  @TylerHendrickson can you confirm?

**Comment by ClaireValdivia** [comment]
2/6 convo - think this is not needed; ty will confirm if this is already on modal and if so, close out
