### ISSUE TITLE
[ID] The Recent Activities Feed should also include "Assigned" grants.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#239]
When an agency is assigned a grant, that should also be added to the Recent Activities feed. 

_The text should be:_

Historical Records Advisory Board was **assigned** FY21 Supplemental for the Northeast Corridor... 

_For the color of the word_ "assigned" - let's keep it black but bolded.

_For the icon, let's use something like this:_
https://thenounproject.com/icon/assign-4574720/
![image](https://user-images.githubusercontent.com/91221265/183539272-72a2d461-9c36-4b11-b592-8ff2831a5ef8.png)

**Comment by mhuang-usdr** [comment]
QA: **was** should not be bolded. Only **assigned** should be bolded.

@cavukovic

**Comment by cavukovic** [comment]
@mhuang-usdr had to make a new pull request for it, added you as a reviewer
