### ISSUE TITLE
api tests failing but not causing ci to fail

### ISSUE THREAD

**Issue by User1m** [usdigitalresponse/usdr-gost#243]
api tests failing but not causing ci to fail

[Continuous Integration #114](https://github.com/usdigitalresponse/usdr-gost/runs/7737484638?check_suite_focus=true)

<img width="835" alt="Screen Shot 2022-08-09 at 10 25 22 AM" src="https://user-images.githubusercontent.com/4316022/183718405-8342cec1-9e00-48f4-9496-5581361b27e3.png">

**Comment by mhuang-usdr** [comment]
@User1m is this closed now then?

**Comment by User1m** [comment]
yes
