### ISSUE TITLE
[ID] Upcoming closing dates should only show grants with deadlines that agencies have also marked as interested.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#248]
Currently, the closing dates card on the Dashboard shows all grants with upcoming deadlines. It should ONLY show grants with upcoming deadlines that ALSO have agencies who have indicated interest in them.

![image](https://user-images.githubusercontent.com/91221265/183973061-de2b1490-0896-43f2-98b4-abd3409101b1.png)

**Comment by CGowan44** [comment]
@mhuang-usdr @anigonzales I realized after testing some more that this needs some more work in addition to the new PR, so I moved the issue back to in progress. The query just needs to be more specific. When selecting a subagency the feed list doesn't change and while the interested agency lists are limited in scope to selected agencies and children, the displayed entries are not so the lists can be empty there. The query also needs to only get entries with interests from user associated agencies I'm assuming.

**Comment by anigonzales** [comment]
> @mhuang-usdr @anigonzales I realized after testing some more that this needs some more work in addition to the new PR, so I moved the issue back to in progress. The query just needs to be more specific. When selecting a subagency the feed list doesn't change and while the interested agency lists are limited in scope to selected agencies and children, the displayed entries are not so the lists can be empty there. The query also needs to only get entries with interests from user associated agencies I'm assuming.

"When selecting a subagency the feed list doesn't change and while the interested agency lists are limited in scope to selected agencies and children, the displayed entries are not so the lists can be empty there."  Can you clarify what you mean? I'm not sure I understand.

**Comment by CGowan44** [comment]
@anigonzales As usdr: 
![image](https://user-images.githubusercontent.com/56096100/184009455-d2e5c3dd-ef8a-43f9-824e-e8cfac9e71fc.png)

As grants office:
![image](https://user-images.githubusercontent.com/56096100/184009641-6fdd509d-cac0-430e-b922-9028747a7c1c.png)

As test22:
![image](https://user-images.githubusercontent.com/56096100/184009688-b6400068-43e3-4718-9e89-7134cf6899ea.png)

The interested lists only populate with agencies at or below the level of the one currently selected, so it seems like the results should reflect that as well. Or all of the results and the interested lists could be made to include entries from all user associated agencies and child agencies regardless of the currently selected agency. @mhuang-usdr Would one of these two ways be preferred over another?
