### ISSUE TITLE
Notify users of failure to generate audit and treasury report

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#2526]
### Why is this issue important?

When there are failures in generating the ARPA audit or treasury reports the user does not know if their file generation has failed due to an issue on the server.

### Current State

When an ARPA treasury/audit report fails and the task moves to the dead letter queue there is no notification to the user that kicked-off the process to inform them of the failure.

### Expected State

When an ARPA treasury/audit report fails and the task moves to the dead letter queue there is an email sent to the user with `grants-helpdesk@usdigitalresponse.org` being CC'd on the email.

Get final confirmation/sign-off from @ClaireValdivia on the verbiage of the email.

Verbiage
```
To: {user}
CC: grants-helpdesk@usdigitalresponse.org
Subject: {ReportName} generation has failed for {TenantName}
Body: There was an error generating a your requested {ReportName} report. Someone from USDR will reach out within 24 hours to debug the problem. We apologize for any inconvenience.
```

### Implementation Plan

```
// code that needs to be used to send an email.
const subject = ``
const emailPlain = ``
email.deliverEmail({
        toAddress: user.email,
        emailHTML: ``,
        emailPlain,
        subject,
    });
```
Insert the above code with the correct `subject` and `emailPlain` information into these two places:
1. https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/lib/audit-report.js#L582
2. https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/services/generate-arpa-report.js#L1094

**Comment by jcomeau1** [comment]
The verbiage is fine.
