### ISSUE TITLE
[Issue]: Make Browse Grants default tab

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2585]
### Why is this issue important?

the Browse Grants tab is the tab where core functionality of Grant Finder currently lives, but it is not where users currently land when they login, nor is it the first tab in the order. As it is the primary tab, we want that to be reflected by being first and where users land after login. 

We also observe in google analytics that a significant number of users don't make it past the My Grants tab after logging in, and that they spend less time on the My Grants tab than on the Browse Grants tab. We anticipate that landing users on the Browse Grants tab will result in higher numbers of users visiting Browse Grants, without the average time spent on Browse Grants decreasing. 

### Current State

Browse Grants is the second tab and is not where you land at login.

### Expected State

- [ ] When users login to the app, they should land on the Browse Grants tab
- [ ] The order of the first two tabs should be flipped - Browse Grants should be first, and My Grants should be second.

### Implementation Plan

- Modify the default `/` route for the Finder app so that it [redirects to](https://github.com/usdigitalresponse/usdr-gost/blob/eb7ef6c4d6d4332c7cf13ddee55fbfb72309bcce/packages/client/src/router/index.js#L27-L33) the `grants` route instead of `my-grants`. 
- To change the order of the tabs/menu links, swap the order of [the respective nav items](https://github.com/usdigitalresponse/usdr-gost/blob/eb7ef6c4d6d4332c7cf13ddee55fbfb72309bcce/packages/client/src/components/Layout.vue#L65-L66).

**Comment by TylerHendrickson** [comment]
@ClaireValdivia Implementation details added.

**Comment by ClaireValdivia** [comment]
thanks! @TylerHendrickson  after chatting with Caitlin, added into the top section what we want to observe before/after implementation re: metrics

**Comment by ClaireValdivia** [comment]
tested and looks good in staging!
