### ISSUE TITLE
[Issue]: New Audit Report Tab for Data specified by Subaward ID

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2609]
### Why is this issue important?
This was originally part of #2105 but was not completed in that issue so breaking it out here

With this change, the partners will finally have a truly complete fiscal picture of projects, subawards and subrecipients within the Audit Report. It will dramatically reduce the time spent auditing agency's submissions by cutting out the number of entries that tie out. Currently a partner like OH has to look at 500 or more rows to determine what is okay and what isn't - and do this manually. If 493 rows tie out, it means they only need to follow-up on 7 of them - a dramatic savings each reporting period.

### Current State

No Subawards view in the Audit Report.

### Expected State

New tab, called **Subawards**, should be created where Subaward ID is the key. Example of how it should look:

<u></u><u></u></span></li></ul></li></ul></ul>
  | 12-31-2021 Awards > 50000 SubAward Amount (Obligation) | 01-31-2022 Awards > 50000 SubAward Amount (Obligation) | 03-31-2022 Awards > 50000 SubAward Amount (Obligation) | 06-30-2022 Awards > 50000 SubAward Amount (Obligation) | 12-31-2021 Awards > 50000 Current Expenditure Amount | 01-31-2022 Awards > 50000 Current Expenditure Amount | 03-31-2022 Awards > 50000 Current Expenditure Amount | 06-30-2022 Awards > 50000 Current Expenditure Amount
-- | -- | -- | -- | -- | -- | -- | -- | --
Subaward ID | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Awards > 50000 tabColumn K (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID) | Expenditures > 50000Column G (total related Subaward ID)

<br class="Apple-interchange-newline">
</body>
</html>

**Acceptance Criteria**
- New tab will display on all audit reports after the "Project Summaries V2" tab, and be named "SubAwards"
- The first column is Subaward ID - starting on row 3, all subaward IDs that the partner has reported will be displayed from the beginning of time. Each Subaward ID should only display once. **should these be displayed in a specific order?**
- In row 1, Starting with column B, all reporting periods that exist for the partner should be displayed in their own column, starting with the oldest reporting period and continuing chronologically. The naming convention of the columns should be "[End Date of Reporting Period] Awards > 50000 SubAward Amount (Obligation)". Once the last reporting period is listed, the next column should start over at the first reporting period with the naming convention "[End Date of Reporting Period] Awards > 50000 Current Expenditure Amount"
- For each subaward ID row, the total amount from column K of the Awards > 50000 tab of the upload workbook associated with that subaward ID for the relevant reporting period should display in the Obligation column for the relevant reporting period
- For each subaward ID row, the total amount from column G of the Expenditures > 50000 tab of the upload workbook associated with that subaward ID for the relevant reporting period should display in the Expenditure column for the relevant reporting period
- Each reporting period, two new columns should appear in this tab - one for the current reporting period's Obligations and one for Expenditure Amounts.
- With each new reporting period, no data should be changed from what was displayed in previous reporting period columns
- With each new reporting period, updated amounts for new and existing subaward IDs should populate in the two new columns for the current reporting period

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@jcomeau1 separated this issue out and would love to discuss/get your thoughts on:
- why will this be valuable to partners? does it help them catch errors, or is it just calculations they may need for other reasons?
- if it helps them catch issues - what kind? 
- are partners currently doing these calculations manually? 
- thoughts on what the tab should be named?

**Comment by jcomeau1** [comment]
I updated the description to address Claire's questions. Moving this to Ready and assigning it to Tom.

**Comment by ClaireValdivia** [comment]
@tzinckgraf I know I missed some discussion about this last Fri, but are you able to add implementation details to this issue with how you plan to approach? i'll be adding in some details to the description also based on discussion with Joe. Thanks!

**Comment by ClaireValdivia** [comment]
discussion questions with Joe in slack:

- Is SubAward is referring to the combination of awards and expenditures?
- Correct that “Obligation” refers to items added in input template in “Awards” tab?
- Should subawards reflect all types of awards (i.e. subrecipient, contractor, beneficiary)?
- How do the column headers generate? Are they always the last day of each quarter’s reporting period for the current year? Do we expect them to only show for the current year? Or after this year, will the tab show 2024 and 2025?
- If implemented for Q1 of this year, correct that future quarter columns will display but be blank?
- Do we ever expect an award or expenditure to display in more than one quarter? i.e. if the start and end dates span more than one quarter? Or is it just for quarter in which they are first entered?

**Comment by ClaireValdivia** [comment]
Okay, @jcomeau1 @tzinckgraf, I just synched with Ty and confirming that we don't need implementation details for this, but would love if you both could review the acceptance criteria drafted above and let me know if this matches your understanding of how it will work. Thanks!

**Comment by tzinckgraf** [comment]
Acceptance criteria looks good to me.

**Comment by ClaireValdivia** [comment]
Notes/adjustments needed based on testing in prod:
- in general, the columns are showing chronologically left to right, but when I pull the report for ohio, june 2022 reporting period shows at the far right (after dec 2023 reporting period). screenshot here:
![image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/2d4bb668-9a10-4aba-a2f7-92ce8cfc30c5)

- it also looks like the order of the columns is different than the acceptance criteria and what we had previewed for partners (it shows obligations then expenditure for each year rather than all obligations then all expenditures). can this be adjusted so it matches the acceptance criteria and is consistent with project summaries v2 tab?
- the names of columns B and on are also not matching the acceptance criteria in the issue - can you please update this? The naming convention of the columns should be "[End Date of Reporting Period] Awards > 50000 SubAward Amount (Obligation)" and "[End Date of Reporting Period] Awards > 50000 Current Expenditure Amount"
