### ISSUE TITLE
[ID] If the Recent Activities or Upcoming Closing dates feeds on the dashboard have less than three rows, don't show the link for the full page.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#266]
If the feed on the dashboard is already showing all the information, the user doesn't need to see the full page.

- if the Recent Activities dates feed on the dashboard has the same number of rows that would show in the "Recent Activities" grid (e.g. four or less), don't show the link "See All Activity".
- if the Upcoming dates feed on the dashboard has the same number of rows that would show in the "Upcoming Dates" grid (e.g., three or less), don't show the link "See All Upcoming".

**Comment by chrisxkeith** [comment]
@mhuang-usdr Is there a UX reason for having "Upcoming Closing Dates" three rows and "Recent Activity" four?

**Comment by caitlinwinner** [comment]
@chrisxkeith I don't have context on any of these decisions only similar questions. There are 15 options under "Agency Status" drop down when viewing a grant and it's not obvious where those options map to elsewhere in the UI. (Relatedly, I was curious why "My Grants and Dashboard" are two different tabs and the use cases for each!)

**Comment by chrisxkeith** [comment]
@caitlinwinner No problem! I'm trying to get the context myself. :)

**Comment by mhuang-usdr** [comment]
@chrisxkeith 
> Is there a UX reason for having "Upcoming Closing Dates" three rows and "Recent Activity" four? "Upcoming Closing Date" rows are 'deeper'.

Nope, feel free to make them 3 each.

> As far as I can tell, it looks like “Upcoming Closing Dates” only includes grants that have been “Interested” (from my testing and reading of the code). Is this the expected behavior, or should it also include grants marked “Assigned”? Oops, had it backwards. Fixed this comment.

It should include both Assigned and Interested grants


@caitlinwinner 
> was curious why "My Grants" and "Dashboard" are two different tabs and the use cases for each!
No real good reason, it is legacy from eng-driven design :) 

My Grants is intended to be a todo-list/project management page for the average user. The recent activities and closing dates feeds might belong there better!

Dashboard is meant to show metrics and analytics for admins/super-users - for example, how much grant money an agency or an organization as a whole has applied for vs. been rejected for. There hasn't been a ton of functionality fleshed out around this particular use case yet.
