### ISSUE TITLE
Change url for grant detail pages

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2717]
### Why is this issue important?

Want to implement hierarchical url structure for added discoverability

### Current State

grant detail pages are following "grant/:id" 

### Expected State
grant detail pages should be "grants/:id" 

### Implementation Plan

1. Update the path in our [router definition](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/client/src/router/index.js#L72) from `/grant/:id` to `/grants/:id`
2. Update the three points in the code that route to the grant detail page (https://github.com/search?q=repo%3Ausdigitalresponse%2Fusdr-gost+grant%2F%24%7Bitem.grant_id%7D&type=code)
   - We should update these to use named routes (`{name: 'grantDetail', params: {id: item.grant_id}}`) instead of building route strings (`grant/${item.grant_id}`) to make them less brittle to changes like this, easier to type in the future, etc.
3. The in-flight (#2705) email updates will need to link to the new URL.

**Comment by ClaireValdivia** [comment]
@jeffsmohan  are you able to add technical implementation details to this issue?

**Comment by jeffsmohan** [comment]
✅ Added implementation details

**Comment by TylerHendrickson** [comment]
LGTM!

**Comment by ClaireValdivia** [comment]
looks good in staging!
