### ISSUE TITLE
[ID] Staff-level members should also have the ability to edit keywords and eligibility codes

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#278]
Currently only admins can do that. However, the State of Nevada pointed out that admin rights should be reserved for editing users and agencies, and keywords and eligibility codes are lower risk.

**Comment by chrisxkeith** [comment]
@mhuang-usdr : Questions about current functionality:
- I am able to add a keyword by clicking on the "Add" button in the upper right when viewing keywords. However, I don't see an "Add" button when I'm viewing eligibility codes.
- How do I edit an existing keyword? After creating a keyword, I don't see a pencil icon or any other edit indicator. I also tried double-clicking the keyword, to no effect.
Thanks!

**Comment by mhuang-usdr** [comment]
@chrisxkeith 

> I am able to add a keyword by clicking on the "Add" button in the upper right when viewing keywords. However, I don't see an "Add" button when I'm viewing eligibility codes.

Eligibility codes are set by Grants.gov, so users shouldn't be able to add or delete them - only check and uncheck them. This is working as intended.

> How do I edit an existing keyword? After creating a keyword, I don't see a pencil icon or any other edit indicator. I also tried double-clicking the keyword, to no effect.

I don't think we have the ability to edit an existing keyword - the user just has to delete and re-add it if they made a typo. I'm very open to adding an edit button. 

> Should non-admins have the ability to delete keywords and eligibility codes? I think it's dangerous, but will go with the majority opinion.

For eligibility codes - this is not a concern.

For keywords - this is a good question, I'll add you to the thread with our partners so you can ask them directly!

**Comment by chrisxkeith** [comment]
@mhuang-usdr 

> I'll add you to the thread with our partners

Thanks! Is that an email thread, a Slack thread, or somewhere else?

**Comment by chrisxkeith** [comment]
Merged into _staging.
