### ISSUE TITLE
[Bug]: Change Notification Preferences link in emails does not open my-profile

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2825]
### Why is this issue important?

needs to link users to where they can update notifications

### Current State

link from emails does not bring users to https://grants.usdigitalresponse.org/my-profile

### Expected State

On grant_assignment and grant_digest emails, the link in the footer that says "Change notification preferences" should link to https://grants.usdigitalresponse.org/my-profile

### Implementation Plan

The following functions need to be added...

**Comment by jeffsmohan** [comment]
@ClaireValdivia Thanks for flagging this! Would you mind including a few more details to help me debug? (I tested a couple emails on dev and the link seems to be working for me.)

- Which emails are you seeing this on? (grant digest, grant assigned, login link, etc.)
- Which environments are you seeing this in? (it sounded like maybe just staging, but not prod?)
- Where do the links actually point to in the emails you're seeing?

**Comment by ClaireValdivia** [comment]
@jeffsmohan  Ah okay so it looks like it's only broken for Grant assignment emails. In both staging and prod, I get directed here:
- in prod, seems to be broken - sends me to this url: https://grants.usdigitalresponse.org/my-grants/interested?utm_source=subscription&utm_medium=email&utm_campaign=GRANT_ASSIGNMENT 
- in staging, also not working, sends me here: https://staging.grants.usdr.dev/my-grants/interested?utm_source=subscription&utm_medium=email&utm_campaign=GRANT_ASSIGNMENT

both take me to the My Grants page > Interested tab when I want them to take me to /my-profile

Grant digest is working fine in both staging and prod

**Comment by jeffsmohan** [comment]
@ClaireValdivia Thanks! Just wanted to chime in that I've been working on this today and believe I understand the bug and the fix. However, the fix affects all email types, so I've been working hard today on actually being able to trigger all the email types in dev to ensure they still work as intended. 

So I haven't lost track of this, the fix is coming soon! But if you want the fix out ASAP, I could forgo some of the testing in dev and get a PR up pretty quickly, just let me know.

**Comment by ClaireValdivia** [comment]
totally fine to keep working on the testing and appreciate that!

**Comment by ClaireValdivia** [comment]
tested both digest and notification emails in staging and looks great!
