### ISSUE TITLE
Upload Validation - UEI is not required field when Entity Type is Contractor

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2944]
### Why is this issue important?

In December 2023, Treasury changed their requirements so contractors are no longer required to have a UEI and we have not yet made this change in our upload workbook or upload validation

Ohio has agency reporters who are unable to upload workbooks because their contractors do not have UEIs. 

### Current State
- In the subrecipient sheet, if Entity Type = Contractor or Subrecipient and they do not have a UEI entered, an upload validation error generates that says: "UEI is required for all new subrecipients and contractors". 
- When subrecipient type = Beneficiary, either a UEI or TIN is required (does not matter which one) 
- The upload validation errors only display if the subrecipient is new - we are looking into how we currently determine if a subrecipient is new (i.e. is it based on matching UEI or TIN?)

### Expected State
- UEI is required when subrecipient type = Subrecipient. If Entity Type = Subrecipient and there is no UEI, the error should generate, and the message should say: "UEI is required for all new subrecipients"
- Either a UEI or TIN is required (does not matter which one) when subrecipient type = Beneficiary or Contractor. The validation should be updated so if Entity Type = Contractor or Beneficiary and there is not a UEI or a TIN, an error should generate the following error message shows: "At least one of UEI or TIN/EIN must be set, but both are missing". If either a UEI or TIN is submitted for beneficiary or contractor, or both are submitted, no error generates.
- The upload validation errors only display if the subrecipient is new. If the subrecipient exists, no validation error will generate - we are looking into how we currently determine if a subrecipient is new (i.e. is it based on matching UEI or TIN?)
- if more than one subrecipient type is selected, if the multiple values include the type "Subrecipient", show the error "UEI is required for all new subrecipients". If the type is Contractor and/or Beneficiary, show the error ""At least one of UEI or TIN/EIN must be set, but both are missing".

### Implementation Plan

The following functions need to be added...

**Comment by tzinckgraf** [comment]
Looks like below is the source of the issue:
[validate-upload.js](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/services/validate-upload.js#L149)

A few questions:
- Do we want to check the date to make sure the date is after December 2023? I know we don't have anything that requires back filling data, and maybe just a comment could work for now. But we may not want to lose the info that it was invalid previously.
- Can you provide a sample file for testing?
