### ISSUE TITLE
Grant Digest Email Metrics: Configure the click tracking subdomain to support https

### ISSUE THREAD

**Issue by sanason** [usdigitalresponse/usdr-gost#2996]
Subtask of **[User Story: Grant Digest Email Metrics](https://github.com/usdigitalresponse/usdr-gost/issues/2749)** #2749 

#### Blocked by

N/A

#### Blocks

- #2880 

### Description

This is a follow-up to #2879 . In that ticket, we made some infrastructure changes to enable click tracking for the emails that we send to users (i.e., we are notified when users click on links in our emails). We defined a custom subdomain of the form `mail-redirect.<aws-region>.grants.usdigitalresponse.org` to redirect clicks. Links in our emails are replaced with URL's pointing to the `mail-redirect` subdomain, which is aliased to an AWS tracking domain (`awstrack.me`). It is the AWS tracking server that finally redirects to the original destination of the link.

There is a problem though because the links in our emails use `https` but the SSL certificate returned by the AWS tracking server obviously is not valid for our custom `mail-redirect` subdomain. So, a user who clicks on a link in one of our emails will see an error like this:

<img width="1010" alt="Screenshot 2024-04-29 at 4 45 34 PM" src="https://github.com/usdigitalresponse/usdr-gost/assets/8216592/3c50532f-6f07-41b6-9022-b8db49368ada">

Relevant AWS documentation [here](https://docs.aws.amazon.com/ses/latest/dg/configure-custom-open-click-domains.html).

### Implementation Plan

TODO

**Comment by ClaireValdivia** [comment]
I believe this is working in staging! tested sending a login email to one of my test accounts, then checked that the send, delivery, open, and click events were reflected in datadog

![Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/e9a344a9-0ac0-4de4-b9b2-78ba00b96927)
