### ISSUE TITLE
Fix yarn tests to run on Windows

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#300]
PS C:\Users\chris\Documents\Github\usdr-gost\packages\server> yarn test:db
yarn run v1.22.4
$ NODE_ENV=test mocha --timeout 10000 __tests__/db/*.test.js
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mattbroussard** [comment]
Some discussion in [Slack](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1661544455232139?thread_ts=1661530717.135939&cid=C0324KDQSCR)

> I think that both this and [#300](https://github.com/usdigitalresponse/usdr-gost/issues/300) have the same root cause: these scripts in package.json assume a Bash (or similar) environment:
> - NODE_ENV=test is bash syntax that sets an environment variable for a single command. There is a [windows equivalent](https://superuser.com/a/950944) but I don't know of a single syntax that works on both windows and *nix-like platforms.

> Recommend that windows users run these commands using Bash under [WSL](https://docs.microsoft.com/en-us/windows/wsl/about)
