### ISSUE TITLE
Agency parent error checking won't find a three-level circular reference

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#311]
This code makes sure that there is no parent-child circular references, but won't catch grandparent->parent->child->grandparent.

https://github.com/usdigitalresponse/usdr-gost/blob/1fe2a637b864bcf2f7ad1a967c3000170777aa38/packages/client/src/components/Modals/EditAgency.vue#L236

Unclear what will happen if this gets into the database. Could be a db error or it could return bad data.

This can be manually patched if it happens.

**Comment by chrisxkeith** [comment]
Can be fixed along with https://github.com/usdigitalresponse/usdr-gost/issues/791

**Comment by ClaireValdivia** [comment]
@TylerHendrickson going through old tickets and for this one, I'm not sure how to test it to see if it's still an issue - any thoughts?

**Comment by TylerHendrickson** [comment]
@ClaireValdivia Closing this issue – I don't think it's causing any problems and our overall landscape has changed since it was first identified.
