### ISSUE TITLE
Create a demo tenant

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#314]
Create a tenant for the purposes of giving partners demo access.

Name of the tenant should be `DEMO`

**Comment by mhuang-usdr** [comment]
@mattbroussard it works seamlessly in `_staging`, but fails in `prod` (couldn't figure out how to copy out of the Render shell, sorry):

<img width="673" alt="image" src="https://user-images.githubusercontent.com/91221265/191632419-9416a148-7725-42dc-a61b-b778026a642e.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/91221265/191632459-793702cb-c89f-47c0-81c9-69edbbb617b7.png">

**Comment by mattbroussard** [comment]
On mobile atm but running migrations on prod will fix this

**Comment by mhuang-usdr** [comment]
migration run and tenant created via this script. Will start a new issue tracking moving all non-USDR users to the demo tenant.

**Comment by mhuang-usdr** [comment]
See #356
