### ISSUE TITLE
[Infra] Can't scale past a single instance on Render.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#315]
From @mattbroussard on Slack:

I doubt this will be an issue anytime soon, but it looks like enabling the Disks feature in Render (needed for ARPA integration) means you can't scale past a single instance. In December they said they planned to eventually remove this limitation: https://feedback.render.com/features/p/allow-disk-access-from-multiple-instances-and-services
If we got to the point where we needed to scale to multiple instances and this still isn't resolved, I think we would have to migrate our uploads storage to something like S3 instead of Render's built-in disk construct.

Reading [[a bit more](https://render.com/docs/disks#application-considerations)](https://render.com/docs/disks#application-considerations) about this:

- Using the disks feature also prevents zero-downtime deploys. Not a huge deal but slightly annoying.
- It sound like their plan is to allow "multiple service instances *each with its own disk*", but not multiple instances sharing the same disk -- so even with this feature, once we need to scale past a single instance I think we'd need to switch to something like S3 for upload storage (or have some kind of stateful sharding where a given tenant is guaranteed to only be on a single specific instance)

Again, not a super pressing issue right now or likely anytime soon given how low the traffic + CPU/memory load we're dealing with is, but something to be aware of down the [road.cc](http://road.cc/) [[@Andrew Hyndman (PT)](https://usdigitalresponse.slack.com/team/U02N6NS9M45)](https://usdigitalresponse.slack.com/team/U02N6NS9M45) [[@Mindy Huang (PT)](https://usdigitalresponse.slack.com/team/U0285FPPSDA)](https://usdigitalresponse.slack.com/team/U0285FPPSDA)

**Comment by TylerHendrickson** [comment]
Addressing this with the AWS migration off Render
