### ISSUE TITLE
Move bugs over from ARPA repo

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#326]

**Comment by mattbroussard** [comment]
@mhuang-usdr is this actually done? I only see [one ARPA-related issue](https://github.com/usdigitalresponse/usdr-gost/issues?q=is%3Aissue+is%3Aopen+label%3A%22arpa+quarterly+reporter%22) in GOST repo, but there are [40 open issues](https://github.com/usdigitalresponse/arpa-reporter/issues) in arpa-reporter.

**Comment by mhuang-usdr** [comment]
Not yet - we have it scheduled for Tuesday. I had closed to clear clutter since we had time scheduled already, but to your point, will re-open :)
