### ISSUE TITLE
Consitency of agencyId vs agency use in variable names and url params

### ISSUE THREAD

**Issue by bspates** [usdigitalresponse/usdr-gost#328]
Across the code base the term agency sometimes refers to agencyId, and sometimes agencyId is used. Let's chose one and be consistent with it.

**Comment by mattbroussard** [comment]
My preference would be `agencyId` when dealing with the numeric ID and `agency` when dealing with an object corresponding to DB `agencies` row.

**Comment by ClaireValdivia** [comment]
closing, will need new ticket to address broader issues
