### ISSUE TITLE
[Issue]: UI tweaks to card design related to issue 3154

### ISSUE THREAD

**Issue by samserif23** [usdigitalresponse/usdr-gost#3373]
### Why is this issue important?

Updates following the first release of card design UI seen in staging. 

### Current State

**Card Design**
Border Radius: 4px (.25rem) -> Change to 8px (.5rem)

**Main Card (Grant Detail)**
Margins for primary (main content) card: 20px -> Change to 24px (1.5rem)
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/014b50e9-4470-4410-9c2d-0f08ca672a7b">
Back Button Row: Change top margin to 0px (24px total with card margin); bottom margin to 24px.
Grant Title Margins: Top: 16px (1rem), bottom: 24px (1.5rem).
Spacing between button row (view on grants, copy, print): 24px (1.5rem).
Make the button left-aligned to the left margin of the card (24px from edge)

**Secondary Card (Share, Status, Grant Activity, etc)**
Top/Bottom Margin: Change to 24px (1.5rem) -- Keeps the cards visually aligned in both columns (main and side).
Left/Right Margin: Change to 16px (1rem)-- to meet the narrower column sizing, shortening the side margins gives us more content space to work with.

<img width="412" alt="image" src="https://github.com/user-attachments/assets/5da904fb-89ef-4296-a6be-89b189ecd376">

Margin between search bar and entry for share / status card: 24px (1.5rem)
<img width="396" alt="image" src="https://github.com/user-attachments/assets/e93d9bf4-616c-43f5-9427-a2cdb3a5c38d">
Total spacing between entries: 24px (1.5rem)
- May need to remove padding on email address line (currently at 16px)
<img width="394" alt="image" src="https://github.com/user-attachments/assets/776a6e7c-13a8-454a-8cc6-dace8db60a1d">

### Expected State

When user visits X page...

### Implementation Plan

The following functions need to be added...

**Comment by samserif23** [comment]
**Adding additional specification images.**
<img width="1738" alt="Main Card Spacing" src="https://github.com/user-attachments/assets/bca9c3cc-bc07-4765-893c-fe4c96b25ea0">
<img width="956" alt="Share Card Spacing between elements" src="https://github.com/user-attachments/assets/fa48b4a5-09dc-4be3-9004-5fb3d21ff55f">
<img width="956" alt="Share Card Spacing Between Entries" src="https://github.com/user-attachments/assets/e0b65206-28ca-4ea8-8956-7e325ff51f44">

**Comment by ClaireValdivia** [comment]
@sushilrajeeva ah yes I see how that's confusing! #3240 is the issue that addresses the changes to the share activity. I think if it's easier to focus on the non-share aspects in this issue, then #3240 could cover all UI & content changes for Share. does that sound like a reasonable path forward to you?

**Comment by sushilrajeeva** [comment]
@ClaireValdivia then I guess I can close this issue as I have already finished coding the UI changes for non-share portion ( apart from additional specifications)

So far I have finished all the initial issue tasks:
1. Card Design
2. Main Card (Grant Detail)
3. Secondary Card (Share, Status, Grant Activity, etc)

Can I assume this issue can be closed?

**Comment by ClaireValdivia** [comment]
@sushilrajeeva you should link your relevant PR to this issue and submit a merge request for it - this will move it to "In Review" status. Once another engineering team member reviews and approves the PR, it will be merged to staging and the issue will be closed.

**Comment by ClaireValdivia** [comment]
Reviewing this in staging and it's looking pretty close to me! @samserif23 would you be able to take a look in staging and if anything looks off, list out the specific changes that are needed? I'm not sure if the spacing under the grant title and share grant/team status header are correct so we could add specific adjustments needed to #3240 if needed
