### ISSUE TITLE
Follow+Notes: Create client-side feature flag

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#3405]
Subtask of **[[STORY]: Update 'Status' to 'Follow + Note' feature](https://github.com/usdigitalresponse/usdr-gost/issues/2960)** #2960 

#### Blocked by

N/A

#### Blocks

- #3406
- #3429

### Definition of Done

A new feature flag, `followNotesEnabled`, is defined in the client-side library of feature flags.

### Implementation details

(See also: our [Feature Flags development guide](https://github.com/usdigitalresponse/usdr-gost/blob/main/docs/feature-flags.md).)

- In `packages/client/src/helpers/featureFlags/index.js`, create a new function called `followNotesEnabled()` that returns a boolean value based on whether a feature flag named `followNotesEnabled` strictly evaluates (`===`) to `true`.
- In `packages/client/public/deploy-config.js`, register the new `followNotesEnabled` with a value of `true` so that this feature is enabled by default in development environments.
  - Note: [Lines 16-17 of this file](https://github.com/usdigitalresponse/usdr-gost/blob/6a415a5d07f248f46df464decd54b4b312f66016/packages/client/public/deploy-config.js#L16-L17) are currently not formatted according to our ESLint rules. Please reformat so that this file is compliant.
- In `terraform/staging.tfvars`, register the new `followNotesEnabled` feature flag within the `website_feature_flags` map with a value of `false` so that this feature is disable by default in our Staging environment.
- In `terraform/prod.tfvars`,  register the new `followNotesEnabled` feature flag within the `website_feature_flags` map with a value of `false` so that this feature is disable by default in our Production environment.

**Comment by ClaireValdivia** [comment]
tried out the feature flag in staging and it is working as expected -thanks @sushilrajeeva !
