### ISSUE TITLE
Remove redundant `agencies.main_agency_id` column

### ISSUE THREAD

**Issue by mattbroussard** [usdigitalresponse/usdr-gost#357]
This column is redundant of the `main_agency_id` column in `tenants` table (because you can join `agencies.tenant_id = tenants.id`) and its NOT NULL constraint creates an annoying circular dependency that requires setting a dummy agency ID when creating new "root" agencies (such as when creating a new tenant).

The idea to drop the field came up in [this comment](https://github.com/usdigitalresponse/usdr-gost/pull/189#discussion_r968005072). From quick grepping it doesn't actually look like anything reads `agencies.main_agency_id` so doing a migration to remove the column and any write sites should be pretty straightforward.

This is a followup task from #189

Technical implementation details available in [this comment](https://github.com/usdigitalresponse/usdr-gost/issues/357#issuecomment-1411331136).

**Comment by TylerHendrickson** [comment]
@as1729 Can you investigate and follow up?

**Comment by TylerHendrickson** [comment]
**Technical implementation details:**
- Write a Knex migration script that drops the `main_agency_id` column from the `tenants` table
- Refactor fixtures and source code (see the below list of files) to remove remaining references to `main_agency_id`.


(Noting as a reference for PR review) As of today, the following files reference `main_agency_id` (all paths are relative to the `packages/server` directory):

- Fixtures:
  - `__tests__/arpa_reporter/server/fixtures/add-dummy-data.js`
  - `__tests__/arpa_reporter/server/seeds/02_users.js`
  - `__tests__/db/seeds/fixtures.js`
  - `seeds/dev/01_main.js`
  - `seeds/dev/ref/agencies.js`
- Knex migration scripts (these should not be edited):
  - `migrations/20220102020804_agency_add_main_agency_id.js`
  - `migrations/20220208185452_add_tenants.js`
  - `migrations/20220810231630_make_tenant_id_nonnull.js`
- Source code references:
  - `src/db/arpa_reporter_db_shims/agencies.js`
  - `src/db/index.js`
  - `src/db/tenant_creation.js`
  - `src/lib/agencyImporter.js`
  - `src/scripts/import_arpa_reporter_dump.js`

Files were found by running `grep -lr 'main_agency_id' packages/server` from the repository root.
