### ISSUE TITLE
[STORY]: Grant Activity digest notification preference

### ISSUE THREAD

**Issue by greg-adams** [usdigitalresponse/usdr-gost#3570]
Subtask of **[[STORY]: Create new email notifications for 'Follow + Note'](https://github.com/usdigitalresponse/usdr-gost/issues/2962)** #2960 

#### Blocks

- #3571
- #3572

### User Story

As an organization, we would like to foster more collaboration between our users to allow for the sharing of knowledge and resources to empower them to more efficiently and effectively apply for the grants discovered on our platform.

As a grantseeker, I want to be able to easily share grants I’ve discovered with my team.

As a grantseeker, I want to be able to easily find collaborators who may be able to help me when preparing and applying for grants.

As a grantseeker, I want to be able to quickly see what grants my team members are interested in.

As an admin, I want to be able to easily surface and resolve issues and blockers my team is running into.

### Why is this issue important?

In order to help build the collaborative spirit we're going for, we need to have a prompt to pull people back to the platform when people they may be interested in supporting or receiving support from mark interest in the same grant. This will help bring users back to the platform in a timely manner to collaborate on previously marked grants.

### Definition of Done

1. On a users My Profile page, a Grant Activity toggle will be available.
   - Name: Grant Activity
   - Description: Send me a daily summary of new activity for grants that I follow.
2. Toggling the input will update/save the preference

### Implementation Details

- Create a new input entry in Email Notifications of My Profile section
  - `MyProfileView` component controls displaying/saving user preferences
- Update new preference to be enabled by default upon user creation
  - uses a new notification type of `GRANT_ACTIVITY` as added to `src/lib/email/constants.js`

**Comment by phm200** [comment]
I grabbed this story as my first task. Will of course adjust to meet PR guidelines as needed

**Comment by ClaireValdivia** [comment]
@phm200 this looks great in staging! The only adjustment needed is that this should be behind the followNotesEnabled feature flag as it won't be applicable to users until we have the follow/notes feature launched. this was the implementation issues of the feature flag for reference, but let me know if you need more info! https://github.com/usdigitalresponse/usdr-gost/issues/3405

**Comment by phm200** [comment]
> @phm200 this looks great in staging! The only adjustment needed is that this should be behind the followNotesEnabled feature flag as it won't be applicable to users until we have the follow/notes feature launched. this was the implementation issues of the feature flag for reference, but let me know if you need more info! #3405

I will put this behind that feature flag in a follow up PR. No problem. I will plan to do that tonight. Thank you for testing it out!

**Comment by phm200** [comment]
@ClaireValdivia created PR #3606 to add feature flag. Do you want me to re-open this issue as well?

**Comment by ClaireValdivia** [comment]
thank you! and nope, this issue as good as is it - when it's closed it's move to "staging" status, and I manually move to closed when all testing is signed off on it's shipped to prod.

**Comment by ClaireValdivia** [comment]
feature flag is working as expected and this was deployed to prod today, thanks!
