### ISSUE TITLE
Add UI for switching between tools

### ISSUE THREAD

**Issue by mattbroussard** [usdigitalresponse/usdr-gost#360]
After 9/23, there will be 3 tools on the GOST platform:
- Grants Identification, at `/`
- ARPA Reporter, at `/arpa_reporter/`
- ARPA Annual Performance Reporter, at `/arpa-annual-performance-reporter`

If users accidentally go to the root of the grants.usdigitalresponse.org domain when intending to go to one of the other tools (i.e. because they only remember that part of the URL), we should provide some basic UI to let them get where the need to. I'm envisioning something conceptually similar to Google's app switcher:
![image](https://user-images.githubusercontent.com/3347176/191907111-4dff3c11-7581-4071-a1f5-f8e0a9394d48.png)

This button would get mounted in the header UI of all 3 tools and provide a quick way to switch between tools. Optionally, we could also add a dropdown on the main `/` login screen that uses the `redirect_to` param to send you someplace specific after login.

@mhuang-usdr any thoughts or concerns about something like this?

**Comment by mhuang-usdr** [comment]
Ooh. I like the idea of a basic switcher UI while we get a better full experience in place.

I think your idea of having a dropdown on the main / login screen fits more nicely with main pain point - users going to the wrong link upfront.

Also, adding an upper right switcher could be a heavier lift than expected, as some of our tools don't even have a header bar to speak of. We'd need to componentize the header first.

I'd start with the login screen dropdown and we can always add in the switcher in the header later.
