### ISSUE TITLE
Fix the 'test:api' target in server/package.json to make it more reliable

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#368]

**Comment by mattbroussard** [comment]
I think the main thing Chris has run into so far is timeouts due to race between server starting up and Mocha test runner; I had an idea in https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1663712820120909?thread_ts=1663709029.578369&cid=C0324KDQSCR for how to potentially fix that

**Comment by chrisxkeith** [comment]
From @mattbroussard : from some interactive debugging: it's not the TCP socket that's slow; we think it's filesystem operations when registering routes (which imports a bunch of modules to do so). Some reports of slow filesystem operations on proxied folders in WSL https://github.com/microsoft/WSL/issues/4197 -- Chris going to try moving repo checkout to a non-proxied folder inside the WSL environment (which if I understand correctly is basically a VM)

**Comment by chrisxkeith** [comment]
Not a problem that can be fixed in our code.
