### ISSUE TITLE
[Partner submission] Add 'Status of Completion' to Audit File

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#374]
**Submitted Description:**
Adding it here for FY23Q2 - currently going through an exercise to understand which projects were submitted with adopted budgets of X dollars but are not scheduled to start. Would be helpful to have this field pulled into the audit file, too.

**(Optional) Uploaded file - click to download:**

**Comment by NatHillardUSDR** [comment]
Oop, I took a look at this yesterday before it had moved from "Ready" to "New"
