### ISSUE TITLE
[ARPA] Create an extensible framework for enforcing conditionally required values

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#378]
There are a number of fields in the input template that are sometimes required, depending on the answer to a previous question.

We should programmatically detect these conditionally required values, and validate that if they are required, the value is present.

**Comment by mhuang-usdr** [comment]
This is causing partners a lot of issues ahead of the Jan'23 reporting cycle

**Comment by trumanc** [comment]
The first and most critical use-case of this feature has been accomplished in these two PRs: https://github.com/usdigitalresponse/usdr-gost/pull/740 https://github.com/usdigitalresponse/usdr-gost/pull/761

The point of those PRs is that there were around 30 fields that are usually required, but become optional if the project is in status 'Not started'. While we've handled those 30 fields, this idea applies to several other fields. Here are some examples:
* `Cancellation_Reason__c` is required if `Completion_Status__c` is `Cancelled`
* `Total_Cost_Capital_Expenditure__c` and `Type_of_Capital_Expenditure__c` are required if `Does_Project_Include_Capital_Expenditure__c` is 'Yes'
* `Type_of_Capital_Expenditure_Other__c` is required if the answer to `Type_of_Capital_Expenditure__c` is `Other (specify)`
* Many many many others

The details of when/how to determine if these fields are required is usually found in the workbook in the hidden row 5 which gives definitions for all the input columns. A good place to check for possibly conditional fields is https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/lib/outputTemplates.json where you can see all the fieldIds that include `"required": "Conditional"`


I'm not sure how useful a validation library would be here, because our validation system has a strong dependency on the inpout workbook. All the rules you see in outputTemplates.json is parsed directly from data found in the excel workbook, in order to try to ensure the workbook and the backend validations are as in-sync as possible. It might be possible to use a tool to improve it, but given the volume of code that already exists, I'm not sure if the benefits of adding it would outweigh the cost of having to move our current validation code to that system

**Comment by as1729** [comment]
Not necessary for the Monday March 20th deadline.

**Comment by as1729** [comment]
@trumanc let us know if you will be working on this while onboarding into the elections team or if its better to reassign.

**Comment by trumanc** [comment]
This ticket has been completed! There is some follow-up work in ticket #1074 that builds on this
