### ISSUE TITLE
[Partner submission] [Data Validation] SubAward Number in the Expenditures tab should be one of the subaward numbers listed in the subawards tab.

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#380]
**Submitted Description:**
SubAward Number in the Expenditures tab should be one of the subaward numbers listed in the subawards tab. Hoping to preempt the error in the screenshot attached.

Some agencies submitting the wrong unique ID for the ID field in the expenditures tab.

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5342196568214750640/capture14.PNG

**Comment by trumanc** [comment]
Fixed in https://github.com/usdigitalresponse/usdr-gost/pull/506
