### ISSUE TITLE
[Partner submission] [Data Validation] Ensure email address format is valid (email address prefix + @ symbol + email domain)

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#381]
**Submitted Description:**
UST Portal rejected an upload for the email address b/c someone entered “James Comer jcomer@rihousing.com” - would be a nice-to-have feature to ensure entries follow a valid email address format ((email address prefix + @ symbol + email domain) either in Render or Excel.

See example for what I am picturing (excuse the horrible art) - the text box would only appear after a successful validation.

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5341684888218910168/3Capture12.PNG

**Comment by NatHillardUSDR** [comment]
Oddly I can't re-link this to https://github.com/usdigitalresponse/usdr-gost/pull/901

**Comment by jcomeau1** [comment]
This was implemented in February, 2023. Closing.
