### ISSUE TITLE
Invalid subrecipient in Period 1 should not prevent uploading in Period 2

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/usdr-gost#386]
OH saw a case in which a subrecipient was part of an upload to the ARPA tool in Period 1.  Even though this subrecipient was never part of a "valid" upload, it was excluded (incorrectly) from subrecipient exports in Period 2.

**Comment by mhuang-usdr** [comment]
@trumanc can this be closed?

**Comment by as1729** [comment]
This does not seem to be a good first issue. @as1729 to work with @jcomeau1 and figure out the requirements and eng-plan prior to assigning this over to a developer.

**Comment by as1729** [comment]
When the file is invalidated, any subrecipients created by this invalidated upload must also be removed from the subrecipients tab as a valid subrecipient.

**Comment by as1729** [comment]
Same as #1675
