### ISSUE TITLE
Ozzie: Can we add a ‘reupload’ button?

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/usdr-gost#395]
It's a few more clicks than ideal to get from looking at an upload to the new upload submission screen.

Maybe we can add a shortcut in the UI?

**Comment by as1729** [comment]
We need to first gather more requirements and have a design discussion here before we make this ready as a good first issue.

@jcomeau1 will also need to confirm from partners whether this is worth pursuing as a feature.

**Comment by as1729** [comment]
I believe with the ability to invalidate uploads we now have this functionality. Closing ticket.
