### ISSUE TITLE
Restore support for Audit Report

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/usdr-gost#397]
This can probably be modelled after the CRF audit report feature.

Requirements:

MUST

- [x] list cumulative and period obligations and expenditures
- [x] list subtotals for _each_ reporting period

SHOULD

- [x] "crosswalk" between uploads and project IDs
- [x] include _all_ KPI fields in project summary tab
- [ ] publish summaries per EC of _all_ fields from EC tabs

COULD

- [ ] help verify that all uploaded data ended up in an output template (and which)
- [ ] highlight apparent numerical discrepancies
- [ ] "crosswalk" between uploads and output templates

**Comment by mhuang-usdr** [comment]
@ajhyndman can this be closed?

**Comment by TylerHendrickson** [comment]
@ajhyndman Can this be closed?

**Comment by ajhyndman** [comment]
I think it's fine to close this!  This is really just a stub ticket I put down to track all of our ideas for the audit report.

I don't think there we have committed to anything beyond what has already been implemented.
