### ISSUE TITLE
[ARPA/Infra] When new users are added to the ARPA Reporter, they should receive an email directing them to the ARPA tool.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#404]
Right now, adding users via the ARPA UI still directs them to grants.usdigitalresponse.org, which is the ID tool. This caused confusion for one of our partners.

The problem will be mitigated by #360 , but if we have capacity to make this fix I think it'll help the user experience tremendously.

**Comment by as1729** [comment]
@mhuang-usdr can you confirm if this is working as intended in staging? If so, we can push to prod.

**Comment by mhuang-usdr** [comment]
QA'd, LGTM

**Comment by mhuang-usdr** [comment]
@as1729

**Comment by as1729** [comment]
Can you approve this production release? https://github.com/usdigitalresponse/usdr-gost/pull/415
