### ISSUE TITLE
[ID] Nevada's SPOC button appears even for non-Nevada tenants

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#43]
From OH:

> Once the user indicates if they are interested or not, a button that says SPOC appears. If you click it, it is the form for the State of Nevada. Ohio does not follow the SPOC process nor has a form.

**Comment by Raphomet** [comment]
Is the SPOC process rare or common? I'm wondering if this should be controlled a user setting, or if USDR should just set it on an account by account basis.

(Maybe the latter for MVP and Settings Page later?)

**Comment by mhuang-usdr** [comment]
USDR should set it on a per-tenant basis. SPOC is a state program, ~11 states have it, each state has a different form for it. This feature doesn't need to be user configurable.

**Comment by davidbkay** [comment]
@mhuang-usdr merged to staging

**Comment by mhuang-usdr** [comment]
I'm unable to log into the staging environment to check

**Comment by mhuang-usdr** [comment]
Just reviewed in the staging environment. Looks good to me.

**Comment by as1729** [comment]
Closing this issue as it is complete 🥳

**Comment by as1729** [comment]
Noticing that this PR was not merged. Will revisit this.

**Comment by mhuang-usdr** [comment]
This button still shows up on the USDR tenant, though downloading it is broken
