### ISSUE TITLE
Improve/automate processing of arpa output templates

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#443]
Currently, the process of updating the output templates provided by the US treasury is a very manual and error-prone process, where we often don't even realize that updates have occurred.

For reference, this PR is an example of the process https://github.com/usdigitalresponse/usdr-gost/pull/424
It involves checkin in new binary .xlsm files as provided by treasury, and then *manually* checking for format changes and updating the field mappings in `generate-arpa-report.js`.

It would be nice if we could auto-parse the output templates and save them in some way that is easier to detect differences.
It could be based on how we read/parse the workbook. In that same PR we ran the `generateRules.mjs` script which reads data directly from the new input workbook file, and writes structured json describing that file to the `templateRules.json` and `templateDropdowns.json` files. A similar strategy of reading the .xlsm files and writing to json will let us easily detect changes in the format.

**Comment by mhuang-usdr** [comment]
@trumanc is this issue still relevant? I thought y'all wrote a script already!

**Comment by trumanc** [comment]
Yup we made good progress on this! We might want to document how the system works for new engineers later, but for now engineers can mimic what I did in this PR to update to new output template versions: https://github.com/usdigitalresponse/usdr-gost/pull/799
