### ISSUE TITLE
[ID] Keywords and eligibility codes should NOT filter the My Grants tab

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#456]
Current behavior:

- setting new keywords and eligibility codes filters what is seen in both the `Browse Grants` and `My Grants` tabs

Expected behavior:

- setting new keywords and eligibility code should only filter `Browse Grants`, NOT the `My Grants` tab

**Comment by chrisxkeith** [comment]
Don't do this if in the "My Grants" tab (?) : 
https://github.com/usdigitalresponse/usdr-gost/blob/af3a1302d061fe4091b6c0d2066f4365751442ab/packages/server/src/db/index.js#L301

**Comment by mhuang-usdr** [comment]
I will couch that I don't know the code too well, but seems like it, yes.

**Comment by mhuang-usdr** [comment]
@chrisxkeith

**Comment by chrisxkeith** [comment]
Manually verified in production
