### ISSUE TITLE
[ARPA P&E Reporting] Empty row triggering error preventing validation.

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#458]
**Submitted Description:**
https://grants.usdigitalresponse.org/arpa_reporter/uploads/f16eff67-fe7a-4894-9e4b-8ac8f9714b52

Link to validation file. Row 14 of subrecipient tab is empty but still triggers error that prevents upload.

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212007960331041/5409560918216179747/111.PNG

**Comment by trumanc** [comment]
The problem was identified, and is better described in https://github.com/usdigitalresponse/usdr-gost/issues/459
This particular case was resolved by removing an extra character that had been added several rows down in the workbook
