### ISSUE TITLE
arpa reporter: Validations report incorrect row labels when there are skipped rows

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#459]
**Current Behavior - Pulled out from comment below on how to recreate this bug:**
To see the bug firsthand, you can take a valid input workbook, and delete a required field in any of the rows of data. Trying to validate the file will show you that there is an error because of a missing field, but the error message should correctly report the row number.
Now, if you add an empty row into the workbook above the line where you have this error and revalidate, you should see that it is still reporting the missing field at the old row number, because it is incorrectly skipping the blank row. This is caused because the error processing assumes there are no empty lines, and assigns the row number based on what number record it is (https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/validate-upload.js#L419).
Ideally, we shouldn't be assuming anything about record index, and instead we should include the row-number as a part of the record when we parse it from the file here: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/records.js#L148
We should keep a count of what row we are on and include that row number in the object that is .push'ed into the records array during parsing. Then we can use that row number later when tagging errors with row data.

examples of current behavior: 
![Image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/90169942-7cf4-4499-9b05-67e584b1216e)

**Expected Behavior**
- users should be able to have blank rows in the upload file
- if an error or a warning occurs in a row below the blank row, the validation should correctly specify which row the error or warning is in

**Implementation Details**
The blank rows get filtered out in `records.js` on line 134. We specifically filter out empty rows. The row number gets populated in `validate-upload.js` on line 410. We even have a comment about a hard-coded offset.
It may be easiest to not filter the empty rows and then skip them at validation time. That would preserve the row numbers.

Alternatively, we can look to leverage a feature directly from sheetjs. As per the docs for sheet_to_json:
"If header is not 1, the row object will contain the non-enumerable property __rowNum__ that represents the row of the sheet corresponding to the entry."
We should be able to leverage that properly in the row to get the correct line numbers.

1. Ensure the SheetJS library does not skip blank rows. As per the documentation here (https://www.npmjs.com/package/xlsx#json)
> When header is not 1, the default is to skip blank rows. blankrows must be true to generate blank rows
Therefore we can set it to `true` in this code here: https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/services/records.js#L131
```js
        const rows = XLSX.utils.sheet_to_json(sheet, {
            ...
            blankrows: true,
        });
```

2. Add validation to skip blank rows. There exists some validation that seems to indicate that it skips blank rows. This needs to be verified if it is sufficient.
https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/services/records.js#L139

4. Capture the row number in the error 
> If header is not 1, the row object will contain the non-enumerable property __rowNum__ that represents the row of the sheet corresponding to the entry.
```js
// arpa_reporter/services/records.js
// access the __rowNum__ property and set it in the formattedRow object so it is accessible by validate-upload.js
loadRecordsForUpload
        for (const row of rows) {
            ...
            const formattedRow = {
                rowNum: row. __rowNum__
            };
            ...
            records.push({
                type, subcategory, upload, content: formattedRow,
            });
        }
```

```js
// arpa_reporter/services/validate-upload.js
// Here we access the rowNum attribute set by records.js
async function validateRules({
    upload, records, rules, trns,
}) {
    const errors = [];
        ...
        for (const record of tRecords) {
           ...
            recordErrors.forEach((error) => {
                ...
                error.row = record.rowNum;
                ...
            });
        }
    }

    return errors;
}
```

**Comment by trumanc** [comment]
After some changes made in https://github.com/usdigitalresponse/usdr-gost/pull/586, these error messages might also now have incorrect column labels when dealing with legacy workbook templates. We should address both the column and row labels when looking into this issue.

**Comment by mhuang-usdr** [comment]
@trumanc @jcomeau1 was this addressed?

**Comment by trumanc** [comment]
No, this issue still exists

**Comment by TylerHendrickson** [comment]
@trumanc Can you add any details around a prescribed path for fixing and/or investigating the source of this issue?

**Comment by trumanc** [comment]
So there are 2 related-but-distinct issues here (one for the rows, one for the columns) but I've grouped them together because I suspect the fixes will be similar.

I'll give descriptions of the errors, and then a brief idea of where I think the solution should go (with a big asterisk here that I haven't investigated the fixes super thoroughly and could be missing something important.

### First the incorrect-row-numbers bug:
To see the bug firsthand, you can take a valid input workbook, and delete a required field in any of the rows of data. Trying to validate the file will show you that there is an error because of a missing field, but the error message should correctly report the row number.
Now, if you add an empty row into the workbook above the line where you have this error and revalidate, you should see that it is still reporting the missing field at the old row number, because it is incorrectly skipping the blank row. This is caused because the error processing assumes there are no empty lines, and assigns the row number based on what number record it is (https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/validate-upload.js#L419).
Ideally, we shouldn't be assuming anything about record index, and instead we should include the row-number as a part of the record when we parse it from the file here: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/records.js#L148
We should keep a count of what row we are on and include that row number in the object that is `.push`'ed into the records array during parsing. Then we can use that row number later when tagging errors with row data.


### And the incorrect columns bug:
When recording errors in the validate-upload code, there are several places where we record the col as `col: rule.columnName` (here for example: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/services/validate-upload.js#L272)
The problem is that the rule.columnName is a constant that is parsed from the currently known most recent workbook, and is saved here: https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/lib/templateRules.json#L11
But uploaded workbooks aren't required to adhere to the same column ordering. When reading from a workbook, we trust the workbook to tell us the field-id for each column (this change was made recently to ensure that old workbooks continue to work, even if we add new columns in the future. That happened in this PR: https://github.com/usdigitalresponse/usdr-gost/pull/586) When recording the col of an error, we should use the col from the uploaded workbook header, not from the parsed-and-saved rules list. 
To see this bug firsthand, you can try uploading an old workbook (pre-Q4-2022) before we added new Display-Only columns to the expenditures/awards tabs).


Ideally, in both the row and the col case we should see if we can include the real row-number and col-name that came from the currently uploaded workbook by parsing that info in the record parsing code and passing it along to later code that needs it.

**Comment by ClaireValdivia** [comment]
Claire to update description; also will review in 2/9 meeting to see if anyone has worked on this already or if this is still outstanding

**Comment by ClaireValdivia** [comment]
Tom and Claire will both try testing out with blank rows

thinking that column issue could be from issue with an old template issue - we are pretty confident that the column issue is resolved.

**Comment by ClaireValdivia** [comment]
tested in staging and confirmed that when adding a blank row, the validation reported the incorrect row holding the error

![image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/a03ee92a-52e7-4f1b-9909-fe2bdff60a69)

**Comment by ClaireValdivia** [comment]
Updated the expected behavior in the issue! Next step is for @tzinckgraf to fill in implementation details (fyi @TylerHendrickson )

**Comment by ClaireValdivia** [comment]
Aditya to review implementation details and the move to Ready

**Comment by as1729** [comment]
Ideal to use the second approach and if that doesn't work then we will fallback to the first approach. We have the preference for the second approach laid out in the ticket.

**Comment by as1729** [comment]
Blocked by @as1729 - to move to ready by end of day today.

**Comment by ClaireValdivia** [comment]
@as1729 can this be moved to Ready?

**Comment by as1729** [comment]
Yes- will move it now

**Comment by ClaireValdivia** [comment]
This is looking great in staging! I have tested errors EC1 tab, sub-recipient, awards, expenditures, and aggregate awards tabs, and all are resulting in errors that reference the correct row numbers. have tried with different number of blank rows and leaving different fields blank, all seem to work :)
