### ISSUE TITLE
[ID] Export Recent Activities into a CSV

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#494]
Add an export to CSV feature similar to the one on Browse Grants.

This export should include as columns:

- The date of the activity
- The target agency in the activity
- The grant in the activity
- The detailed `status code` (ex. `Will Apply`, `Inadequate state authority`, etc)
- The name of the person who performed the activity
- the email of the person who performed the activity

![image](https://user-images.githubusercontent.com/91221265/196550196-d312766c-caef-4ebf-9ac0-653dc183b264.png)

![image](https://user-images.githubusercontent.com/91221265/196550250-b8fd0fac-bc3a-4798-82fb-5e8d458fc993.png)

**Comment by slants3** [comment]
This should be all set
