### ISSUE TITLE
 (2)[ID] User needs a way to hide Rejected Grants on the Browse Grants and My Grants tabs.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#50]

**Comment by mhuang-usdr** [comment]
From Alaska (originally tracked in #17):

>  if I finished using reviewing a grant, I need a way to close it out and mark it as "done."

**Comment by Raphomet** [comment]
If we automatically hide all rejected grants, then there will be no way for the user to undo that action.

So, instead, let's piggyback off of #53 , and add a fourth filter that allows users to filter by review status. This way, they can choose for themselves what they wish to view.

<img width="830" alt="CleanShot 2022-04-12 at 13 59 30@2x" src="https://user-images.githubusercontent.com/58006/163053705-3f25632d-73da-4a06-abf6-6647149d2227.png">

The depicted state should be the default state (DO show interesting, DON'T show rejected).

Just like all the other filters, this filter should be visible both on the "My Grants" and "Browse Grants" tabs.

**Comment by Raphomet** [comment]
@mhuang-usdr Let me know what you think!

**Comment by mhuang-usdr** [comment]
Sg! Is the idea that the same filters will be available in both Grants and
My Grants?

**Comment by mhuang-usdr** [comment]
This should be completed after #53

**Comment by mhuang-usdr** [comment]
For now, just implement "Marked as Interested"

**Comment by mhuang-usdr** [comment]
@CGowan44 I had a thought. The Interested and Rejected filters make sense under the Grants tab. But as you pointed out, it makes less sense under the My Grants tab.

So what if instead of doing the drop down filter for the My Grants tab, we add a sub-tab for Rejected alongside Interested and Assigned?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/91221265/176805011-da8dbf5f-f84a-4478-bdda-bb564368274f.png">
