### ISSUE TITLE
[ID Tool] Our tool should scrape Forecasted grants

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#51]

**Comment by as1729** [comment]
@mhuang-usdr @Rapol 
From what I can tell this is already happening here in the code. Am I missing something?
https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/lib/grantsgov.js#L108

I did notice that for [eligibility code filtering](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/lib/grantsgov.js#L87) we're not adding `forecasted` to the search filter. I added that in the MR [here](https://github.com/usdigitalresponse/usdr-gost/pull/75/files).

**Comment by mhuang-usdr** [comment]
@as1729 I think this is done right? Can you close it if so?
