### ISSUE TITLE
Review strange-looking code

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#513]
These lines of code look like they should have type `typeof` operator added, so that they actually check for object type, not just do a string comparison. Also, it's unclear why one checks `null `and the other `undefined`. It would be good to (if we can figure out the intent of the code) remove the '[truthy](https://dev.to/myogeshchavan97/javascript-basics-truthy-and-falsy-values-in-javascript-4jo2)' check and make them more definite.

https://github.com/usdigitalresponse/usdr-gost/blob/af3a1302d061fe4091b6c0d2066f4365751442ab/packages/server/src/db/index.js#L284

https://github.com/usdigitalresponse/usdr-gost/blob/af3a1302d061fe4091b6c0d2066f4365751442ab/packages/server/src/db/index.js#L323

**Comment by TylerHendrickson** [comment]
Prioritizing typescript
