### ISSUE TITLE
Support sorting on Award Floor column in Grants grids

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#515]
Via @mattbroussard : Award Floor: because this is extracted from raw_body and not stored in its own column, relying on Postgres to sort does not work. If you try to sort this column, you get no sorting. To fix this, I think we'd have to either add a new column and backfill it, or do a more complicated query to dynamically pull it out of the raw_body JSON in Postgres.

See also https://github.com/usdigitalresponse/usdr-gost/issues/425

**Comment by ClaireValdivia** [comment]
old issue, closing as we have removed award floor from results table
