### ISSUE TITLE
[ID] Nevada's SPOC button shows up for non-Nevada tenants in the My Grants tab

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#522]
Related to #43.

#43 fixed the issue of SPOC buttons showing up for non-Nevada tenants. However, upon further digging, it seems that it only fixed it for modals clicked through `Browse Grants` and on the `Dashboard.` If you click through a modal via the `My Grants` tab, you can still see the SPOC button.

**Comment by chrisxkeith** [comment]
@mhuang-usdr : I need a set of steps to reproduce this. This is what I tried:
- Logged into the production instance as a USDR user (chris.keith@gmail.com)
- Click on "My Grants"
- Click on grant "20230112-PN"
- I don't see any SPOC button in the modal. Am I looking in the wrong place?
![image](https://user-images.githubusercontent.com/3921494/198067719-fb5f912e-c1d9-4764-9b31-48512be46794.png)

**Comment by mhuang-usdr** [comment]
So odd! I just tried to repro what I did before as well and the issue is gone. I'll close this unless we can repro in the future!
