### ISSUE TITLE
[ID Tool] Implement Filter system for Browse Grants and My Grants tabs

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#53]
Related to #55

**Comment by mhuang-usdr** [comment]
Add keywords to the filter system.

**Comment by mhuang-usdr** [comment]
Should we match Grants.gov filters

Forecasted  (303)  
 Posted  (2,423)  
 Closed  (4,620)  
 Archived  (60,379)  

?

**Comment by mhuang-usdr** [comment]
Filter for rejected grants

**Comment by Raphomet** [comment]
<img width="583" alt="search filters" src="https://user-images.githubusercontent.com/58006/162344631-7be9af6c-0c4e-495b-b65a-ba8f8c7ba427.png">

We'd like to ship 3 filters: Opportunity Status, Opportunity Category, and Cost Sharing.

[Figma file](https://www.figma.com/file/ACzl0OlcPSL913vg2nezI9/Grants-ID-Tool?node-id=6%3A2538)
[Clickable prototype](https://www.figma.com/proto/ACzl0OlcPSL913vg2nezI9/Grants-ID-Tool?page-id=6%3A2537&node-id=6%3A2538&viewport=300%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=6%3A2538)

The Opportunity Status filter address #17 by allowing the user to filter out Closed / Archived grants.

**Comment by chrisxkeith** [comment]
Started manual testing in the Render staging instance, and see this when I select "Interested" in "Review Status":
![image](https://user-images.githubusercontent.com/3921494/204572563-0fc39721-1480-46e2-8325-f65e9219dbe1.png)
I assume that "NV:AGO" is a Nevada agency. Should I be able to see this row when I'm logged in as a USDR user?

**Comment by mhuang-usdr** [comment]
@chrisxkeith NV:AGO looks like it's actually a valid agency under the usdr tenant on the staging environment - I can see it in the agency tab

**Comment by chrisxkeith** [comment]
Verified in production
