### ISSUE TITLE
(2) [ID Tool] Add, remove, and reorder grants table columns

### ISSUE THREAD

**Issue by Raphomet** [usdigitalresponse/usdr-gost#55]
We recently got a walkthrough from Pari, a former state budget officer, of what she looks for when she's looking at grants. She gave us some new information about which data are most important and which aren't.

On both the My Grants and the All Grants view, let's make some changes to the table columns:

![grants table with new columns](https://user-images.githubusercontent.com/58006/162336581-5bab6055-bf0c-4960-b156-1db413336491.jpeg)

Here are the changes, and why:

1. **Remove the Grant ID column.** We don't need both Grant ID and Grant Number — both are unique identifiers, but grants.gov uses the Grant Number more (although they call it the "Opportunity Number").
2. **Rename Grant Number to Opportunity Number.** This matches what's on grants.gov and is more consistent for the user. Although I didn't wireframe it, this column can also be dark, just like Grant ID is now.
3. **Keep Title, Viewed By, and Interested Agencies the same.**
4. **Remove the Agency Code column.** We don't think it's important enough to show in this table. They can click through if they need to.
5. **Move Status to the right of Interested Agencies.**
6. **Move Opportunity Category to the right of Status.**
7. **Add Award Floor and Award Ceiling to the right of Cost Sharing.** We don't currently have these columns, but they are important to budget officers — they tell them how much they could expect to get if the grant is awarded! **These columns should also be sortable.**
8. **Remove Created At and Updated At.** These are debug columns that reflect the state of the database row, not the state of the grant — it's for developers, not the end user.

**Comment by Raphomet** [comment]
Pari actually says to **get rid of the Posted Date column**, too.

**Comment by Raphomet** [comment]
This applies to both the "My Grants" and "Grants / Browse Grants" tabs.

**Comment by mhuang-usdr** [comment]
Current state:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/91221265/174902894-de42040f-76a4-4fc5-82fc-0a59fee3929f.png">


Desired state:
![image](https://user-images.githubusercontent.com/91221265/174902783-c44a8ca1-60cd-4416-af81-d7bec0782256.png)

**Comment by mhuang-usdr** [comment]
cavukovic is taking this on (waiting to add him to the repo before we can officially assign him to the bug)
