### ISSUE TITLE
Update the Tenants tab so it is only visible when tenant id = 1

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#60]
The tenants tab was added for debugging purposes, but should be not be visible to every user.

<img width="706" alt="Screenshot 2022-04-19 125248" src="https://user-images.githubusercontent.com/91221265/164084735-88cbcdef-f841-421b-923a-e4b5b73b044b.png">

**Comment by mhuang-usdr** [comment]
This issue still needs to be resolved.

**Comment by mattbroussard** [comment]
PR is updated and ready to merge as soon as approved.
