### ISSUE TITLE
User should be able to assign a grant to any agency, not just agencies who are subagencies 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#61]

**Comment by davidbkay** [comment]
i'll grab this one since it runs parallel with #66. We'll have to track `assigned_by` which is already in the `assigned_grants_agency` table

**Comment by as1729** [comment]
Additional context here:
1. Query for populating the list will need a new endpoint that filters by tenantId and not SubAgency
2. The assignment of the grant to an agency will also need to be updated to allow to assign grants to agencies within the tenant.
```
router.put('/:grantId/assign/agencies', requireUser, async (req, res) => {
    const { user } = req.session;
    const { grantId } = req.params;
    const { agencyIds } = req.body;
    if (!agencyIds.every((agencyId) => isPartOfAgency(user.agency.subagencies, agencyId))) {
        res.sendStatus(403);
        return;
    }

    await db.assignGrantsToAgencies({ grantId, agencyIds, userId: user.id });
    res.json({});
});
```

**Comment by mhuang-usdr** [comment]
@davidbkay our conversation about multitenancy yesterday bled over to this issue. Have you started on this issue yet? If not, do you mind if @as1729 takes over?

**Comment by mhuang-usdr** [comment]
@slants3 I've verified that this bug still exists.

If you create a new sub-agency as a sub-agency, and switch yourself to view from that sub-agency, you are unable to assign the agency to anyone except yourself. You should still be able to assign a grant to any agency in the tenant.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/91221265/181133230-76dfa2d6-b443-41f0-9526-681a9e226f60.png">

**Comment by bspates** [comment]
@mhuang-usdr I'm having trouble understanding the use case from the context in this issue. Is it that a user that is part of an agency should be able to assign a grant to any sub-agency under their agency? Or something more of different?

**Comment by mhuang-usdr** [comment]
@bspates good question!

One of the goals of our tools is to ease communications and break down information silos between different parts of an organization. Hence, any user that happens upon a grant should be able to assign that grant to any other agency in their TENANT.

Right now, the user is only able to assign grants to their own agency or children agencies.
