### ISSUE TITLE
[Infra/ARPA] On the ARPA tool, we cannot add a user to the USDR agency 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#616]
![image](https://user-images.githubusercontent.com/91221265/202578801-e720af56-cb46-431b-a68f-fbcdfee1cd85.png)

This works in the ID tool, so there might be a special check that ARPA tool is doing on `agency_id`?

**Comment by mhuang-usdr** [comment]
This will surface as a major issue as the designer figures out how agencies/users should be shared across tools.

**Comment by TylerHendrickson** [comment]
Need to fix the false-y evaluation of Agency ID `0` – the FE is submitting it as `null`.

See @as1729 for more information.
