### ISSUE TITLE
[ID] Recent activities dashboard should reflect `Applied` activities

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#622]
Similar to #555 .

Recent activities dashboard should reflect `Applied` activities.

Right now the line shows up, but isn't a full sentence and doesn't have an icon.

For example, the image below should say:

> USDR **applied** for Private Sector Led Growth, Resilience and Response Activity

<img width="814" alt="199086788-038ebe78-cdde-4fde-b63e-ada10a9faa6c" src="https://user-images.githubusercontent.com/91221265/202820490-2eec521d-e3fa-43e8-9f28-1f47deb70142.png">

@rachel699 @cajinajr any ideas for these icons ?

**Comment by rachel699** [comment]
How about something like these? 
![humbleicons_user-asking](https://user-images.githubusercontent.com/60455000/202821887-06a5e65a-708b-41c0-95e2-d136ef566941.svg)
![Frame 4](https://user-images.githubusercontent.com/60455000/202821896-bbc1186d-f561-45d6-92dd-0e4d13564011.svg)
![Frame 5](https://user-images.githubusercontent.com/60455000/202821902-ee934b97-a28d-4330-9a43-d3c712ef1ee5.svg)

**Comment by rachel699** [comment]
If there'll be many kinds of activities, I think maybe we should think about not to make the icons in a rainbow of colors. But if it won't be much more, it might be fine.

**Comment by cajinajr** [comment]
To me the "raised hand" icon reads more like "interested" than applied. 

Again, I think it might be a good idea to look to Bootstrap's library for icons. I think any of the icons below would be a good option for "applied."

<img width="45" alt="Screen Shot 2022-11-19 at 10 06 05 AM" src="https://user-images.githubusercontent.com/16214088/202857433-6a790497-fb3b-480d-8b4d-3ce5bbf29afd.png"> https://icons.getbootstrap.com/icons/file-earmark-arrow-up/
<img width="40" alt="Screen Shot 2022-11-19 at 10 06 59 AM" src="https://user-images.githubusercontent.com/16214088/202857467-ce171aca-ac06-4800-8cbf-b67edb087161.png"> https://icons.getbootstrap.com/icons/file-earmark-arrow-up-fill/
<img width="40" alt="Screen Shot 2022-11-19 at 10 11 20 AM" src="https://user-images.githubusercontent.com/16214088/202857626-805a344b-b00f-43ae-8c8d-fcc4f64e0811.png"> https://icons.getbootstrap.com/icons/file-earmark-check/
<img width="43" alt="Screen Shot 2022-11-19 at 10 11 57 AM" src="https://user-images.githubusercontent.com/16214088/202857658-f95864a1-835c-4f4f-95b1-e4bc677f2853.png"> https://icons.getbootstrap.com/icons/file-earmark-check-fill/
<img width="39" alt="Screen Shot 2022-11-19 at 10 16 32 AM" src="https://user-images.githubusercontent.com/16214088/202857834-496d8a46-2c24-4445-accb-a9f5556e14a8.png"> https://icons.getbootstrap.com/icons/clipboard2-check/
<img width="36" alt="Screen Shot 2022-11-19 at 10 16 53 AM" src="https://user-images.githubusercontent.com/16214088/202857853-e4498a68-99a5-4e9c-9451-901f3fd4c29f.png"> https://icons.getbootstrap.com/icons/clipboard2-check-fill/


If the engineers don't really mind importing icons from multiple sources, then I think the one below could be a good option too.

<img width="25" alt="Screen Shot 2022-11-19 at 10 33 14 AM" src="https://user-images.githubusercontent.com/16214088/202858641-0d690299-6102-4d4a-987d-c51750059be7.png"> https://thenounproject.com/icon/apply-2714905/
