### ISSUE TITLE
Implement grant 'aging' (e.g., hiding old grants)

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#623]
(via @jcomeau1): I also remember the partners disliking that there were so many old (closed) grants in the mix when they did their searches. Obviously there are ways to exclude these from the queries, but I'm a fan of getting rid of data when it's no longer helpful.

**Possible UX:**
- Only show grants with a close date of today or later
- Add a checkbox for "All Grants"

**Comment by mhuang-usdr** [comment]
@Christopher Keith ***@***.***> this will be handled by roman's
filtering PR.

We talked with partners about this in the past - it's tricky to know
exactly what grants to "age" out- what if one day they want to look a
previous one up? And they also ask for analytics on what they've applied
for in the past, which necessitates keeping the old grants around.  So UX
decided a filter that users can toggle on and off themselves is the best
way to do it.

@Joe Comeau ***@***.***> fyi
