### ISSUE TITLE
Truncate text fields to avoid database insert and update errors

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#633]
E.g. : 2022-11-23T16:31:13.654667401Z knex error when creating a new row with key 340880 in grants: error: insert into "grants" ("agency_code", "award_ceiling", "cfda_list", "close_date", "cost_sharing", "description", "eligibility_codes", "grant_id", "grant_number", "notes", "open_date", "opportunity_category", "opportunity_status", "raw_body", "reviewer_name", "search_terms", "status", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) - value too long for type character varying(255)

Should probably truncate and append ellipses (e.g., '...') to indicate that text has been truncated.

**Comment by chrisxkeith** [comment]
Seems very low occurrence (2 out of 2792)
```
gost-app  | 2022-11-25T17:32:59.744642901Z knex error when creating a new row with key 340880 in grants: error: insert into "grants" ("agency_code", "award_ceiling", "cfda_list", "close_date", "cost_sharing", "description", "eligibility_codes", "grant_id", "grant_number", "notes", "open_date", "opportunity_category", "opportunity_status", "raw_body", "reviewer_name", "search_terms", "status", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) - value too long for type character varying(255)
gost-app  | 2022-11-25T17:33:00.782819765Z searching for  @ 1110
gost-app  | 2022-11-25T17:33:20.423877441Z found 15 total results on grants.gov
gost-app  | 2022-11-25T17:33:20.551582546Z knex error when creating a new row with key 340880 in grants: error: insert into "grants" ("agency_code", "award_ceiling", "cfda_list", "close_date", "cost_sharing", "description", "eligibility_codes", "grant_id", "grant_number", "notes", "open_date", "opportunity_category", "opportunity_status", "raw_body", "reviewer_name", "search_terms", "status", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) - value too long for type character varying(255)
...
gost-app  | 2022-11-25T17:33:29.740060784Z sync complete!, elapsed: 01:03:58, totalGrantsProcessed: 2792
```

**Comment by chrisxkeith** [comment]
Field that is too long is 
`cfda_list: (length 310): 93.262, 93.837, 93.084, 93.839, 93.855, 93.233, 93.840, 93.361, 93.273, 93.838, 93.073, 93.879, 93.351, 93.070, 93.865, 93.242, 93.326, 93.068, 93.173, 93.847, 93.121, 93.286, 93.853, 93.867, 93.846, 93.866, 93.083, 93.103, 93.113, 93.136, 93.213, 93.307, 93.142, 93.394, 93.395, 93.859, 93.279, 93.350, 93.172`
Truncating this won't work.

**Comment by TylerHendrickson** [comment]
Closing in favor of #877
