### ISSUE TITLE
Change query pageSize to improve grant scraping performance

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#636]
Changing this parameter from 10 to 25 will result in a 250% improvement (66 minutes to 26 minutes) in the elapsed time for doing a scraping for 200 days worth of grants.

https://github.com/usdigitalresponse/usdr-gost/blob/699ff64d194237c7eb18c724fbc90ba68371020c/packages/server/src/lib/grantsgov.js#L193

This is because (1) we can use fewer queries, and (2) we won't get the same grant twice in different queries:
![image](https://user-images.githubusercontent.com/3921494/204156186-4a0488dd-4889-48b7-9c41-7ff246d7fdc3.png)

There is some unknown risk here, in that there is no official documentation for the API we call. Here is my attempt at reverse-engineering that documentation:
https://github.com/usdigitalresponse/usdr-gost/wiki/API-%22spec%22-for-currently-used-grants.gov-endpoint

If, however, we get access to an official API, we may not need to do this, thus 'low priority'.

**Comment by TylerHendrickson** [comment]
Closing this as the functionality will be replaced by the new ingest process.
