### ISSUE TITLE
Upgrade `aws-sdk` to v3

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#653]
Currently, the server package makes use of the [2.x version of the AWS SDK for JavaScript](https://github.com/aws/aws-sdk-js#aws-sdk-for-javascript), which is scheduled to be deprecated to maintenance mode in 2023. 

The [3.x version of the AWS SDK for JavaScript](https://github.com/aws/aws-sdk-js-v3) is the recommended replacement library. In addition to remaining current, this version of the SDK is [modularly structured](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/), which helps keep the size of packages down by only building with SDK components that are actually in-use. As the SDK in its entirety is rather expansive, and at present we only use the SES client, migrating to the new version should yield a not-insignificant (roughly 72M) reduction in the `node_modules` footprint.

Upgrade path is documented [here](https://aws.amazon.com/blogs/developer/why-and-how-you-should-use-aws-sdk-for-javascript-v3-on-node-js-18/).

**Comment by jakekreider** [comment]
Quick update - I had some work started before I was unavailable and started a PR with it in #1234, but I had missed that more V2 SDK calls were being made with #1173, so it failed. I'll go back and get that upgraded as well.
