### ISSUE TITLE
Upload parsing failing with "weird errors"

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/usdr-gost#656]
Reported by Wisconsin during early testing.

It looks likely that #585 introduced a regression in upload parsing.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/11449340/205202267-07177c6c-a372-44ba-9960-6e7eb349e0c2.png">

**Comment by mhuang-usdr** [comment]
@ajhyndman @jcomeau1 @trumanc was this taken care of? can we close it?

**Comment by trumanc** [comment]
Yup! This was fixed in https://github.com/usdigitalresponse/usdr-gost/pull/657
