### ISSUE TITLE
[ID] Move `Eligibility Codes` from its own tab to a filter in the `Browse Grants` and `My Grants` pages

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#672]
Move `Eligibility Codes` from its own tab to a filter in the `Browse Grants` and `My Grants` pages.

This is the goal: 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/91221265/205786798-5bc3aef6-7534-433e-bbeb-ea85273354b0.png">

You can browse the full Figma file at https://www.figma.com/file/jHvmE56bZIQWozGreXDOit/Grants-ID-Tool?node-id=1%3A2

cc @rachel699, the designer

**Comment by TylerHendrickson** [comment]
@as1729 To document implementation details

**Comment by TylerHendrickson** [comment]
Closing in favor of saved search.
