### ISSUE TITLE
[ID] update grants ID filters with recommendations from UX

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#673]
### For `Browse Grants` only, remove:
- [ ] `Review Status` 
<img width="920" alt="image" src="https://user-images.githubusercontent.com/91221265/205762688-06c55fb0-f308-4db6-9469-8492d1c34da6.png">

### For both `Browse Grants` and `My Grants`:
This is the goal:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/91221265/205785282-8eb561f1-6259-4ba9-80a7-3585303822b1.png">

Remove:

- [ ] `Opportunity Category`

Rename:
- [ ] `Opportunity Status` to `Status`

Add:
- [ ] `Award Floor`
- [ ] `Award Ceiling`

You can see the details of the drop downs in the [Figma, under Search Filters](https://www.figma.com/file/jHvmE56bZIQWozGreXDOit/Grants-ID-Tool?node-id=1%3A2)

`Eligibility` will be tracked in a separate issue, #672.

**Comment by mhuang-usdr** [comment]
cc @rachel699

**Comment by disambiguator** [comment]
@mhuang-usdr Should these fields all be removed from the CSV as well?

**Comment by mhuang-usdr** [comment]
@disambiguator no, keep them in the CSV.

**Comment by misspran** [comment]
Should we pause on this? considering there's a whole redesign with filters? @mhuang-usdr
