### ISSUE TITLE
[ID] Move keywords from its tab into the search experience

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#675]
Store keywords in the search bar instead of in a separate page

<img width="502" alt="image" src="https://user-images.githubusercontent.com/91221265/205794704-07a08613-1902-4a7c-a86f-e465dee6badd.png">

TODO: think about how exclusionary keywords fits into this.

**Comment by mhuang-usdr** [comment]
@cajinajr not in ARPA or UEI, but this would be a good next project actually - eng is blocked on being able to implement the new search experience until we figure out how to weave negative keywords into the new experience.

The existing patterns in industry for negative keywords is largely in the ad space but not sure if we need to go as heavy-duty as they do.

**Comment by as1729** [comment]
cc @slants3 if you had any thoughts here.

**Comment by mhuang-usdr** [comment]
Waiting on caitlin's redesign

**Comment by ClaireValdivia** [comment]
Closing this as it's addressed with search redesign
