### ISSUE TITLE
Give an error message when attempting to delete agency with users

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#678]
This now fails silently with an error message in the log.

`gost-app  | 2022-12-06T19:52:04.907399374Z error: delete from "agencies" where "id" = $1 and "parent" = $2 and "name" = $3 and "abbreviation" = $4 and "warning_threshold" = $5 and "danger_threshold" = $6 - update or delete on table "agencies" violates foreign key constraint "users_agency_id_foreign" on table "users"`

Recommended UX: 

- Leave delete icon enabled. (Disabling it doesn't tell the admin why it's disabled).
- When admin attempts to delete agency, show an error dialog with a list of users that are 'attached' to the agency. This is so the admin doesn't have to search through users to find which one(s) are attached to that agency.

**Comment by TylerHendrickson** [comment]
@mhuang-usdr To prioritize wording/copy for the error message and how the info is presented to users.

**Comment by TylerHendrickson** [comment]
Closing to handle more holistically in error-management UX.

Tagging @caitlinwinner since this is a concrete use-case to consider.
