### ISSUE TITLE
[Infra] Add Agencies in bulk by uploading a CSV/Excel spreadsheet. 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#700]
Very similar to #355 - but instead of bulk loading users, we need a way to load `Agencies`

**Comment by TylerHendrickson** [comment]
@chrisxkeith Can this be closed?

**Comment by chrisxkeith** [comment]
My memory (which is not as good as it was :) is that we weren't going to close issues until they had been deployed to production. If that's changed, I'm fine closing it now. Thanks.

**Comment by TylerHendrickson** [comment]
Your memory is better than mine :) I'm fine waiting for the prod release before closing.

**Comment by chrisxkeith** [comment]
Deployed to production
