### ISSUE TITLE
[ARPA] Be able to delete a workbook

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#705]
On Thursday meeting, partners asked for the ability to delete a workbook upload. Users would accidentally upload, or get to chains of ~20 uploads long, and wanted to clear the screen. They received a lot of feedback from the agencies about this.

**Comment by mhuang-usdr** [comment]
@trumanc @ajhyndman an alternative can be to "archive" workbooks from the screen, but still have them around in the db if that's easier. But if there are parallel efforts in play to redesign the backend anyways, I do think a full deletion is better (keeps our disk usage lower, is more transparent to the users)

**Comment by mhuang-usdr** [comment]
@TylerHendrickson skipping Design for this because the UX will be minimal (some icon or button), the blocker right now is figuring out what the eng implications of deleting a workbook are (they are currently not deletable due to other things relying on them in the database). Once we have that I think we can have a more fruitful discussion about possible solutions!

**Comment by TylerHendrickson** [comment]
Deletion would be ideal; is there a technical reason that wouldn't be possible (or especially difficult)?

Product question: when a reporting period is closed, should it be possible to delete a workbook?

**Comment by mhuang-usdr** [comment]
1-pager [here](https://www.notion.so/usdr/ARPA-Deleting-a-workbook-3b1338107b6c4bfca8763fd526142e30)

**Comment by TylerHendrickson** [comment]
Closing in favor if #1268
