### ISSUE TITLE
[ID] Rename "Agency" to "Team"

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#727]
We found from talking with our partners that the term `Agency` didn't accurately reflect many of their use cases, and caused confusion. `Team` was more accurate.

This task is to update all instances of the word `Agency` or `Agencies` to `Team` or `Teams.` Here are two examples:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/91221265/209215559-e49eab93-34ae-4a98-873a-d3f0c892df1b.png">

**Comment by mhuang-usdr** [comment]
Waiting for FTE UXD's full redesign

**Comment by mhuang-usdr** [comment]
A document from Pari detailing this further: https://docs.google.com/document/d/1Xqp6w-2WUBGErF_6npXhjAi04O56p2_h/edit

**Comment by LieAlbertTriAdrian** [comment]
@mhuang-usdr Requested access to the docs to see whether I can help with that!

**Comment by ClaireValdivia** [comment]
duplicate of #1846
