### ISSUE TITLE
[GOST] URL is no longer grants.usdigitalresponse.org after logging in 

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#78]
Upon inputting my email to login, the link given is:

`Your link to access USDR's Grants Tool is https://gost-grants-tools.onrender.com/api/sessions/?passcode=f4fff1dd-3975-4a63-b5e7-96b83de25cb6. It expires in 30 minutes`

The base url should be `grants.usdigitalresponse.org` instead

**Comment by mattbroussard** [comment]
I think this is just a matter of setting `WEBSITE_DOMAIN`, `API_DOMAIN`, and `VUE_APP_GRANTS_API_URL` environment variables on Render to point at `https://grants.usdigitalresponse.org`

**Comment by mattbroussard** [comment]
Confirmed, I made this change and all user visible URLs are on `grants.usdigitalresponse.org` now, and everything works normally.
