### ISSUE TITLE
PRs trigger two builds, resulting in race + build cancellation 

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#821]
As seen in [this PR](https://github.com/usdigitalresponse/usdr-gost/pull/793), PRs currently trigger two builds, `build-and-push` (aka "Build Docker image for GOST API") and `test-server-client`. 

These seem to launch at the same time, and thus github actually ends up canceling one of the builds, as can be seen on [this page](https://github.com/usdigitalresponse/usdr-gost/actions/runs/3894581181/attempts/1) -- you then see the error response "Canceling since a higher priority waiting request for 'refs/pull/793/merge' exists" . 

Notably it's possible to work around this by re-running the job, this results in a passing check for the PR. 

We should investigate how to avoid these two jobs racing against one another and triggering these auto-cancelations.

**Comment by TylerHendrickson** [comment]
@NatHillardUSDR This should be fixed by https://github.com/usdigitalresponse/usdr-gost/pull/815. Are you still seeing this?

**Comment by NatHillardUSDR** [comment]
Yep, that seems to have fixed things - Thanks!
