### ISSUE TITLE
[ID] If an grant is marked as rejected, it should no longer show up on the Upcoming Close Dates feed.

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#835]
**expected Behavior:**
If an grant is marked as rejected (e.g. via the `My Grants` page), it should no longer show up on the Dashboard > Upcoming Close Dates feed

**current Behavior:**
A grant is marked as rejected, but it still shows up on the Upcoming Close Dates feed

![image](https://user-images.githubusercontent.com/91221265/213565202-087e8952-96bd-49f9-a8e9-e69d6f1f5884.png)

**Comment by as1729** [comment]
Blocked by @as1729 on review.
