### ISSUE TITLE
Set up Nevada as a tenant

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#84]
- [ ] Add "State of Nevada" as a tenant
- [ ] Make the root agency "Administration: Grant Office"
- [ ] Add "grants.dev@usdigitalresponse.org" as an admin to that tenant

**Comment by mhuang-usdr** [comment]
@slants3 - I remember now! We set up `Nevada Tenant` as a test development tenant, but we meant to blow it away and create a new one before launching with NV.

Can you rename `Nevada Tenant` to `Test Tenant` (there are people dev-ing in this tenant so I don't want to blow it away), and create a new tenant to the specs in the original description please?

If you can make this a script, that'll allow me to set up a new tenant with ease in the future as well :)

**Comment by slants3** [comment]
@mhuang-usdr got it!

To clarify, the tenant creation process should not be available as an UI element on the site correct but should instead only be accessible via a script in the console or something along those lines?

Also do you know if we have existing scripts for anything else?

**Comment by mhuang-usdr** [comment]
@slants3 - eventually it'd be great to have a UI element on the site, but the faster (and very acceptable) solution to build and maintain is to have a script.

I don't think we have any in this repo, but you can check out this sister repo (different tool, but still working in the Grants space) for an example - https://github.com/usdigitalresponse/arpa-reporter/tree/staging/scripts

**Comment by chrisxkeith** [comment]
```
gost_grants_tools_db=> select * from users where name = 'USDR Dev NV';
 id |                email                |    name     | role_id |          created_at           | tags | agency_id | tenant_id
----+-------------------------------------+-------------+---------+-------------------------------+------+-----------+-----------
 56 | grants.dev+nv@usdigitalresponse.org | USDR Dev NV |       1 | 2022-08-10 21:32:03.591422+00 |      |       384 |         2
```
