### ISSUE TITLE
(3)Edit Agency is missing some functionality

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#85]
Go to Agency tab > Edit icon. The modal is missing functionality to:

- [x] Change the name
- [x] Change the abbreviation
- [x] Change the parent agency
- [x] Delete the agency

<img width="508" alt="image" src="https://user-images.githubusercontent.com/91221265/170601362-0122d839-55d3-4377-9f2f-02f34c2b426b.png">

These fields (besides delete) already exist in the Add Agency modal.
<img width="337" alt="image" src="https://user-images.githubusercontent.com/91221265/170601738-232d1a10-cee1-40b9-b7db-f5847748e258.png">

**Comment by User1m** [comment]
@mhuang-usdr is this still open?

**Comment by mhuang-usdr** [comment]
It is in part. I'll pull out the remaining tasks into a separate issue

**Comment by mhuang-usdr** [comment]
QA:  Parent Agency field shows the ID of the parent agency, but should show the Name of the Parent agency.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/91221265/185464032-f641f29b-6992-414f-9377-b56dd5c737cc.png">

**Comment by chrisxkeith** [comment]
Fixed by https://github.com/usdigitalresponse/usdr-gost/pull/313 .
