### ISSUE TITLE
(1) input fields for Add Agency should not show errors until after the user has finished typing

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#86]
Right now, it appears with input errors without the user ever typing.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/91221265/170601969-80709420-28cc-4805-b0f2-d68bd01e9b0e.png">

**Comment by User1m** [comment]
@mhuang-usdr It would be great if you could include steps to access the area of the application where this issue is.

eg. Go to "Agencies" > Click "Add" 

something like that so the user knows where to start digging.
