### ISSUE TITLE
[Grants Identification] Grants Notification Email Issues

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/usdr-gost#863]
**Submitted Description:**
- I added keywords that I now receive grant notification emails. Other users within my agency appear to be receiving these emails also. 

- Noting that users show up across USDR tools. E.g. one user that does ARPA reporting is also a grant ID tool user.

- There could be an error in the URL behind "View Grant" that leads to an 'http’s server IP address could not be found.' message. E.g. https://http/secure-web.cisco.com/11NuyfsFvme9OGAdiFEdxMoipk6fIcVVK4WvO9QvMaDSkiqeOe97UTMpCl4tybGtxIRAxBnId0wVCmbICoJbr-s-xIuh9IcQrPuSkmOTmM4tMoqGUsZdwi_NsPgyqI2oq1jv8-aScvTDB_GR5fZ0Uy3SB7TtI6wSFkiltkxabPaZ4Jaj7Aywfb8IshmwHau0tUkUBaxp0ebrBHRcE1sTV7L-fqoJL0P1W6jreF7GMYJ5zYDIfIx4LYu3rJvfoGkc7DTQUakc_b70S7avaxeMzVqgUh-Q1BGCgqlwZvQzPe6sL6f6cle0H_AaNV-4Bz_Gv/http%3A%2F%2Fwww.grants.gov%2Fweb%2Fgrants%2Fview-opportunity.html%3FoppId%3D345527 

**(Optional) Uploaded file - click to download:**

**Comment by mhuang-usdr** [comment]
I'll follow up on the desired email behavior for users across tools.

@as1729 can you look into the URL issue?

**Comment by as1729** [comment]
@mhuang-usdr it will be fixed with this issue here: https://github.com/usdigitalresponse/usdr-gost/issues/853

We're QA-ing today so will be ready by Monday's digest
