### ISSUE TITLE
Migrate VARCHAR columns to TEXT

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#877]
**DOD:** Postgres DB columns that previously were type `VARCHAR` are now type `TEXT`, except for columns in the `migrations` table.

**Background:** Many of the columns in our Postgres DB that we use to store string/text data are currently implemented as `VARCHAR(255)`. This pattern has lead to various issues (e.g. as described in #633) that are cause by what is effectively an arbitrary max-character limit on columns used to store text values. It's also worth noting that in Postgres, there is [no performance benefit](https://www.depesz.com/2010/03/02/charx-vs-varcharx-vs-varchar-vs-text/) for choosing `VARCHAR` over `TEXT`, as they are both backed by the same underlying (variable-length array) type, which creates a compelling argument for treating `TEXT` as the go-to default type for storing string/text data in Postgres, and resorting to `VARCHAR` only in (presumably rare) cases where business logic would benefit from enforcing a character limit at the DB layer. For this reason, this ticket prescribes migrating all currently-`VARCHAR` columns to `TEXT`, rather than only the columns where the max-length constraint has resulted in a known bug.

**Implementation details:**
- Write a Knex migration script that applies an `ALTER TABLE ... ALTER COLUMN ... TYPE text` operation to every `VARCHAR`-typed column in the database (excluding the `migrations` table, which is managed by Knex).
- Ensure that the migration script runs within a single transaction.
- Run migration script on Staging and ensure that operations that insert/update data in the migrated columns have no apparent regressions.
- Schedule downtime to run the migration script on Production. 

**Other notes:**
- To help identify columns to target, the following SQL will produce a row containing the table and column names for every `VARCHAR` ("character varying") column:
    ```sql
  SELECT  
    c.table_name,  
    c.column_name  
  FROM information_schema.columns c  
    JOIN information_schema.tables t  
      ON t.table_schema = c.table_schema  
      AND t.table_name = c.table_name  
      AND t.table_type = 'BASE TABLE'  
  WHERE c.data_type = 'character varying'  
    AND c.table_schema NOT IN ('information_schema', 'pg_catalog')  
    AND c.table_name NOT IN ('migrations')  
  ORDER BY  
    c.table_name,  
    c.column_name;
    ```
- The above SQL can be modified to produce and execute a dynamic statement that executes within a transaction:
  ```sql
  DO $bulkmigration$
  BEGIN
  EXECUTE (
    SELECT
        string_agg(  
          format (  
            'ALTER TABLE %I ALTER COLUMN %I TYPE text',  
            c.table_name,  
            c.column_name  
          ),  
        E';\n')
    FROM information_schema.columns c  
      JOIN information_schema.tables t  
        ON t.table_schema = c.table_schema  
        AND t.table_name = c.table_name  
        AND t.table_type = 'BASE TABLE'  
    WHERE c.data_type = 'character varying'  
      AND c.table_schema NOT IN ('information_schema', 'pg_catalog')  
      AND c.table_name NOT IN ('migrations')
  );
  END
  $bulkmigration$;
    ```

**Comment by chrisxkeith** [comment]
Unfortunately, we won't be able to test this in _staging, since the columns are already of type 'text';
```
gost_grants_tools_staging_db=> select c.table_name, c.column_name, c.data_type from information_schema.columns c where c.column_name = 'cfda_list';
 table_name | column_name | data_type 
------------+-------------+-----------
 grants     | cfda_list   | text
(1 row)

gost_grants_tools_db=> select c.table_name, c.column_name, c.data_type from information_schema.columns c where c.column_name = 'cfda_list';
 table_name | column_name |     data_type     
------------+-------------+-------------------
 grants     | cfda_list   | character varying
(1 row)
```

**Comment by chrisxkeith** [comment]
I did not realize that the script above creates and _executes_ the SQL to migrate the database. I believe that is why _staging didn't have any 'character varying' columns.

**Comment by chrisxkeith** [comment]
Task list:

- Change Ty’s SQL into a knex statement.
- knex migrate:make <migration_name>
- Fill the migration file with the knex statement.
- Run against local db.
- Create the pull request.
-
