### ISSUE TITLE
Move email login from grants-identification@ to grants-notifications@

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#88]
Right now, all email notifications from the integrated GOST tool are still sent from grants-identification@usdigitalresponse.org. They should be sent from the consolidated grants-notifications@usdigitalresponse.org email address instead.

You can see existing credentials for grants-notifications@usdigitalresponse.org in the 1Password vault (ask Mindy for access)

You can create new credentials for grants-notifications@usdigitalresponse.org by make a tools access request for AWS, and describing that you need SES
[https://usdr.link/tools/request](https://usdigitalresponse.slack.com/archives/C03FWRVKM7W/p1652819464701519).

**Comment by trumanc** [comment]
Just updated the environment variables and redeployed and confirmed the login email on prod is coming from grants-notifications now:
<img width="742" alt="Screen Shot 2022-09-15 at 10 37 02 AM" src="https://user-images.githubusercontent.com/3675290/190472877-37d6b593-edbd-4f9a-bf2f-18b8408b3f7c.png">
