### ISSUE TITLE
[ID] Visually distinguish grants that have been Unread (unreviewed) vs. Read (reviewed)

### ISSUE THREAD

**Issue by cajinajr** [usdigitalresponse/usdr-gost#888]
Related to issue #74 but creating a new issue to start with a clean slate since the proposed solution no longer involves creating a filter.

Taking a cue from existing patterns in email clients, we've settled on using a bolded/unbolded text styling to visually distinguish unread/read grants (respectively). We believe there are some advantages to a solution like this:

- It's a visual language pattern that users should already be used to
- It's low effort implementation for engineering
- It reserves other potential visual cues to be used for other solutions (for example one iteration I toyed with involved using badges to mark the grants)

Below is a screenshot of my mockups for what this would look like:

![Image](https://user-images.githubusercontent.com/16214088/215882136-142e975b-2b33-4645-aadc-e3368fc89129.jpg)

Another stylistic change to note: for sake of simplifying the table a bit, the background color for the Opportunity Number column has been removed, as well as the alternating stripe background for the rows. The aim is to reduce the number of colors in the table so that we can use them a little more purposefully in the future.

**Comment by mhuang-usdr** [comment]
The work around removing columns is tracked separately in #889.

**Comment by cajinajr** [comment]
> The work around removing columns is tracked separately in #889.

Noted. Thanks Mindy. As soon as I hit publish on this I immediately changed my mind and edited my original post to take out the stuff about columns. Should be more focused now.
