### ISSUE TITLE
Support explicitly setting agency and reporting period in the ARPA Reporter upload API

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#895]
Subtask of: #786

**DOD:** POST requests to the `/api/uploads` endpoint support supplemental `reportingPeriodId` and `agencyId` fields.

**Implementation details:**
- Inspect the body of the incoming request object (which [multer](https://github.com/expressjs/multer) makes available via `req.body`) for non-null `reportingPeriodId` and `agencyId` field values. 
- When `reportingPeriodId` is not null, use that value (**not** the value returned by `getReportingPeriod()`) to set the `reporting_period_id` value on the `upload` being saved to the DB.
- When `reportingPeriodId` is null, default to the current behavior of deriving this value by calling the `getReportingPeriod()`.
	- If the `reportingPeriodId` is invalid, abort the upload (deleting any partially-created file) and respond with an error.
- When `agencyId` is not null, first validate that the authenticated User is associated with that Agency. Then, use the value to set the `agency_id` value on the `upload` being saved to the DB.
	- If the user is not associated with the identified agency, abort the upload (deleting any created files) and respond with an error.
	- If the contents of the spreadsheet also provide an Agency ID that does not match the value submitted in the request's form data, abort the upload (deleting any created files) and respond with an error.
- When `agencyId` is null, default to the current behavior of deriving this value from the contents of the uploaded spreadsheet.

**Technical notes:**
- Because the `POST /api/uploads`  route expects a `multipart/form-data` request to provide the uploaded file (rather than, say, a base64-encoded text representation of the file), it is not possible to provide a JSON payload like most other API requests. Therefore, the client will provide supplemental data in additional form-encoded fields, which are then exposed server-side via `req.body`.
- According to the [multer](https://github.com/expressjs/multer) README, the `req.body` property may not be fully populated until the request (including/especially the incoming file upload) has been fully read. Therefore, it may be necessary to defer checks for supplemental data fields until after the `req.file` buffer has been completely written to the local filesystem.

**Comment by NatHillardUSDR** [comment]
Hey @TylerHendrickson / @trumanc , I have a few logistical questions around this actually that I wanted to clarify before I move this patch out of DRAFT:

> When reportingPeriodId is not null, use that value (not the value returned by getReportingPeriod()) to set the reporting_period_id value on the upload being saved to the DB.

It is possible to call `getReportingPeriod` with a `reportingPeriodId`, but if you do so, it filters by tenant by default. Should we be bypassing `getReportingPeriod` in this case entirely (and thereby ignoring the `tenantId`) and setting the value, or do as `getReportingPeriod` does and do that tenant filter here as well? The proposed implementation uses `getReportingPeriod` but this may be too restrictive.

> When agencyId is not null, first validate that the authenticated User is associated with that Agency. 
The current code calls 
```js  
const userRecord = await getUser(userId);
    if (agencyId !== userRecord.agency_id) {
```

Is this what is intended by "associated with that Agency", that the user must have their `agency_id` set to this value specifically? I'm realizing that in the UI ticket, we call out that there should be a dropdown list of potential agencies, which we get with
```js
this.$store.state.agencies.map((agency) => ({ text: agency.name, value: agency.id }));
```
so in theory we'd have agencies there that could be selected but which aren't assigned to a given user. It seems we may want to relax this / I may be misunderstanding that particular phrase?

> If the contents of the spreadsheet also provide an Agency ID that does not match the value submitted in the request's form data, abort the upload (deleting any created files) and respond with an error.

We currently don't parse the form until after it is persisted to disk. To do so beforehand would be a relatively significant shift. With the proposed patch, the behavior is that validation happens after persistence, and if there are issues, the sheet is still persisted/we don't delete it. Is this acceptable, or should I consider moving the order in which the parsing of the form itself happens?

> When agencyId is null, default to the current behavior of deriving this value from the contents of the uploaded spreadsheet.

Similar to the above, this happens to take place during the validate phase, but in theory we could do this by parsing the sheet sooner - do we want to, or is it acceptable for this to happen later as part of the post-persistence validation phase, as it currently does? 

Happy to talk through any of these on a call also if it would be easier!

**Comment by NatHillardUSDR** [comment]
I've rebased these changes against `_staging` just now and pushed back to this branch. The patch is generally ready to go now and has tests, but I did want to make sure to check on the above!

**Comment by trumanc** [comment]
Great questions @NatHillardUSDR ! Here are my answers:

> Should we be bypassing getReportingPeriod in this case entirely (and thereby ignoring the tenantId) and setting the value, or do as getReportingPeriod does and do that tenant filter here as well? The proposed implementation uses getReportingPeriod but this may be too restrictive.

It should be safe (and in fact recommended) to filter by tenant id here. Every user is **strongly** tied to a tenant id, and each tenant has its own current reporting period. So filtering by tenant id is likely a good safety check to make sure we don't accidentally associate the upload with a government that the user is not associated with.


Being "associated with an agency" is a little trickier. I don't think the ARPA reporter ever actually uses the userRecord.agency_id field. I think that field mostly exists in the ID tool, and we have to support it now in ARPA tool. The result is that while we might be able to use that user.agency_id as a good starting estimate, we should still allow them to select any of the other agency ids within the tenant. This is particularly important because some governments might have users who are doing the reporting work for multiple agencies, and so they can't be exclusively tied to a single agency.



> is it acceptable for this to happen later as part of the post-persistence validation phase, as it currently does?
That should be fine. We can add a validation error that will check the value stored in the db and the (possible) value stored in the worksheet and throw an error if they mismatch



Let me know if I missed anything!

**Comment by NatHillardUSDR** [comment]
Thanks @trumanc for the clarifications! I've updated the patch to consult the user's tenant's list of agencies based on your feedback. The patch is now ready for review
