### ISSUE TITLE
Add messaging for how to reach out to get access to the app

### ISSUE THREAD

**Issue by cmroberts** [usdigitalresponse/usdr-gost#9]
We'll want to provide a public facing way for users to create a new account with us so they can use the hosted grants id tool. 

Today an initial admin user is initially seeded to the database and that user is used to invite others; we'll want to have a way for users to self-register as the initial admin user for a new tenant.

**Comment by mhuang-usdr** [comment]
We've decided to keep the experience as B2B first, so instead of a signup experience, we should add this language to the landing page:

> "To create an account for your government, please fill out [USDR's request form](https://www.usdigitalresponse.org/request-help/) and indicate that you'd like to an account on our Hosted Grants Tool."

**Comment by mattbroussard** [comment]
@mhuang-usdr The link in the comment above appears to 404 now. Should we instead link to:
- the [Contact Us](https://www.usdigitalresponse.org/contact-us) page
- the [Request Support](https://form.jotform.com/201195733501145) form itself on Jotform, linked from the Contact Us page

My intuition is it's safer to link to the Contact Us page in case the Jotform URL changes in the future.

**Comment by mhuang-usdr** [comment]
Good catch, let's link to the Contact Us page!
