### ISSUE TITLE
[ID] Send email reminder if an `Interested` or `Assigned` grant has an upcoming closing date

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#933]
New email feature request from a partner - send a reminder email to a user if they belong to an agency that has a grant marked:

- `Interested`
- `Assigned`

That has an upcoming closing date within the `Danger` threshold that the agency has set.

**Comment by ClaireValdivia** [comment]
Closing this as we will wait for recommendations from collab cohort
