### ISSUE TITLE
[ID] Make opting into email notifications more visible

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/usdr-gost#936]
In #935, we are setting email notifications to off by default.

Open UX question - is there an easy way to make opting into email notifications more visible from the ID tool side? Help text, popup, etc.

**Comment by mhuang-usdr** [comment]
Notes:

- Toggle in a banner?
- Tooltip about turning off after?

**Comment by cajinajr** [comment]
Opting for a toggle switch in a pop-up banner. Below are mockups for the default state and toggle-activated state

![Image](https://user-images.githubusercontent.com/16214088/221940607-13440bd4-c0dd-45ff-9d1d-6ff9fbb4da7f.jpg)



![Image](https://user-images.githubusercontent.com/16214088/221940615-86459386-c12b-436a-9829-1fc4ff1cdcce.jpg)


Below are the same screenshots but with redlines included


![Image](https://user-images.githubusercontent.com/16214088/221940720-8ceef220-b9bf-43b3-8c22-8bdd966929b5.jpg)



![Image](https://user-images.githubusercontent.com/16214088/221940734-64366033-b715-4a47-8182-8ada175518e6.jpg)

**Comment by misspran** [comment]
![Image](https://user-images.githubusercontent.com/3173822/228623666-7c235e6c-6084-4050-b664-774473f60661.png)

I'm pretty much done with this, let me know if there's any visual tweaking needed. Otherwise I can put out the PR to get reviewed.

**Comment by mhuang-usdr** [comment]
lgtm, defer to @cajinajr for the last check!

**Comment by cajinajr** [comment]
Looks good to me too! Thanks!

**Comment by misspran** [comment]
I just noticed in the settings visually in user preferences UI there’s 2 options:
`Grant assignments and New Grants Digest`
 but when you call the fetch the user there’s 3 email options a user can subscribe to.
```
GRANT_ASSIGNMENT
GRANT_DIGEST
GRANT_INTEREST
```
Is Grant Interest still a thing? Should I add Grant Interest toggle to the preferences UI?
