### ISSUE TITLE
Include source program in Grant Details details modal

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/usdr-gost#940]
**DOD:** When a non-null `source_details` value is available for a grant, it shows up in the "Grant Details" modal.

**Blockers:**
- usdigitalresponse/grants-ingest#13 
- usdigitalresponse/usdr-gost#938 
- **Note:** Both of the above tickets are a "soft block"; the new field should only display when the `source_details` property exists and is non-null, so this ticket can be worked on at any point. However, it will not have any effect until the work from these other tickets has been implemented.

**Implementation details:**
- Modify the "Grant Details" modal to add a new field, labeled "Source Details", that displays the `source_details` value provided by a grant object returned by the GOST API.
- Make the new "Source Details" field conditional, so that it only displays when the value is not null or empty
- Ensure the display logic degrades gracefully so that when the `source_details` property is missing entirely, it is treated the same as a null value.

**Mocks:**
![grant details modal](https://user-images.githubusercontent.com/1851017/217975422-d06480d9-15ad-4281-8c2a-12ad37948e6a.png)

**Comment by mhuang-usdr** [comment]
Contingent on more info from Pari - do we have enough info from all programs or will we just expose IIJA.

**Comment by caitlinwinner** [comment]
Green light to build against the above mock. "Source program" Matches the position in the search window, below opportunity category (https://github.com/usdigitalresponse/usdr-gost/issues/1479)

**Comment by ClaireValdivia** [comment]
Closing this as out of date as we now have Appropriations Bill field. @TylerHendrickson please let me know if there are still relevant items to be done from this!
