### ISSUE TITLE
Change text of browser tab from 'client' to whatever UX folks think is better

### ISSUE THREAD

**Issue by chrisxkeith** [usdigitalresponse/usdr-gost#948]
![image](https://user-images.githubusercontent.com/3921494/218501383-01b0560e-7d57-43ae-81bf-c655cbea366a.png)

**Comment by TylerHendrickson** [comment]
@mhuang-usdr To add specs for design

**Comment by mhuang-usdr** [comment]
new text: `USDR: Grants`

**Comment by cajinajr** [comment]
I'm a little late chiming in on this so please ignore if no longer needed but I thought the options below could be good:

- ARPA Reporter | USDR
- Grant ID Tool | USDR

**Comment by misspran** [comment]
![Image](https://user-images.githubusercontent.com/3173822/227819371-60beb016-fcf7-4a8f-af90-c73908d528cd.png)
![Image](https://user-images.githubusercontent.com/3173822/227819372-d76d1fd0-65f4-4929-91de-6defde795928.png)

Let me know if you guys prefer something else.
