### ISSUE TITLE
Research an automated testing framework for the usdr-gost repository

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#982]
## Current State
- The test coverage for the ID and ARPA tool is sparse. Most of the tests are on the serverside of the ID Tool.
- No tests for the client-side

## Expected State
- Proposal for how to approach testing within the ID tool
- Suggestions for tools/packages we need to add to the repository to support the new testing framework
- Example code/pseudocode for how to write tests moving forward
- Plan of action on how to improve test coverage

## Implementation Details
- NA

**Comment by as1729** [comment]
Agreed on using Cypress for UI automation

Next steps - do the Cypress impelmetation in the gost-repository.

**Comment by swatisqa1** [comment]
First 2 items are completed: See [](https://docs.google.com/document/d/1g1LaPidzmcxSmCkXF_rXnrEtNT71pAOVsxNpSyqAGMQ/edit?usp=sharing)

**Comment by swatisqa1** [comment]
Creating separate tickets for remaining 2 items

**Comment by as1729** [comment]
Created
- #1066
- #1067 
- #1068

**Comment by ClaireValdivia** [comment]
closing this as research is completed; execution still needed
