### ISSUE TITLE
Workbook downloads are broken with 500 error

### ISSUE THREAD

**Issue by trumanc** [usdigitalresponse/usdr-gost#993]
In an email from Marcus on Tuesday Feb 21, titled `ARPA Workbook not Downloading`, he reported that all workbook downloads for Rhode Island are failing with 500 errors. I confirmed that I can't download any workbooks, either in the RI account, or the USDR test account. Those downloads fail with the following error:
![Screenshot 2023-02-21 at 9 26 31 AM](https://user-images.githubusercontent.com/3675290/220417814-c6582166-ac85-4839-a890-5197dffca93c.png)

Note: Someone with render access will have to help investigate this since no useful error info is being pushed to the front-end. I'm not sure who all that includes after we started removing people as a result of their new per-person pricing changes.

**Comment by TylerHendrickson** [comment]
Fixed by #994
